### PR TITLE
Revert "Added the link of my blog (#534)"

### PR DESCRIPTION
**Pull request by Vishwajeet-TheTechy**
This reverts commit 6d9a370b161aff15e91d99e0e7dd4ead58746bd3.

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — COMMENTED** [review]
Please read the readme.md on how to add your blog.
You first need to  fork the repository

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Review by ParthS007 — COMMENTED** [review]
@Vishwajeet-TheTechy Closing this PR due to many conflicts and inactivity.Please read `README.MD` on how to add a blog and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

**Pull request closed without merging**
