### PR TITLE
My blog 

### PR DESCRIPTION
**Pull request by vanshsingla**
Author name-Vansh Singla

https://vanshsingla009.wordpress.com/2018/01/14/gci-2018-fossasia/

Title- GCI-2018-FOSSASIA

[Blog PR.txt](https://github.com/fossasia/gci17.fossasia.org/files/1629352/Blog.PR.txt)

### CODE REVIEW

**Review by rupav — CHANGES_REQUESTED** [review]
Refer this https://github.com/fossasia/gci17.fossasia.org/pull/917. You need to add blog url correctly. and an image for the same to the end of the _data/blogs.yml.
Refer above PR to take help.

**Review by nikit19 — COMMENTED** [review]
Please send your PR from the gh-pages branch.
You are sending it from the revert-534-gh-pages branch

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please don't delete existing code which contains someone else's blog. Add your details following the same pattern after line no 199.

**Review by anshumanv — COMMENTED** [review]
Refer README too see steps about how to add.

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@vanshsingla  Please read README.MD on how to add a blog and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Status of the PR ?

**Comment by vaibhavsingh97** [comment]
@vanshsingla Update please

**Comment by NaviRocker** [comment]
It's better to close the PR

**Review by nzec — CHANGES_REQUESTED** [review]
No need for a new blog now.

**Comment by rupav** [comment]
Closing this, because of no update.

**Pull request closed without merging**
