### PR TITLE
Added Shubham Kumar as a Mentor

### PR DESCRIPTION
**Pull request by sahildav**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included  screenshot showing after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.

# Changes done in this Pull Request

-Before 
screenshot from 2018-10-23 23-04-09
After
screenshot from 2018-10-23 22-56-10

### CODE REVIEW

**Comment by sahildav** [comment]
@sk9331657  Please review .

**Comment by championpaddler** [comment]
@abishekvashok  Reviews??

**Comment by championpaddler** [comment]
@mariobehling  Review?? Shall I merge this ??

**Review by tabesin — APPROVED** [review]
looks good

**Comment by akshatnitd** [comment]
@tabesin @sk9331657 Why was this PR merged and approved? 

@sk9331657 Were you a mentor the previous year?

**Pull request merged**
