### PR TITLE
Fixed #665: Delete lokinder singh

### LINKED ISSUE #665: Lokhinder singh
The image has to be deleted as it was added by mistake

### PR DESCRIPTION
**Pull request by samyakbvs**
screen shot 2017-12-31 at 11 56 05 am
This is the PR which initially deleted the image but some thought it was an issue as only the image was deleted and restored the image
Now the whole block for Lokhinder Singh has been deleted

### CODE REVIEW

**Comment by saarthakchats** [comment]
Why are you deleting the whole block? Why remove Lokinder Singh

**Comment by saarthakchats** [comment]
And it's Lokinder not Lokhinder

**Comment by samyakbvs** [comment]
screen shot 2017-12-31 at 12 05 43 pm
 Screenshot after local deploying the page

**Comment by samyakbvs** [comment]
screen shot 2017-12-31 at 12 06 32 pm
 Screenshot of the original site

**Review by saarthakchats — CHANGES_REQUESTED** [review]
Why did you remove him? What was the problem?

**Comment by samyakbvs** [comment]
Whatever it is, it was supposed to removed

**Comment by samyakbvs** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/651 - anyone having any confusion pls see this PR

**Comment by saarthakchats** [comment]
Who said that

**Comment by samyakbvs** [comment]
See the PR link mentioned in the comment above @saarthakchats

**Comment by saarthakchats** [comment]
I believe that that guy had a problem with the old image he had added. He didnt want himself scrubbed off the website

**Comment by samyakbvs** [comment]
But still the image that was added was wrong and we don't know which is the right one so we will have to remove the whole block

**Comment by saarthakchats** [comment]
I think you should Lokinder before removing him from the website

**Review by saarthakchats — CHANGES_REQUESTED** [review]
Squash your commits please, rest is fine

**Review by saarthakchats — APPROVED** [review]

**Comment by samyakbvs** [comment]
Clsoing this one and making a new one

**Pull request closed without merging**
