### PR TITLE
Update mentors.yml and add hung.jpg into img/mentors

### PR DESCRIPTION
**Pull request by Jerry2001**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Update mentors.yml and add hung.jpg into img/mentors

### CODE REVIEW

**Comment by Jerry2001** [comment]
OMG, how can i resolve this conflict. This is my first time :(

**Comment by anshumanv** [comment]
Don't worry, click on `Resolve Conflicts` button and the editor will guide you through the places in your code where merge conflicts are present, resolve them.

**Comment by Jerry2001** [comment]
I think I have resolve the conflict

**Comment by Jerry2001** [comment]
However, I accidentally "Set theme jekyll-theme-cayman"

**Comment by anshumanv** [comment]
Not yet, please see.

**Comment by Jerry2001** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/158/commits/43b0e9175ade8e137a63891c275148c0d0f4d78d
Is it right?
I think I am messing thing up :(

**Comment by anshumanv** [comment]
There's a `Resolve Conflicts` button here, please click on it and follow.

**Comment by Jerry2001** [comment]
Hey, did i make it correctly?

**Comment by anshumanv** [comment]
Yes, conflicts have been resolved, please remove the extra file you added `_config.yml` that appeared from selecting the theme.

**Comment by Jerry2001** [comment]
May I ask you a question? In every pull request, there maybe a lot of commits. Do you have to merge all of them or you can select it?

**Comment by Jerry2001** [comment]
I have just removed it

**Comment by anshumanv** [comment]
I'll squash merge them, mean they will be added as a single commit, but ideally, you should rebase your branch and squash your commits so a single commit remains.
Please learn how to squash your commits from next time on.

**Comment by anshumanv** [comment]
File is still present, only the content in it has been deleted, please delete the file entirely. :smile:

**Comment by Jerry2001** [comment]
Yahm i did delete it

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Good Job!

**Pull request merged**
