### PR TITLE
Added my Photo to the GCI FOSSASIA Site Student Section

### PR DESCRIPTION
**Pull request by Jeewal**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request
In this pull request I have updated the Student.yml file and added a picture of mine in the respective folder. This is to add my profile on GCI FOSSASIA Site Student Section.
The preview link is as follows:
https://jeewal.github.io/gci17.fossasia.org/students

### CODE REVIEW

**Review by gabru-md — APPROVED** [review]
Approved

**Comment by gabru-md** [comment]
@harshit98 Please merge

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Please try to squash your commits from next time. :smile: 
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by Jeewal** [comment]
Okay ! :) 
@anshumanv

**Pull request merged**
