### PR TITLE
Fixed #506: Enhanced contributors section

### LINKED ISSUE #506: Link to Gci'16 contributors
### Expected results
Link to Gci'16 contributors should be added
### Actual results
Link to Gci'16 contributors isn't added
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
What did you enhance exactly? Preview Link? Please specify appropriate details in the PR comment.

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/smyak-gci17.fossasia.org/

**Comment by samyakbvs** [comment]
screen shot 2017-12-25 at 10 44 41 pm

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by anshumanv** [comment]
Please make sure you open an issue before proposing any change, reference the issue in the PR comment and specify all the changes with preview link in the first step itself. Don't do so only when someone requests, this isn't the first time I'm seeing you do this.

**Review by vaibhavsingh97 — COMMENTED** [review]
Please change commit message to `Fixes #<issue-number>: <commit message>`. Also, add fixes, solvesxetc #<issue-number> in the PR  message. This will automatically closes PR when PR got merged. read more about it here: https://help.github.com/articles/closing-issues-using-keywords/

**Review by harshit98 — APPROVED** [review]
I'll merge this once travis ci passes. LGTM. 💯

**Comment by samyakbvs** [comment]
Closes #506

**Pull request merged**
