### PR TITLE
Fixes #488 : Piyush Raj was added twice

### LINKED ISSUE #488: Piyush Raj is added twice in the students' section
### Expected results
All students added once
### Actual results
Piyush Raj Added twice
### Steps to reproduce the issue
Remove one of the two
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #488 

#Things Done 
Removed one of the two profiles of @0x48piraj from the students' section.

### CODE REVIEW

**Review by 0x48piraj — APPROVED** [review]
LGTM! :tada:

**Comment by saarthakchats** [comment]
@0x48piraj :)

**Review by nzec — APPROVED** [review]
No one noticed!

**Comment by saarthakchats** [comment]
I know, even I felt weird when I saw it being repeated

**Comment by ParthS007** [comment]
@saarthakchats  Preview link, please ?

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/gctahtsi1/
@ParthS007

**Review by abishekvashok — APPROVED** [review]

**Comment by saarthakchats** [comment]
Please merge

**Comment by saarthakchats** [comment]
@ParthS007

**Review by saurabhjn76 — APPROVED** [review]

**Pull request merged**
