### PR TITLE
Blog Image

### PR DESCRIPTION
**Pull request by ZiadElKhattabi**
url: https://ziadelkhattabi.wordpress.com/2017/12/11/first-blog-post/
title: BETWEEN THE COLORED LINES
img: computer-programming.jpeg
author_name: Ziad El Khattabi
computer-programming

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
You have uploaded the image correctly but please also include the code that you wrote in the other pull request

**Comment by nikit19** [comment]
And the dimensions of your image should be 240 x 240 pixels

**Comment by ZiadElKhattabi** [comment]
what about now?

**Comment by nikit19** [comment]
I don't see any changes

**Comment by ZiadElKhattabi** [comment]
and now?

**Comment by ZiadElKhattabi** [comment]
please I do not have time left in my task

**Comment by harshit98** [comment]
@ZiadElKhattabi Share your task link here. Deadline will be extended by the mentors. Take your time, don't worry.

**Pull request closed without merging**
