### PR TITLE
Added Contributors

### PR DESCRIPTION
**Pull request by supunTE**
Added contributors to the gci17.fossasia.org web site.

### CODE REVIEW

**Review by jigyasa-grover — COMMENTED** [review]
Just a kind suggestion, try using the API perhaps and not adding each contributor manually ?

**Comment by nzec** [comment]
@jigyasa-grover Currently, there is no API for contributors. There is one for the Mentors.

**Comment by abishekvashok** [comment]
@duttaditya18 @jigyasa-grover was reffering to the Github API to get contributions.

Here's a reference: https://developer.github.com/v3/repos/#list-contributors

**Comment by poush** [comment]
Closing it for, #82

**Pull request closed without merging**
