### PR TITLE
Adds Hover effect on projects

### PR DESCRIPTION
**Pull request by saarthakchats**
#Problem
The names displayed are not looking good
#What did I do?
Added a new hover effect which is looking nice

### CODE REVIEW

**Comment by saarthakchats** [comment]
Sorry for that commit name. :)

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/gci17.fossasia.lozicorg/
Deployment link

**Comment by nzec** [comment]
I don't see anything new.

**Comment by saarthakchats** [comment]
See the Student Projects section @duttaditya18

**Comment by saarthakchats** [comment]
screenshot 92
The name display was looking like this (bad)

**Comment by saarthakchats** [comment]
screenshot 93
Now its like this (nice)

**Comment by saarthakchats** [comment]
@duttaditya18

**Comment by saarthakchats** [comment]
@ms10398  @gabru-md

**Review by the-codingninja — APPROVED** [review]

**Comment by saarthakchats** [comment]
@ms10398 
Now can I submit my task?

**Review by gabru-md — CHANGES_REQUESTED** [review]
Change the PR name to something like:
`Adds Hover effect on projects`
rest LGTM , then will be approved and merged

**Comment by saarthakchats** [comment]
@gabru-md 
Pls merge

**Review by gabru-md — APPROVED** [review]
good

**Comment by saarthakchats** [comment]
https://codein.withgoogle.com/dashboard/task-instances/4594119936573440/
Pls also approve my task after you merge. @gabru-md @ms10398 
No pressure :)

**Comment by saarthakchats** [comment]
@ParthS007 @gabru-md @ms10398 
Thank you!

**Pull request merged**
