### PR TITLE
Added a video

### PR DESCRIPTION
**Pull request by supunTE**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
https://github.com/fossasia/labyrinth/pull/455
- https://STEdirisuriya/gci17.fossasia.org
Added video about labyrinth

### CODE REVIEW

**Review by nikit19 — COMMENTED** [review]
Looks good. Please provide a preview link

**Review by rupav — CHANGES_REQUESTED** [review]
Resolve conflicts. Video looks amazing. Very well executed. Great job ✨ 👏👏👏

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Review by rupav — COMMENTED** [review]
Provide a preview link and squash your commits.

**Pull request closed without merging**
