### PR TITLE
Added Student info

### PR DESCRIPTION
**Pull request by RajKhare**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Added new Student info in the Student Section (GCI): "Raj Khare"  in  _data/students.yml
- Added profile picture "rajkhare.png" in img/students
- Test Link: https://rajkhare.github.io/gci17.fossasia.org/
screen shot 2017-12-27 at 20 50 43

### CODE REVIEW

**Review by nikit19 — APPROVED** [review]
LGTM !

**Review by saurabhjn76 — APPROVED** [review]
Thanks 👍  , please squash you commits

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
@RajKhare Please squash commits from next time since you are a first-time contributor merging this.
Please go through this for squashing commits [https://gist.github.com/patik/b8a9dc5cd356f9f6f980](https://gist.github.com/patik/b8a9dc5cd356f9f6f980)

**Comment by RajKhare** [comment]
Oh Sure!

**Pull request merged**
