### PR TITLE
Fb div width - solves #361

### PR DESCRIPTION
**Pull request by shikhar-scs**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

The Fb scroll feed of fossasia page was not showing complete width. This issue has been fixed.
social media 1

 Also as mentioned by me in #361 the iframes lacked responsiveness and never changed irrespective of change n dimensions. 

Thus, that issue has also been cleared with the help of media queries. By nature iframes are not responsive an d always maintain there dimensions. So media queries were used. I've used 2 break points and they have been mentioned in my commit.

As the dimensions at any given time is fixed thus actual moving responsiveness cant be seen. However at the breaking points of 1200px and 768px they can be seen shifting . The top bar contains the width in each of the cases.
social media 2
social media 3

 
- Replace this with your change description

### CODE REVIEW

**Comment by shikhar-scs** [comment]
I'm sorry for the alarming no. of commits here. I've committed only twice for this issue. The others follow because of my last PR which I had made #330. Please guide me how to remove this.

preview link is [here](https://shikhar-scs.github.io/gci17.fossasia.org/)

**Review by nzec — APPROVED** [review]
Looks good. Please learn how to squash commits.

[This is a good article to learn how to do that.](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

**Comment by shikhar-scs** [comment]
thankyou @duttaditya18

**Comment by shikhar-scs** [comment]
@ParthS007 @anshumanv please review and merge

**Comment by shikhar-scs** [comment]
I've filed another PR after squashing my commits please review that

**Comment by himanish-star** [comment]
@duttaditya18 , I have one doubt which I would like to ask here in reference to commits 287258a and e5751aa. How do you squash these two , as commit 287258a is basically a merge commit and that doesn't become available for squashing . I have encountered this problem another place that's why I thought so of asking here

**Pull request closed without merging**
