### PR TITLE
Fixed Menu bar in students.html and mentors.html

### LINKED ISSUE #249: Menu bar not working
### Expected results
When you go to students page and click welcome tab welcome section in the home page must be shown.
### Actual results
When you go to students page you can't to come again to home page using menu bar.
And other menu bar buttons are same.
### Steps to reproduce the issue
Give correct link in to menu bar buttons, If you click mentor tab added "#mentors" to the URL. It works when you in home page. If you in another page like students page just click mentor tab you will not come for home page.
## Would you like to work on this
Yes

### LINKED ISSUE #254: Menu Bar options don't work after we click see more
### Expected results
Clicking on any option in the menubar at https://gci17.fossasia.org/students should lead normally to the page expected.

### Actual results
Menubar won't work on pages like https://gci17.fossasia.org/{attribute}
Due to single page design and anchor references.

### Steps to reproduce the issue
Go to https://gci17.fossasia.org/students or https://gci17.fossasia.org/mentors 
and try menubar

## Would you like to work on this
No, GCI Students grab this one.

### PR DESCRIPTION
**Pull request by nzec**
You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

* Fixed Menu bar in students.html and mentors.html
* Fixes #254
* Fixes #249 

https://duttaditya18.github.io/gci17.fossasia.org/mentors
https://duttaditya18.github.io/gci17.fossasia.org/students

*I went all paranoid on why the mentor and students buttons were not working. Turned out I did a stupid mistake.* 😄

### CODE REVIEW

**Comment by anshumanv** [comment]
@duttaditya18 try to provide a link, if not, please post screenshots/gifs atleast. :smile:

**Comment by nzec** [comment]
@anshumanv Okay! Sorry. I was linking the wrong thing. Here check it out: 
https://duttaditya18.github.io/gci17.fossasia.org/students
https://duttaditya18.github.io/gci17.fossasia.org/mentors

**Comment by duttaditya18** [comment]
@anshumanv 
>If you click the Student and Mentor button in index.html, it would not work because the baseurl is set to blank.
And in this case, it is thinking of the baseurl as https://duttaditya18.github.io.
But in the actual website, it would say that it is gci17.fossasia.org

**Comment by nzec** [comment]
@anshumanv Okay! So I managed to fix that as well!

**Comment by nzec** [comment]
>I went all paranoid on why the mentor and students buttons were not working. Turned out I did a stupid mistake. 😄

**Review by anshumanv — APPROVED** [review]
Everything seems to be functional.

**Comment by nzec** [comment]
@anshumanv Thanks!

**Review by abishekvashok — APPROVED** [review]
ack https://github.com/fossasia/gci17.fossasia.org/commit/9b8d88d7d601a04673db81d6715dd6a4de72e0b9

**Review by ParthS007 — APPROVED** [review]
LGTM !

**Comment by nzec** [comment]
@ParthS007 Thanks!

**Pull request merged**
