### PR TITLE
GEOLOCATION TASK 

### PR DESCRIPTION
**Pull request by ShivamRai2003**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by rupav — APPROVED** [review]
You could have done earlier this thing. Keep in mind for next PRs. Provide a preview link too.

**Comment by ShivamRai2003** [comment]
https://codein.withgoogle.com/dashboard/task-instances/6169904195567616/
PLZZ APPROVE THIS

**Comment by ShivamRai2003** [comment]
YOU ARE MENTOR

**Comment by rupav** [comment]
Yes, you need to provide a preview link.

**Comment by ShivamRai2003** [comment]
https://shivamrai2003.github.io/Hello-world/

**Comment by ShivamRai2003** [comment]
approve now plzz

**Comment by rupav** [comment]
Atleast respond to my review. Preview link is https://shivamrai2003.github.io/gci17.fossasia.org/.

**Pull request merged**
