### PR TITLE
Aligned the github icon

### PR DESCRIPTION
**Pull request by samyakbvs**
#417

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/123-gci17.fossasia.org/

**Review by supunTE — CHANGES_REQUESTED** [review]
Add there small description about your change, and please add two screen-shots that showing actual result and expected result!

**Comment by nzec** [comment]
It is already aligned.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Specify which github icon, by posting a screenshot.

**Comment by vaibhavsingh97** [comment]
@samyakbvs when you send this type of PR than please send Actual result and expected result screenshot

**Comment by samyakbvs** [comment]
Expected
screen shot 2017-12-23 at 1 56 18 am
Actual 
screen shot 2017-12-23 at 1 55 54 am

**Comment by samyakbvs** [comment]
Done @vaibhavsingh97

**Review by vaibhavsingh97 — APPROVED** [review]

**Comment by samyakbvs** [comment]
Pls merge

**Pull request merged**
