### PR TITLE
Fixed #516: Added a mentor

### LINKED ISSUE #516: Add a mentor
Nikit bhandari is not added
Working on it!!

### PR DESCRIPTION
**Pull request by samyakbvs**
Closes #516

### CODE REVIEW

**Review by NaviRocker — APPROVED** [review]
LGTM!

**Review by nzec — APPROVED** [review]
Looks good!

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Preview link please

**Comment by samyakbvs** [comment]
Sorry i forgot

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/mentor-gci17.fossasia.org/mentors
@ParthS007

**Review by ParthS007 — COMMENTED** [review]
@samyakbvs  I am not able to see the mentor 
image

**Comment by samyakbvs** [comment]
but there is no problem in the code

**Comment by samyakbvs** [comment]
@ParthS007

**Review by ParthS007 — APPROVED** [review]
Ok. I am approving it, Please wait for other mentor's review 👍

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
>Sorry i forgot

Make sure you add the link in the PR template and also mention your changes there.

**Comment by nikit19** [comment]
@samyakbvs  the twitter link is not working. My twitter handle is NikitBhandari. There is no space, Please fix it

**Pull request merged**
