### PR TITLE
Fixes #606 : Added Animations in activities.html

### LINKED ISSUE #606: Add on-scroll animations in activities.html
### Expected results
There are on-scroll animations in activities.html.

### Actual results
Currently there are no animations in `activities.html`

### Steps to reproduce the issue
Add on-scroll animations using the **AOS Libirary**

### Would you like to work on this
Yes.

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
* Added on-scroll animations using the AOS Libirary.
* Fixes #606 

***Preview Link : https://duttaditya18.github.io/gci17.fossasia.org/activities***

---
*This was suggested by @0x48piraj!*

### CODE REVIEW

**Review by abishekvashok — COMMENTED** [review]
Animations looks great.
Good work.
But however the only thing that prompts me to scroll down is the scroll bar, can we have more accessible UI? Any thoughts?

**Review by 0x48piraj — APPROVED** [review]
LGTM! :tada: 
Looking cool !! :heart:

**Comment by nzec** [comment]
@abishekvashok Will work on that! Thanks for the feedback.

**Comment by nzec** [comment]
Oops. Closed by mistake! 😄

**Comment by arjunpandey2003** [comment]
Its looking good

**Review by arjunpandey2003 — APPROVED** [review]

**Comment by 0x48piraj** [comment]
@abishekvashok We can just implement the rocket slider which was developed by @STEdirisuriya 
:+1: 

What do you say @duttaditya18 ?

**Comment by nzec** [comment]
Can this be merged? And then someone else can work on the slider going down? 😄

**Comment by 0x48piraj** [comment]
> But however the only thing that prompts me to scroll down is the scroll bar, can we have more accessible UI? Any thoughts?

Just a thought @duttaditya18  :smile: 
Is it not good ?

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@duttaditya18  Please resolve conflicts 👍

**Comment by nzec** [comment]
@ParthS007 Done

**Comment by nzec** [comment]
@ParthS007 @0x48piraj @abishekvashok Made a new PR here : #631

**Pull request closed without merging**
