### PR TITLE
Student and blog section changes, add Polish Thank You

### PR DESCRIPTION
**Pull request by kubami9**
Student section: add Kuba Michalski image, delete 2 additional Naveen Rajan images (still one is left :+1: )
Blog section: add Kuba Michalski blog article
Add "Thank You For Contributing" in Polish

### CODE REVIEW

**Comment by isuruAb** [comment]
@kubami9  could you please give a preview link

**Comment by kubami9** [comment]
Sure :)
https://kubami9.github.io/gci17.fossasia.org-kuba-michalski-editing/

**Review by isuruAb — APPROVED** [review]

**Review by SaptakS — APPROVED** [review]

**Review by dynamitechetan — APPROVED** [review]

**Comment by kubami9** [comment]
Could you please check if this can be merged? It's getting more and more conflicts to resolve, after this pull request will be merged I could work on the next tasks, website improvements and translations for FOSSASIA :)

**Review by ParthS007 — APPROVED** [review]
Good Work @kubami9  ! Keep it up

**Comment by ParthS007** [comment]
@kubami9  Please submit your task for review if not submitted yet.

**Comment by kubami9** [comment]
Thank you @ParthS007! Already submitted yesterday :)

**Pull request merged**
