### PR TITLE
Aligned some stuff to center and fixed one of students projects' link

### LINKED ISSUE #362: One of students projects' link is broken!
### Expected results
Make it correct.

### Actual results
One of student projects' link is broken in Students Projects Section.
st
Doon International School project by @YashKumarVerma is not working.
See below picture that came after I clicked that project.
st2

### Steps to reproduce the issue
Add correct link to that project or, remove that project.

## Would you like to work on this
@YashKumarVerma Please add correct link.

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

* Aligned Blog, videos, Projects to center.
* Fixed @YashKumarVerma's broken project link.
* Fixes #362 and 3rd point of #269 

**Here is the preview link :** https://duttaditya18.github.io/gci17.fossasia.org/

---

### CODE REVIEW

**Comment by nzec** [comment]
Ping @fossasia/fossasia-gci

**Comment by saarthakchats** [comment]
This is not required.

**Comment by samyakbvs** [comment]
Yes I agree it is irrelevant

**Comment by saarthakchats** [comment]
screenshot 73
What is this?

**Comment by nzec** [comment]
@saarthakchats I don't see that. Let the whole page load first.

**Comment by nzec** [comment]
@saarthakchats @ samyakbvs I did these changes because they were in an issue. I don't think they are *"Irrelevant"*.

**Pull request closed without merging**
