### PR TITLE
Added Thank You For Contributing in Russian language 

### PR DESCRIPTION
**Pull request by DotSlashTX**
Благодарю за помощь

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please exclude older commits.

**Comment by anshumanv** [comment]
And resolve conflicts.

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@FreakinBabaJi Please do the suggested changes.

**Review by isuruAb — COMMENTED** [review]
please exclude old commits and resolve conflicts

**Review by abhinavk96 — COMMENTED** [review]
@FreakinBabaJi Any updates on this?

**Comment by ParthS007** [comment]
Closing this PR due to inactivity , Please create a new PR 👍

**Pull request closed without merging**
