### PR TITLE
Added myself in the FOSSASIA website

### PR DESCRIPTION
**Pull request by itsguneetsingh**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please make sure that the dimensions of your image is 240 x 240 pixels

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash your commits

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts and squash your commits.

**Review by ParthS007 — COMMENTED** [review]
@Guneetconvent2002 Closing this PR due to many conflicts and inactivity.Please read `README.MD` on how to add a student and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

**Pull request closed without merging**
