### PR TITLE
Blog Image#692

### PR DESCRIPTION
**Pull request by ZiadElKhattabi**
url: https://ziadelkhattabi.wordpress.com/2017/12/11/first-blog-post/
title: BETWEEN THE COLORED LINES
img: computer-programming.jpeg
author_name: Ziad El Khattabi
computer-programming

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
please upload a 240x240 sized image.

**Review by nikit19 — CHANGES_REQUESTED** [review]
You have to make these changes in the blogs.yml file and also upload a picture

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Please check the README file to see how to add the blog in correct format

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Upload the related picture to `img` dir

**Review by ParthS007 — COMMENTED** [review]
@ZiadElKhattabi Please go through README.md on how to add a blog and make a new PR.You can ask on FOSSASIA gitter channel if you face any difficulty. 👍

**Pull request closed without merging**
