### PR TITLE
Developed Site

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixed issue of a lot of links ending up nowhere and getting back to the site again. Also added relevant content to a fitness section instead of simple Lorem Ipsum. Added more useful links.

### CODE REVIEW

**Comment by saarthakchats** [comment]
The above commits except "Developed site" are already merged

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Now as you have already 2-3 PR's merged please update your fork as your previous commits are listed in it

**Comment by saarthakchats** [comment]
Shall I close this and then make a new Pull Request.

**Comment by the-codingninja** [comment]
You can just update your fork you need not to make a new Pull Request

**Comment by saarthakchats** [comment]
How should I update fork? I don't know how

**Comment by the-codingninja** [comment]
https://help.github.com/articles/syncing-a-fork/
https://gist.github.com/CristinaSolana/1885435

**Comment by saarthakchats** [comment]
I am having some trouble. I am making a new pull request. Please merge that.

**Comment by saarthakchats** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/203
This is the new PR. Please merge this one

**Pull request closed without merging**
