### PR TITLE
Enhanced the social media section

### PR DESCRIPTION
**Pull request by ryushar**
Screenshot

### CODE REVIEW

**Comment by harshit98** [comment]
@2coolife Hi Tushar. Can you enhance `Join The Conversation` message above social icons? It does not looks neat. It can be more improved. :)

It would better if you can remove `Join The Conversation` message. Keep the FOSSASIA logo and social icons row on the same level. It will look clean. 

Your PR deployment link: https://2coolife.github.io/gci17.fossasia.org/

**Comment by ryushar** [comment]
Done! :smile: 

Screenshot

**Review by NaviRocker — CHANGES_REQUESTED** [review]
Why Did You Remove the Social Media Feeds from the Website?

**Comment by ryushar** [comment]
You mean the widgets? 
Twitter widget was not needed since it was already implemented properly using twitter api (latest feeds section), the youtube iframe too was used in the webpage in an upper section, the Instagram widget was not even showing correct images (and can't because fossasia instagram account is empty), rest left were flicker and facebook widget.
Sorry, but i don't think they were looking nice with the footer theme, more over since they were just widgets and not full api implementations, it wasn't possible to customize them that much, and were not even responsive to screen sizes (had different size proportions too and thus weren't even aligning properly), therefore I removed them.
Thats just my thought but if those widgets are really needed, they can be added back. :)

**Comment by NaviRocker** [comment]
It's Fine and If you can implement the Facebook API and add Facebook feeds somewhere on the Page it's better. Also, the Google+ and Flickr if you can.

**Comment by NaviRocker** [comment]
And Please Squash your Commits

**Comment by NaviRocker** [comment]
tgtht
This is not responsive.

**Comment by ryushar** [comment]
Hmm seems like too many icons not good for smaller screens, and facebook api needs access token, which would either require user login or me providing an app token or something ( which would most probably require server side authorisation setup because I don't want to leak my private access keys). Even after this, the tokens would keep getting expired after a certain amount of time. Its same with google+ and flickr api, so it would be headache to work with.
And the widgets that were present before are just widgets not api implementations.
Ill still try finding a way to implement facebook api etc  maybe if fossasia could themself provide the page tokens (again this method too isn't safe).

img_20171202_234612
These are widgets and not api implementations.

**Comment by ryushar** [comment]
Made social icons responsive too and squashed all commits in single commit.

screenshot 320px
Doesn't break even on screen as small as 320px wide too now!

screenshot 1920px

**Review by abhinavk96 — APPROVED** [review]

**Review by abhinavk96 — CHANGES_REQUESTED** [review]
image
Can you make the links https please :)

**Comment by ryushar** [comment]
changed some http links to https before too, don't any more http links are there now.

**Comment by ryushar** [comment]
No more http over https now :+1: 
screenshot from 2017-12-03 12-48-06

**Review by abhinavk96 — APPROVED** [review]

**Pull request merged**
