### PR TITLE
Fixes #626 #625 #628 #624 : Fixed Major Bugs in our website !!

### LINKED ISSUE #626: Students section is not appearing
### Expected results
Students should be visible

### Actual results
image

### PR DESCRIPTION
**Pull request by 0x48piraj**
# Fixes : #626 : Fixed Students & Mentors Section [BUG]
# Fixes : #625 : Fixed FOSSASIA Projects [BUG]
# Fixes : #628 : Fixed visibility of Blogs & Videos [BUG] 
# Fixes : #624 : Fixed Icons and logo [BUG] 

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- **_Preview - https://0x48piraj.github.io/gci17.fossasia.org/_** :+1: :100: 

image

image

image

image

image

image

---

### Before :- 

image

#### After my PR :- 

image

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@0x48piraj There should be carousel instead of button
image
One image is broken
image
Thanks for all the fix. Good Work ✨

**Comment by 0x48piraj** [comment]
@vaibhavsingh97 Just refresh and clear your cookies.
It's a fully responsive gallery 

image

**Comment by vaibhavsingh97** [comment]
@0x48piraj PLease fix this
image
image

**Review by ParthS007 — COMMENTED** [review]
@0x48piraj  Good work , Fix the changes suggested by @vaibhavsingh97  else looks good 👍

**Comment by 0x48piraj** [comment]
Again, It's just because of the network, the website is very laggy, I'm working on that.
But this PR is not related, as it will work well when given enough network.

Ping @vaibhavsingh97 @ParthS007

**Comment by vaibhavsingh97** [comment]
@0x48piraj ok, seems like newtwork issue. But in Blog there is one missing thumbnail, pease fix it. Also, in carousel, buttons are missing
reference image:
image

**Comment by 0x48piraj** [comment]
In flickr Gallery all buttons are perfectly working. :blush: 
But yeah! The above image is perfectly right, It do lacks the arrow-icon.
I'll try to fix that.

@vaibhavsingh97 
Yes! I have opened a dedicated issue for the Blog Thumbnail as only the owner can solve that issue.

**Comment by 0x48piraj** [comment]
@ParthS007 @vaibhavsingh97 
I think, it's taking time, and it can be solved by another GCI Student. :+1: 
We can just merge this PR to bring back our previous website.
What do you think ?

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
OK @0x48piraj , alright cool, Merging this PR. create a separate PR for logo correction.

**Pull request merged**
