### PR TITLE
added Srihari Unnikrishnan in students.yml

### PR DESCRIPTION
**Pull request by pythongiant**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please make sure that the dimensions of the image is 240 x 240 pixels and also resolve conflicts

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Review by anshumanv — CHANGES_REQUESTED** [review]
Conflicts and please use proper sized image

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by ShivamRai2003** [comment]
please resolve your conflicts

**Review by ShivamRai2003 — CHANGES_REQUESTED** [review]
please add your information above

**Comment by pythongiant** [comment]
Done!

**Review by gabru-md — CHANGES_REQUESTED** [review]
Resize your image.
Rest okay

**Review by ShivamRai2003 — APPROVED** [review]
GOOD WORK

**Review by gabru-md — APPROVED** [review]
LGTM

**Review by ParthS007 — APPROVED** [review]
LGTM ! Can you please provide a preview link so that I can merge.Thanks

**Comment by pythongiant** [comment]
yeah so can someone push my repo

**Comment by ShivamRai2003** [comment]
provide your pr first to merge it

**Comment by gabru-md** [comment]
2 Approvals. Merging

**Pull request merged**
