### PR TITLE
Reverted hover color on drop-down to gray

### LINKED ISSUE #971: Drop-down has red overlay on drop-down: It should not
The red background on the drop down menu does not make sense here as we are not using the standard FOSSASIA style here.

Please revert this color change. Research the previous gray color and revert to it.

screenshot from 2018-02-09 11-46-34

### PR DESCRIPTION
**Pull request by ankurg22**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showing after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
- Currently, the hover color was red. Since we are not following
FOSSASIA's standard so red didn't make any sense. So reverted it to
gray.
- https://ankurg22.github.io/gci17.fossasia.org/
- Fixes #971

### CODE REVIEW

**Review by yashLadha — APPROVED** [review]
LGTM 👍

**Comment by yashLadha** [comment]
Ping @mariobehling

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@ankurg22  You have to change the `background-color` from `red` to gray.

**Comment by ankurg22** [comment]
@ParthS007 Made the changes please review.

**Review by rupav — APPROVED** [review]
LGTM

**Comment by ankurg22** [comment]
@yashLadha @rupav @ParthS007 Why isn't the change of this PR reflecting back on the website? It is working fine on my machine and on my forked repo gh-pages site.

**Comment by rupav** [comment]
@ankurg22 it takes sometime time to build gh-pages. You can expect changes within few hours in original website.

**Pull request merged**
