### PR TITLE
Improve README.md , Change the position of thanks for contributing box, Add a new mentor. 

### PR DESCRIPTION
**Pull request by supunTE**
#412 Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added how to "add a video to a videos section" in README.md
as issue - https://github.com/fossasia/gci17.fossasia.org/issues/363 point 5
- Add thanks for contributors box after contributors section. 
as issue - https://github.com/fossasia/gci17.fossasia.org/issues/363 point 3
- Add a new mentor. 

https://stedirisuriya.github.io/gci17.fossasia.org/

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
Those 3 commits are 3 points so they can't squash.

**Review by nzec — APPROVED** [review]
@STEdirisuriya They can be squashed. Why can't they be?

Other than that, Awesome work!

**Comment by supunTE** [comment]
squashing pls wait

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash commits @STEdirisuriya

**Review by sayak119 — APPROVED** [review]

**Review by gabru-md — CHANGES_REQUESTED** [review]
The changes look good to me.
But kindly add a suitable name for the PR.

**Review by gabru-md — APPROVED** [review]

**Review by sansyrox — APPROVED** [review]
LGTM

**Review by saurabhjn76 — APPROVED** [review]

**Review by the-codingninja — APPROVED** [review]

**Pull request merged**
