### PR TITLE
index.html: Adds students projects section

### LINKED ISSUE #87: Add students project's section
A student project section s outlined by https://codein.withgoogle.com/tasks/5272972275220480/?sp-organization=6237166344601600&sp-is_beginner=False; so that students can use that to showcase the projects used done by them during gci for fossasia.

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds student projects section based on jekyll and javascript which
displays a student project when there is a project and if there are no
projects it displays that there are no projects.

Fixes #87 

Screenshots:
screenshot from 2017-12-03 17-49-18
screenshot from 2017-12-03 17-50-14

Live link to test: https://abishekvashok.github.io/gci17.fossasia.org/

### CODE REVIEW

**Comment by ParthS007** [comment]
@abishekvashok  . Can you please resolve conflicts

**Comment by abishekvashok** [comment]
@ParthS007 done

**Review by NaviRocker — APPROVED** [review]
Good Job

**Comment by abishekvashok** [comment]
@ParthS007 facing a hard time trying to squash merge commits, unable to do so, please use the squash and merge option.

**Comment by ParthS007** [comment]
Good work @abishekvashok . Please go through [https://gist.github.com/patik/b8a9dc5cd356f9f6f980](https://gist.github.com/patik/b8a9dc5cd356f9f6f980)

**Review by ParthS007 — APPROVED** [review]
LGTM !

**Comment by abishekvashok** [comment]
@ParthS007 it's giving me conflicts, to resolve which I have to commit again.
Can you pls use the squash and merge button theres a drop down in the merge button?

**Comment by ParthS007** [comment]
@abishekvashok No problem we will squash and merge.Link is just for informational purpose and Its the easiest way to squash commits

**Comment by abishekvashok** [comment]
@ParthS007 I know to squash commits but I have'nt figured out how to squash a merge conflict resolution commit along with your commit.

**Comment by abishekvashok** [comment]
> No problem we will squash and merge

@ParthS007 any more changes, I should make?

**Comment by ParthS007** [comment]
You have to pull the changes and then again push it

**Comment by abishekvashok** [comment]
@ParthS007 seems like I lost some of my files. Closing htis PR and opening a new one again.

**Comment by abishekvashok** [comment]
The diff is missing some files that I used , strange, think my experiments went wrong.

**Comment by abishekvashok** [comment]
Please see #97

**Pull request closed without merging**
