### PR TITLE
index.html: Adds thanks you for contributing

### LINKED ISSUE #61: Add thanks for contributing section
Add thanks for contributing section to the website with multiple language support.

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds thank you for contributing section which displays "Thank you for
contributing" section to the website and refresh it with the languages
specified (currently only english) every 6s.

Fixes #61 

Link to test: https://abishekvashok.github.io/gci17.fossasia.org/

link to my task: https://codein.withgoogle.com/dashboard/task-instances/5816210207801344/

### CODE REVIEW

**Comment by gabru-md** [comment]
@abishekvashok  I propose a better and understandable approach to the same work as a mentor.
Please have a look at it. And ask if you do not understand it.

```javascript
var i = 0;
for(var j = 0; j < 20; j++){  // change it with setInterval
    console.log(thankList[i]);
    if(i == thankList.length - 1){
        thankList.reverse();
        i = 0;
    }
    else{
        i++;
    }
}
```

Cheers!

**Comment by abishekvashok** [comment]
@gabru-md thanks for teaching me that, will implement your solution :)

**Comment by abishekvashok** [comment]
@gabru-md done, pls check now :)

**Review by gabru-md — APPROVED** [review]

**Comment by gabru-md** [comment]
@SaptakS please see  and merge.

**Review by NaviRocker — APPROVED** [review]
Looks Good To Me

**Comment by abishekvashok** [comment]
@jigyasa-grover you closed this PR, along with the issue. Fixes should reference issues should'nt it? I think github sees issues and PRs alike. :( Or, did I do something wrong? Anyway,since, the thanks for contributions section was added, opening a new PR

**Pull request closed without merging**
