### PR TITLE
Fixes #658 : Fixed buttons: added one more

### LINKED ISSUE #658: Problems with navbar
### Problems

1. The FOSSASIA navbar button should take to main website
2. There should be a "Home" link on the bar for reaching the landing
### Steps to reproduce the issue
Link main button to the main website and add another home link
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x ] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showing after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request
Have linked main Fossasia website to the main website. Added Welcome button to navbar to link the landing.
[Deploy Link](https://saarthakchats.github.io/I-m-the-one/)
- Fixes #658

### CODE REVIEW

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Not clear. Send some related screenshots :blush:

**Comment by saarthakchats** [comment]
screenshot 14

**Comment by saarthakchats** [comment]
screenshot 14 _li

**Comment by saarthakchats** [comment]
That button was connected to the landing page of this website itself when it should have been linked to Fossasia main website

**Comment by saarthakchats** [comment]
screenshot 15 _li
Now that button links to the main website and "Welcome" button links to the landing page of gci17.fossasia.org website.

**Comment by saarthakchats** [comment]
@0x48piraj

**Comment by 0x48piraj** [comment]
Oh! Cool !

**Review by 0x48piraj — APPROVED** [review]
LGTM! :tada:

**Review by codedsun — APPROVED** [review]

**Comment by saarthakchats** [comment]
@codedsun 
Can we merge. ;)

**Pull request merged**
