### PR TITLE
Update stylesheet.css

### PR DESCRIPTION
**Pull request by Ploypiti**
Desperate effort to fix button hover

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Fix #285 
- Live preview https://ploypiti.github.io/gci.fossasia.org/

### CODE REVIEW

**Review by nzec — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]
LGTM ! Good Work @Ploypiti

**Review by vaibhavsingh97 — COMMENTED** [review]
@Ploypiti Nice to see your dedication to solve an issue. 👏 👏 
Can you please tell me why you named this CSS file   as `stylesheet`

**Comment by Ploypiti** [comment]
@vaibhavsingh97 I don't know :rofl: when I first learned CSS they said `stylesheet.css` is a standard file name so mostly file I write are `stylesheet.css` or `style.css`

**Comment by vaibhavsingh97** [comment]
@Ploypiti Ohh! `style.css` is the general file name convention that is followed. Also, custom.css is also present and I don't think creating to many css files will solve the purpose. Please read more about it here https://css-tricks.com/one-two-three/

**Comment by Ploypiti** [comment]
...Yes? But I just edited the original file not create a new one 😊 Thanks for the link also.

**Comment by vaibhavsingh97** [comment]
@Ploypiti I am merging this as this solves an issue. So do read the article I shared and please open issues and fix it. It's better we follow Best Practices 😉

**Comment by Ploypiti** [comment]
@vaibhavsingh97 You wants me to merge all CSS files?

**Pull request merged**
