### PR TITLE
Added my profile to the GCI FOSSASIA Site Student Section

### PR DESCRIPTION
**Pull request by daniellawson9999**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added my profile to the GCI FOSSASIA Site Student Section which includes a photo, modifications to students.yml.

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by daniellawson9999** [comment]
conflicts should be resolved

**Comment by nikit19** [comment]
@daniellawson9999 still there.

**Comment by daniellawson9999** [comment]
did it work?

**Review by nikit19 — APPROVED** [review]

**Comment by nikit19** [comment]
Yeah ! LGTM :+1:

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please Provide a Preview link.

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by anshumanv** [comment]
Please try to provide a test link as requested by @ParthS007.
Use - https://pages.github.com

**Pull request merged**
