### PR TITLE
update mentors.yml

### PR DESCRIPTION
**Pull request by ShivamRai2003**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by ShivamRai2003** [comment]
MENTORS PLEASE APPROVE IT

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please squash your commits.

**Comment by ShivamRai2003** [comment]
HOW to do it plzz tell

**Comment by realslimshanky** [comment]
Follow [this](https://davidwalsh.name/squash-commits-git) guide and ask your queries here in comments.

**Comment by ShivamRai2003** [comment]
its not working please approve it

**Comment by ShivamRai2003** [comment]
hey can i closed it and make a new

**Comment by realslimshanky** [comment]
Your PR is working properly but doesn't follow guidelines. Please squash all your commits into one by using  [this](https://davidwalsh.name/squash-commits-git) guide.

**Comment by ShivamRai2003** [comment]
i have the windows 8.1 and guide does not work please give to some to me
and help me request you

**Comment by realslimshanky** [comment]
The above guide is generic and works for all the operating system. Take your time and read through it.

**Comment by ShivamRai2003** [comment]
but can't you help me i have tried many times

**Comment by ShivamRai2003** [comment]
in terminal its notworking can it done on github desktop

**Comment by realslimshanky** [comment]
`git` command is not working from the terminal (or in your case command prompt) or some other command?

**Comment by ShivamRai2003** [comment]
YES

**Comment by rupav** [comment]
@realslimshanky  it will not work from cmd , @ShivamRai2003 you need to install git bash to squash.

**Comment by ShivamRai2003** [comment]
i have

**Comment by realslimshanky** [comment]
@rupav depends on whether or not one has `PATH` set for git.

**Comment by rupav** [comment]
That's great then. So have you setup this repository locally too using `git clone <url> ? 
If yes then, you can try out those suggested commands on git bash (using git bash move to the directory where the local setup is ).

**Comment by ShivamRai2003** [comment]
yes

**Comment by rupav** [comment]
@realslimshanky that makes sense. Never tried using cmd. I am a Windows user too. I will try that 😀

**Comment by ShivamRai2003** [comment]
hey i have cloned now can you tell me in the steps

**Comment by realslimshanky** [comment]
Change your branch to gh-pages using `git checkout gh-pages`.
Then soft reset to the first commit you have made by `git reset --soft reset HEAD~3`, this will keep all your changed to the project directory and more head to your first commit.
Now add all the changes to staging area just in case `git add *`.
Finally, do a `git commit -a --amend`, this will amend the first commit i.e. HEAD and add all other changes to it. Now, you have to do `git push --force origin gh-pages` (origin should be the remote of the repository in your profile which is a fork of this repository) to send your changes to github and this PR will be updated automatically.
Please ask if you have any doubt in this process.

**Comment by rupav** [comment]
Yeah sure.

-  move to the directory where it's set up locally using git bash. `cd ` commands will help you to move to required folder.

- now` git log `  to see how many recent commits you made. (In this case 4 ).
- then type `git rebase -i head~4` ( check that link , this command may be slightly different. "i" is for interactive )

-  now replace pick with s except the topmost. Save and close the ediTor.

- `git push origin ` to get the squashed commits reflected on your repo.

**Comment by ShivamRai2003** [comment]
~ how to enter this symblo with keyboard

**Comment by ShivamRai2003** [comment]
and HEAD~3 what is this

**Comment by realslimshanky** [comment]
Use the key just above tab with shift key. HEAD~3 is the commit 3 back from current HEAD of your active branch.

**Comment by ShivamRai2003** [comment]
thanks

**Comment by ShivamRai2003** [comment]
as you can see in the scrren shot the command are not working so what
should i do now.

**Comment by rupav** [comment]
We can't see any screen shot maybe because you are attaching from mail directly. Use GitHub

**Comment by ShivamRai2003** [comment]
hey i think i should delete my repsoitory and create a new one and then send a new pull request what do you think

**Comment by realslimshanky** [comment]
@ShivamRai2003 don't delete your repository. Try to fix the error in existing one. Please share the error you are getting.

**Comment by ShivamRai2003** [comment]
just tell me one by one whole steps to do if you have time please

**Comment by realslimshanky** [comment]
@ShivamRai2003 please ping on the fossasia gitter chat.

**Pull request closed without merging**
