### PR TITLE
try2 - add link to blog

### PR DESCRIPTION
**Pull request by gowriharish100**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by gowriharish100** [comment]
we need to add only the pic and the 4 line modification. the other 2 can be ignored. pls help asap.

**Review by isuruAb — COMMENTED** [review]
there are lot of modifications and one extra image. please check again

**Comment by gowriharish100** [comment]
how to remove the unwanted files from the changeset. pls help.

**Comment by gowriharish100** [comment]
i think i removed the unwanted stuff. is it ok now ? can the pull go thru ?

**Review by nikit19 — APPROVED** [review]

**Comment by gowriharish100** [comment]
thanks for the approval. when will the change reflect in the webpage ?

**Review by isuruAb — APPROVED** [review]
👍

**Review by isuruAb — APPROVED** [review]
Please squash your commits.  rest is okay 👍

**Comment by nikit19** [comment]
@isuruAb I guess for a first time contributor it is okay if the commits aren't squashed

**Pull request merged**
