### PR TITLE
Fixes #323: Replaces Google Maps with Open Street Maps

### LINKED ISSUE #323: Use OpenStreetMaps instead of Google Maps
### Expected results
We should use open source technologies like open street maps.

### Actual results
We are using closed source google maps which has a request limit.

### Steps to reproduce the issue
See the community connect section in the website

## Would you like to work on this
Sure, why not.

### PR DESCRIPTION
**Pull request by abishekvashok**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request
Replaces Google Maps which is closed source with Open Street Maps. Fixes #323 
Preview link: https://abishekvashok.github.io/gci17.fossasia.org/
Screenshot:
screenshot from 2017-12-16 18-05-41

Fixes #323

### CODE REVIEW

**Comment by nzec** [comment]
Oh! Wow! Great work! However, OpenStreetMaps is much more slower than Google Maps.
So, will it be possible to locally host it?

**Comment by abishekvashok** [comment]
> So, will it be possible to locally host it?

As an open source community e should encourage open source projects and not closed source projects The data is fetched from the server as FOSSASIA has large a no: of participants and mentors from all around the world. Hosting that much data locally would be a big vain.

**Review by isuruAb — COMMENTED** [review]
Hi @abishekvashok , Please mention the corresponding issue number in the pull request body and title.

**Comment by abishekvashok** [comment]
@isuruAb sorry for that, pls review now.

**Review by nzec — APPROVED** [review]
LGTM!

**Review by akshatnitd — CHANGES_REQUESTED** [review]
The PR looks great! Can you add separate markers for students and mentors ?

**Comment by abishekvashok** [comment]
@akshatnitd sure. We can use different colours for markers maybe, what do you say?

**Comment by akshatnitd** [comment]
@abishekvashok Yes, that is a good solution, but the idea of student and mentor will be unclear, until we make a map legend separately. Using 'S' and 'M' is more easier to decipher. What do you feel ?

**Comment by abishekvashok** [comment]
Sure. On it.

**Comment by abishekvashok** [comment]
@akshatnitd @isuruAb done, here's a screenshot, live preview link is in the pr description
screenshot from 2017-12-16 18-05-41

**Review by akshatnitd — APPROVED** [review]
LGTM  :+1:

**Review by anshumanv — APPROVED** [review]
:+1:

**Comment by abishekvashok** [comment]
Can we go for a merge then @fossasia/website-admins

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
Good Work @abishekvashok . Keep Contributing 👍

**Comment by abishekvashok** [comment]
Thank you

**Comment by abishekvashok** [comment]
Link to my task: https://codein.withgoogle.com/dashboard/task-instances/6696385464238080/

**Pull request merged**
