### PR TITLE
Fixes #484 :Fixed an out of size image

### LINKED ISSUE #483: An image in the students section is out of size
### Expected results
all images aligned and in the same size
### Actual results
One image smaller than all others in the students' section
### Steps to reproduce the issue
Resizing the image
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #483

###Expected results
all images aligned and in the same size

###Actual results
One image smaller than all others in the students' section

###Steps to reproduce the issue
Resizing the image

Details:- An image in the students' section was out of size. I have resized it!

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
LGTM but follow fossasia's best parctices

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@saarthakchats  Since you have made many PRs, Please follow best practices and fill the details in PR template.

**Comment by saarthakchats** [comment]
@ParthS007 Is this fine?

**Comment by saarthakchats** [comment]
@harshit98

**Comment by harshit98** [comment]
@saarthakchats Kindly provide details of fix in the PR details section.

**Comment by saarthakchats** [comment]
@harshit98 @ParthS007

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
