### PR TITLE
Update Student Section

### PR DESCRIPTION
**Pull request by Retardvoldy**

### CODE REVIEW

**Comment by abishekvashok** [comment]
@Retardvoldy pls don't merge your own PR? Btw. how did you get write access :)

**Comment by Retardvoldy** [comment]
oh oops I did not mean to do that

**Comment by abishekvashok** [comment]
@Retardvoldy how dod you get write access? It's okay since, it was a first time issue.

**Comment by Retardvoldy** [comment]
I work with FA before. Nonetheless I don't mean to edit anything

**Comment by abishekvashok** [comment]
@Retardvoldy I see that you are in the team @fossasia/fossasia-gci but are'nt you a student?

**Comment by Retardvoldy** [comment]
It says it can be merged automatically just now because it does not conflict?

**Comment by abishekvashok** [comment]
@Retardvoldy we have put together a blog post for some general info: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by ParthS007** [comment]
@Retardvoldy Please refrain to directly merge PR, it may have conflicts and errors. Please follow best practices.

**Pull request merged**
