### PR TITLE
Added a mentor

### PR DESCRIPTION
**Pull request by supunTE**
Yash Ladha

### CODE REVIEW

**Comment by supunTE** [comment]
https://stedirisuriya.github.io/gci17.fossasia.org/mentors

**Comment by anshumanv** [comment]
Why did you close #270? Please refrain from closing PR without any solid reason, try to incorporate changes in the PR itself.

**Comment by supunTE** [comment]
OK next time

**Review by ParthS007 — APPROVED** [review]
LGTM !

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
