### PR TITLE
Added mentor and Geolocation(@gabru-md

### PR DESCRIPTION
**Pull request by saarthakchats**

### CODE REVIEW

**Comment by saarthakchats** [comment]
@abishekvashok 
@gabru-md 
This is the one

**Comment by gabru-md** [comment]
LAT : 28.682062
LONG : 77.321622
please :sweat_smile:

**Comment by saarthakchats** [comment]
@gabru-md 
Done the changes

**Review by gabru-md — CHANGES_REQUESTED** [review]
github parameter requires only the github username.
Please make the changes and add `facebook : gabrumd` as well. Thanks

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by saarthakchats** [comment]
@gabru-md @anshumanv 
Done the fixes

**Review by gabru-md — APPROVED** [review]
Thanks!

**Comment by saarthakchats** [comment]
@gabru-md 
Can you merge and also approve my task. No pressure :)

**Pull request merged**
