### PR TITLE
Developed Site #Renewed

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixed issue of a lot of links ending up nowhere and getting back to the site again. Also added relevant content to a fitness section instead of simple Lorem Ipsum. Added more useful links.

### CODE REVIEW

**Comment by saarthakchats** [comment]
@ms10398 Please merge this #203 one, not #202.

**Comment by harshit98** [comment]
Provide screenshots of the fix. @saarthakchats

**Comment by saarthakchats** [comment]
llll
screenshot 61
screenshot 59
screenshot 60

**Comment by saarthakchats** [comment]
These have additional links to them which were useless earlier.

**Comment by saarthakchats** [comment]
screenshot 63
screenshot 64
Also added links here

**Review by isuruAb — COMMENTED** [review]
@saarthakchats  please resolve conflicts 👍  
follow this tutorial to squash your commits
https://www.youtube.com/watch?v=vp7-NeURmFg&t=39s

**Comment by ParthS007** [comment]
@saarthakchats please resolve conflicts and your PR is ready to merge !

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@saarthakchats please resolve conflicts and your PR is ready to merge! 👍

**Pull request closed without merging**
