### PR TITLE
Added Project: Labyrinth !!

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by Beta-King** [comment]
https://beta-king.github.io/goallesdcxzgci17.fossasia.org/# --> Preview Link :D

**Comment by yashk0thari** [comment]
@abishekvashok @nikit19 @harshit98 @samyakbvs please review and merge this PR :D

**Comment by arjunpandey2003** [comment]
@Beta-King I think you should add it to the right side it will look better and maintain the flow

**Comment by yashk0thari** [comment]
https://beta-king.github.io/kayakayakagci17.fossasia.org/# --> Preview Link and commits are squashed :D

**Comment by yashk0thari** [comment]
@arjunpandey2003 made the changes you requested, can you approve now ??

**Review by rupav — COMMENTED** [review]
I think its not needed. Videos are already present for the same project. Also above two projects on SUSI and Open-Event mention technology used. If approved by other maintainers, you should add those too.

**Comment by yashk0thari** [comment]
ohk, then closing this :D

**Pull request closed without merging**
