### PR TITLE
GCI student entry

### PR DESCRIPTION
**Pull request by Chiral13**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — APPROVED** [review]
LGTM but from next time  try making changes in the same pull request. :+1:

**Comment by nikit19** [comment]
And can you change the pull request title to something more meaningful ?

**Comment by abishekvashok** [comment]
@INFERNOMK1 pls close the other PRs as this looks good.

**Comment by YashKumarVerma** [comment]
Pr title and description missing. 😶. Please add one.

**Comment by Chiral13** [comment]
thanks for help guys 👍

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@INFERNOMK1 Please provide a preview link

**Comment by INFERNOMK1** [comment]
Preview link: https://github.com/INFERNOMK1/gci17.fossasia.org.git

**Comment by INFERNOMK1** [comment]
I am not sure about preview link

**Comment by INFERNOMK1** [comment]
can this work?
https://github.com/INFERNOMK1/gci17.fossasia.org.git

**Comment by YashKumarVerma** [comment]
@INFERNOMK1 sorry but no.

this would work : https://infernomk1.github.io/gci17.fossasia.org/

**Comment by Chiral13** [comment]
here it is -
https://infernomk1.github.io/INFERNOMK1-gci17.fossasia.org/

**Comment by Chiral13** [comment]
thanks ;-)

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
