### PR TITLE
Added installation files in Sinhala language and fixed small issues in installations files - english

### PR DESCRIPTION
**Pull request by supunTE**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

See here all changes - https://github.com/STEdirisuriya/gci17.fossasia.org
Added installation files in Sinhala language
    as point of this issue https://github.com/fossasia/gci17.fossasia.org/issues/445 
    and  also part of this https://github.com/fossasia/gci17.fossasia.org/issues/83

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
please squash the changed to one.

**Review by YashKumarVerma — APPROVED** [review]
translation looks fine ✨

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
squash commits to one please

**Review by daminisatya — APPROVED** [review]

**Comment by daminisatya** [comment]
Please squash into one commit

**Review by nzec — APPROVED** [review]
😄

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
@STEdirisuriya Please resolve conflicts and your PR is ready to merge 👍

**Review by amryarios — APPROVED** [review]
:+1:

**Review by NaviRocker — APPROVED** [review]
LGTM

**Pull request merged**
