### PR TITLE
Revert "Added the link of my blog (#534)"

### PR DESCRIPTION
**Pull request by kaushikichhabra**
This reverts commit 6d9a370b161aff15e91d99e0e7dd4ead58746bd3.

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

THIS IS THE LINK OF MY BLOG~
https://fossasiasblog.wordpress.com/2017/12/28/foss-asia-and-me/
PLS TELL IF ANY CHANGES ARE TO BE DONE 
THANKS 
YOUR SCINCERELY 
KAUSHIKI

### CODE REVIEW

**Review by gabru-md — CHANGES_REQUESTED** [review]
There are conflicts in your PR.

**Comment by kaushikichhabra** [comment]
Thanks for writing  back...what changes should I make?

**Review by NaviRocker — CHANGES_REQUESTED** [review]
Resolve the Conflicts @kaushikichhabra

**Review by isuruAb — CHANGES_REQUESTED** [review]
please resolve conflicts

**Comment by kaushikichhabra** [comment]
How should I resolve conflicts?

**Comment by kaushikichhabra** [comment]
I'm not able to create a pull request...how should I create it...please
help...

**Comment by abishekvashok** [comment]
@kaushikichhabra please see this article: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by STARGAZER173** [comment]
I have forgotten to link my blog to FOSSASIA GCI website. Please help. Link of my blog : https://catechnical406767641.wordpress.com/2017/12/28/fossasia-blog-gci-2017/

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
You deleted the image, upload a new one.

**Comment by harshit98** [comment]
I'm closing the PR @kaushikichhabra. Kindly make a new PR for it instead of reverting it back.

**Comment by kaushikichhabra** [comment]
Ya...I am making a new one...but i have submitted work for review...please
grant permission to it..

Closed #586 <https://github.com/fossasia/gci17.fossasia.org/pull/586>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/gci17.fossasia.org/pull/586#event-1405331066>,
or mute the thread

**Pull request closed without merging**
