### PR TITLE
Fixes #538: Adds vk social media link

### LINKED ISSUE #538: Add vk link of fossasia
### Expected results

vk link should be present

### Actual results

it's missing

### Steps to reproduce the issue

Go to the website

## Would you like to work on this

Yes, why not? Working on it.

### PR DESCRIPTION
**Pull request by abishekvashok**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

Adds link of fossasia in the social media vk.
Fixes #538 
Link to live preview: https://abishekvashok.github.io/gci17.fossasia.org/

# Screenshots
screenshot_20171227_161755
screenshot_20171227_161802
screenshot_20171227_161847
screenshot_20171227_161857

### CODE REVIEW

**Review by nzec — APPROVED** [review]
Simple change! Looks k.

**Review by akshatnitd — APPROVED** [review]
LGTM :)

**Review by vaibhavsingh97 — APPROVED** [review]

**Comment by vaibhavsingh97** [comment]
@abishekvashok Use `Fixes #<issue-number> : <message>`. Please follow best practices. Thanks

**Review by anshumanv — APPROVED** [review]

**Review by dilpreetsio — APPROVED** [review]

**Review by the-codingninja — APPROVED** [review]

**Comment by abishekvashok** [comment]
@vaibhavsingh97 do you want me to do that in the commit? Basically, that's against basic practises at git. However I may be obliged to do so, if you oblige me.

**Comment by vaibhavsingh97** [comment]
@abishekvashok Please take care in future. 😄

**Pull request merged**
