### PR TITLE
Added My Student Profile

### PR DESCRIPTION
**Pull request by niranjannitesh**

### CODE REVIEW

**Comment by poush** [comment]
Provide a link to your gh-pages to check the updated changes.

**Comment by niranjannitesh** [comment]
Here I go [http://niteshkumarniranjan.me/gci17.fossasia.org/](http://niteshkumarniranjan.me/gci17.fossasia.org/)

**Comment by niteshkumarniranjan** [comment]
Here I go
[http://niteshkumarniranjan.me/gci17.fossasia.org/](http://niteshkumarniranjan.me/gci17.fossasia.org/)

**Comment by niteshkumarniranjan** [comment]
Here I go
[http://niteshkumarniranjan.me/gci17.fossasia.org/](http://niteshkumarniranjan.me/gci17.fossasia.org/)

**Comment by niranjannitesh** [comment]
@poush Anything Else.

**Review by poush — APPROVED** [review]
Good work.

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
