### PR TITLE
blogs.yml

### PR DESCRIPTION
**Pull request by kaushikichhabra**
url: https://fossasiasblog.wordpress.com
title: FOSSASIA AND ME 
img: IMG_567.PNG
author_name: Kaushiki Chhabra

### CODE REVIEW

**Comment by ShivamRai2003** [comment]
you are correct just correct your conflicting files

**Review by isuruAb — COMMENTED** [review]
please remove unwanted commits and squash your commits

**Review by nikit19 — COMMENTED** [review]
You are sending the pull request into the wrong branch.
Please send a new pull request to the gh-pages branch

**Comment by nikit19** [comment]
Closing this one

**Pull request closed without merging**
