### PR TITLE
Added my image and credentials

### PR DESCRIPTION
**Pull request by kushpandey1811**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [X ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [X ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
https://kushpandey1811.github.io/gci17.fossasia234.org/.
- [ ] Squashed the commits.

### CODE REVIEW

**Review by rupav — CHANGES_REQUESTED** [review]
Just change the size of image to 240x240 pixels. Its now 239x234 pixels.

**Review by saarthakchats — APPROVED** [review]
Squash the commits! rest looks good

**Comment by kushpandey1811** [comment]
@rupav done it will be difficult to squash commits as i live in a hostel with minimal net and will be impossible to download github desktop, please squash and merge, in the mean time i will try to get it from somewhere. Changes done online. Hope you realize thanks :)

**Comment by kushpandey1811** [comment]
thanks @rupav for understanding my situation

**Pull request merged**
