### PR TITLE
GCI 2017 – THE BEST OPPORTUNITY FOR AMATEUR CODERS.

### PR DESCRIPTION
**Pull request by BatTech17**
[etrandomblogspot.wordpress.com](url)

### CODE REVIEW

**Review by nikit19 — COMMENTED** [review]
Please send a new pull request to the gh-pages branch
Currently you are sending it to the revert-534-gh-pages branch

**Review by anshumanv — COMMENTED** [review]
There are way too many issues with this PR, please send a new one.

**Comment by BatTech17** [comment]
Not able to send a pull request to gh-pages. Please help.

**Comment by nikit19** [comment]
https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/README.md

https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/CONTRIBUTING.md
These two links might help,send a new pull request following these links and feel free to ask if you get stuck anywhere

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@BatTech17  Closing this PR due to many conflicts. Please read `README.MD` on how to add a blog and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

**Pull request closed without merging**
