### PR TITLE
Extract student and mentor sections to own page

### LINKED ISSUE #67: Performance issues?
The overall layout for the GCI pages over the past few years have been quite similar: many different sections (a map, the students/mentors/contributors gallery, projects, and so on) all on one large homepage.

While a single page makes sense at smaller scales, some issues might crop up as more things are added to the page:
* greater risk that a merge conflict might break the page
* (more importantly) **it takes longer to load the page** and its large number of resources.

For instance, gci16.fossasia.org pulls in about 600 requests, or **24MB** in resources, including scripts and images.

That took almost **40s** to download on a home broadband connection; it would take even longer to download on a mobile connection.

Additionally, not all of the scripts / images downloaded might be noticed by a user; not everyone might look at the Contributors section, for instance.

Suggest moving each section of the page into individual pages; the front page could have a small preview of each section, which links to the respective page.

### PR DESCRIPTION
**Pull request by kaine119**
(closes #67)
* Headers and footers have been moved to `_includes`
* Mentors and students section moved to their own page (they're still in `index.html`, but can be shortened)
* README.md updated with new page instructions

### CODE REVIEW

**Review by NaviRocker — CHANGES_REQUESTED** [review]
Please Squash all your Commits

**Comment by kaine119** [comment]
Done.

I'm gonna rebase it on top of 7edbc6e

**Comment by kaine119** [comment]
> I'm gonna rebase it on top of 7edbc6e

Done.
@2coolife, could you check if I merged your changes correctly? Thanks.

**Review by poush — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Comment by kaine119** [comment]
Done.

**Comment by jigyasa-grover** [comment]
@kaine119 There are some conflicts, please resolve. Thanks !

**Comment by kaine119** [comment]
Done

Given that this is quite a major change, how should this be merged so as to not affect other contributors?

**Comment by rishiraj824** [comment]
@kaine119 Please try backup your changes and then reset your current fork with the `gh-pages` branch, if you are facing difficulties. Then push that commit as -f to get your changes live.

**Comment by kaine119** [comment]
@rishiraj824 I've been rebasing on top of the `gh-pages` branch; issue is that because I'm making major changes to `index.html`, whenever someone else makes a change to `index.html`, no matter how small, it always conflicts.

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please provide a preview link

**Review by isuruAb — COMMENTED** [review]
@kaine119  please resolve conflicts

**Comment by imujjwal96** [comment]
@ms10398 here's the link https://kaine119.github.io/gci17.fossasia.org/
@kaine119 In the students page, you haven't omitted the `Meet` button, similar to how it is done in the mentors page

**Comment by codedsun** [comment]
@kaine119 Please resolve the conflicts!

**Comment by niranjannitesh** [comment]
@kaine119 Your repo has removed some mentors and blog.

**Comment by kaine119** [comment]
> In the students page, you haven't omitted the Meet button, similar to how it is done in the mentors page

Fixed

> Your repo has removed some mentors and blog.

That's because I haven't rebased on top of the current release; I'm having trouble working with all the new changes that have happened since b35a518. (also, I'm working on the `separate-pages` branch of my fork, not `gh-pages`.)

However, I'm not sure if I should rebase on top of 477f1b1; it breaks the Jekyll markup in the mentors section. Should I wait for that to be fixed, or should I just include the changes in that commit?

**Comment by niranjannitesh** [comment]
@kaine119 I have also seen the current branch is very much messed up.
I think It should be reverted back to some previous commits.

**Comment by kaine119** [comment]
> I think It should be reverted back to some previous commits.

I tried reverting 477f1b1; results at [the `revert-477f1b1` branch on my fork](https://github.com/kaine119/gci17.fossasia.org/tree/revert-477f1b1)

If anyone wants to test the branch, you'll need to clone my fork to your machine, checkout to the branch and run the Jekyll server with `bundle exec jekyll serve`

**Review by anshumanv — APPROVED** [review]
This should work.

**Comment by kaine119** [comment]
@anshumanv I think you missed the `limit:5` filter in the Jekyll `{% for %}` templates for the mentors and students section (i.e. [here](https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/index.html#L57) and [here](https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/index.html#L133))

**Comment by anshumanv** [comment]
That was intentional, I think it's better to have all students/mentors displayed.
@kaine119 :smile:

**Pull request merged**
