### PR TITLE
Added my blog to it.

### PR DESCRIPTION
**Pull request by pmsbir**
I have added my blog's link , image,  title and author name to it.

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please upload the image and after img : write the name of the image

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Instead of posting link to the image. You need to add an image to `img/blog/` folder and write the filename inplace of the link

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Lastly, instead of providing the image link, you need to add an image in the `img/blog/` folder and write the filename after `img: ` instead of the link

**Comment by pmsbir** [comment]
Ok, thankyou

**Comment by pmsbir** [comment]
Am I meant to upload the image file over there..

**Review by anshumanv — CHANGES_REQUESTED** [review]
Add image.

**Comment by harshit98** [comment]
Resolve conflicts and add your image. Make sure its dimensions are 240 x 240.

**Comment by harshit98** [comment]
Closing this PR. Similar to #573.

**Pull request closed without merging**
