### PR TITLE
Added a mentor

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Issue #36

### CODE REVIEW

**Review by akshatnitd — CHANGES_REQUESTED** [review]
@arjunpandey2003 Please provide a deployment link. Also, you have added the image in the incorrect folder. It should be in `img/mentors/`

**Comment by arjunpandey2003** [comment]
https://github.com/arjunpandey2003/gci17.fossasia.org

**Comment by arjunpandey2003** [comment]
Squashed

**Comment by arjunpandey2003** [comment]
@akshatnitd all necessary changes done

**Comment by harshit98** [comment]
Looks good to me! @arjunpandey2003. I'll merge this pull request, once travis ci passes.

**Comment by arjunpandey2003** [comment]
@harshit98 thanks!

**Review by nikit19 — APPROVED** [review]

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
