### PR TITLE
Linking my blog !

### PR DESCRIPTION
**Pull request by STARGAZER173**
screenshot_20180101-181732

Done!

### CODE REVIEW

**Comment by harshit98** [comment]
@Chirag1234567890 You're doing it wrong. Don't remove someone else name. 
- Image should be of 240 x 240 dimensions.
- Image name should be `name_of_student.jpg`. In your case, `chirag.jpg`

**Review by nikit19 — COMMENTED** [review]
You are almost there. Just don't delete somebody's code.
If you could give a better image name that would be better.
And please resolve conflicts

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Please delete the ` img/blog/IMG_20171011_150943-240x240.jpg` file. Please resolve conflicts as well.

**Comment by harshit98** [comment]
@Chirag1234567890 

- Resolve conflicts.
- Delete your old image. (Not `Chirag.jpg`)
- Don't delete someone else blog.

**Review by ParthS007 — COMMENTED** [review]
@Chirag1234567890  closing this PR, Please make a new PR after reading `README.md`

**Pull request closed without merging**
