### PR TITLE
Updated a Mentor's Social Media Links

### PR DESCRIPTION
**Pull request by NaviRocker**
Updated Yash Ladha's Social Links

### CODE REVIEW

**Review by yashLadha — APPROVED** [review]

**Comment by yashLadha** [comment]
Travis is failing can you see it @naveentherocker

**Comment by NaviRocker** [comment]
@yashLadha I just added 2 new lines, Why is Travis CI getting failed?

**Comment by dilpreetsio** [comment]
@naveentherocker Check #352

**Review by dilpreetsio — APPROVED** [review]

**Comment by NaviRocker** [comment]
Thank You For Pointing out @geekyd

**Comment by NaviRocker** [comment]
Well, If you merge this I can work on that Issue

**Pull request merged**
