### PR TITLE
upload image and link blog

### PR DESCRIPTION
**Pull request by MomtahinaKarim**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please delete the image which is not of  proper dimensions. Also write the code in blogs.yml to add your blog

**Review by dilpreetsio — COMMENTED** [review]
@MomtahinaKarim All images must be 240X240 px

**Review by codedsun — CHANGES_REQUESTED** [review]
Add only one image and add the link of the blog.

**Comment by MomtahinaKarim** [comment]
Yes, I deleted the image which is not of proper dimensions. Now, is it all
right??

**Review by akshatnitd — COMMENTED** [review]
@MomtahinaKarim You also need to update the PR, after making the changes

**Comment by MomtahinaKarim** [comment]
Yes, I have done it.

**Comment by abishekvashok** [comment]
@MomtahinaKarim a PR of yours for the same issue was merged.
Ref: https://github.com/fossasia/gci17.fossasia.org/commit/5135563679e12df2706ec8dc2b6eeddfe85d4406

Maintainers this is unwanted.

**Comment by nikit19** [comment]
I am closing this PR as you have already sent a PR that is merged.

**Comment by MomtahinaKarim** [comment]
Okay. What should I do now?

**Pull request closed without merging**
