### PR TITLE
Added my blog

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Interview with a teacher
https://arjunpandey2003.github.io/gci17.fossasiaplcun.org/.

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
guys my laptop is gone for repair this is done from another laptop, i dont have github desktop nor the ability to intsall pls merge like this sorry :(

**Review by akshatnitd — APPROVED** [review]

**Comment by arjunpandey2003** [comment]
thanks :)

**Review by nzec — APPROVED** [review]
Working on a setup that is not yours? That is truly heroic! 🤣 

I literally cannot do anything even if a single desktop icon is out of place. 😆

**Comment by arjunpandey2003** [comment]
merge?

**Comment by arjunpandey2003** [comment]
@duttaditya18 thanks my latptop's display is gone had to borrow a laptop :),

**Review by nikit19 — APPROVED** [review]

**Pull request merged**
