### PR TITLE
Removing repititions

### PR DESCRIPTION
**Pull request by kartikeya23**
* Removing the repeated section
* Improving code slightly

### CODE REVIEW

**Comment by kartikeya23** [comment]
Link to check output: https://kartikeya23.github.io/gci17.fossasia.org/

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Please give the issue link in the PR comment that you're fixing.

**Comment by kartikeya23** [comment]
Fixing issue #160

**Comment by niranjannitesh** [comment]
@anshumanv This PR has removed my Blog.

**Pull request merged**
