### PR TITLE
minified inview.js

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Minified Inview.js

### CODE REVIEW

**Review by NaviRocker — APPROVED** [review]

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Change the name to .min.js

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please do the suggested changes.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Add a EOF too :+1:

**Comment by harshit98** [comment]
I'm closing this pull request since the description of the fix is not clear here.

**Pull request closed without merging**
