### PR TITLE
Public code !! 

### PR DESCRIPTION
**Pull request by yashk0thari**
made necessary code changes to showcase slider image :D

Delete Public Code.jpg

Add files via upload

Alignment 1

Alignment 2

Alignment 3

Update index.html

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h]. 
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
added a new slider image :D 

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/warmhartaszgci17.fossasia.org/ --> Preview Link :D

**Comment by yashk0thari** [comment]
screen shot 2018-01-07 at 3 00 47 pm

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@Beta-King  Please use a good quality image.

**Comment by yashk0thari** [comment]
ohk :D -- changing that

**Comment by yashk0thari** [comment]
https://beta-king.github.io/ganzlebowlgci17.fossasia.org/ --> Preview Link :D

**Comment by yashk0thari** [comment]
@ParthS007, check now :D is it ohk ??

**Review by harshit98 — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]
Awesome

**Comment by yashk0thari** [comment]
Thanks :D Can we merge ??

**Comment by yashk0thari** [comment]
Thank you :D

**Pull request merged**
