### PR TITLE
Added Hitesh's pic correctly and Made necessary code changes

### PR DESCRIPTION
**Pull request by yashk0thari**
Made necessary code changes (Hitesh)

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`
#670 - I've fixed this issue !!

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/vsgci17.fossasia.org/ --> preview link !!

**Review by nikit19 — CHANGES_REQUESTED** [review]
If you are just renaming that picture please delete the original one ie intro.jpg

**Comment by yashk0thari** [comment]
the current picture isnt in the img/blog folder and so isnt showing in the website; nothing to delete

**Comment by yashk0thari** [comment]
but i'll recheck 👍

**Comment by yashk0thari** [comment]
Yup i've checked; no pic called intro.jpg or any other which has his pic

**Comment by yashk0thari** [comment]
the pic doesnt show in the website in any platforms (computer; mobile) even tried different browsers (chrome, safari)

**Comment by yashk0thari** [comment]
I've also tried different computers; his image isnt there is the website

**Comment by yashk0thari** [comment]
i'll send a pic, wait

**Comment by yashk0thari** [comment]
image

**Comment by yashk0thari** [comment]
Thats why i've opened this issue and PR; i found his pic from his blog so ik it is correct...

**Comment by yashk0thari** [comment]
screen shot 2017-12-31 at 2 34 19 pm

**Comment by yashk0thari** [comment]
by the changes i've made; you can see his pic in the website

**Comment by nikit19** [comment]
Just delete intro.jpg from here  https://github.com/fossasia/gci17.fossasia.org/tree/gh-pages/img/students
And you are done

**Comment by yashk0thari** [comment]
Done 👍

**Review by nikit19 — APPROVED** [review]

**Comment by yashk0thari** [comment]
can we merge now ?? :D

**Pull request merged**
