### PR TITLE
Added Youtube Videos and Updated FOSSASIA logo

### PR DESCRIPTION
**Pull request by chahatbansal**
screen shot 2017-11-30 at 8 54 09 pm

### CODE REVIEW

**Comment by chahatbansal** [comment]
@SaptakS I tried doing it the way you wanted!

**Comment by SaptakS** [comment]
@chahatbansal as mentioned in your earlier PRs, please provide a link where one can check. Helps in checking all the aspects of the final product. Thanks.

**Comment by chahatbansal** [comment]
Oh! 
Here you go : https://chahatbansal.github.io/gci17.fossasia.org/

**Comment by SaptakS** [comment]
@chahatbansal the link gives 404 error.

**Comment by chahatbansal** [comment]
@SaptakS can you please check the link again as I tried it on another browser, and it's working.

**Comment by niranjannitesh** [comment]
I haved checked in Chrome and It is working.

**Comment by niteshkumarniranjan** [comment]
@chahatbansal  You should update your fork with the latest repo.

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
