### PR TITLE
Added image

### PR DESCRIPTION
**Pull request by TechnoAman**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by 0x48piraj — COMMENTED** [review]
Please link the PR and address the reason.

**Review by isuruAb — COMMENTED** [review]
Hello @TechnoAman  your image should be 240 x240 sized

**Review by abishekvashok — COMMENTED** [review]
Add your details to students.yml in the _data directory. See the readme for an in-depth guide.

**Review by nikit19 — CHANGES_REQUESTED** [review]
You have resized the image but you also need to delete the older image. Read the readme to see in which folder you have to upload the image.

**Comment by ParthS007** [comment]
@TechnoAman  Closing this , Please add this image in #560

**Comment by TechnoAman** [comment]
I have added new resized image how to add it to the img/blog folder

**Pull request closed without merging**
