### PR TITLE
add my location and delete ig section

### PR DESCRIPTION
**Pull request by kol4k**

### CODE REVIEW

**Review by isuruAb — APPROVED** [review]
👍  please squash your 16 commits.
If you need to lear about squashing
follow this tutorial
https://www.youtube.com/watch?v=vp7-NeURmFg&t=35s

**Review by dilpreetsio — COMMENTED** [review]
@kol4k Please squash your commits.

**Comment by abishekvashok** [comment]
Can we do a squats and merge as he is not responding?

**Comment by isuruAb** [comment]
@kol4k  thank you 👍

**Pull request merged**
