### PR TITLE
Added my poster to the website

### PR DESCRIPTION
**Pull request by saarthakchats**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
hey why is your link my blogs link

**Comment by hpdang** [comment]
@arjunpandey2003 could you help @saarthakchats to complete his task? I am not sure what is he is trying to do. According to his GCI task, he is supposed to add a video on gci17 website.

**Review by nzec — CHANGES_REQUESTED** [review]
You don't have to add the poster to the website, you have to add it to the FOSSASIA Flickr album.

**Comment by saarthakchats** [comment]
Oh my god. I am so sorry. I completely forgot

**Pull request closed without merging**
