### PR TITLE
Create blog

### PR DESCRIPTION
**Pull request by kaushikichhabra**
url: fossasiasblog.wordpress.com
title:  FOSSASIA AND ME 
img: IMG_ 4670
author_name: Kaushiki Chhabra

### CODE REVIEW

**Comment by kaushikichhabra** [comment]
url: fossasiasblog.wordpress.com
title:  FOSSASIA AND ME 
img: IMG_ 4670
author_name: Kaushiki Chhabra

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please go through the readme.md on how to add your blog.
You have to write this code in blogs.yml in _data folder and upload the image in the img/blogs folder

**Comment by kaushikichhabra** [comment]
There is no option for me to create a code/ pull request

**Comment by nikit19** [comment]
Make these changes in your forked repository.
Commit those changes.
Then you will get an option to send a pull request just like you sent this pull request

**Comment by kaushikichhabra** [comment]
Which changes should  I make
I am sorry...but I am not able to understand this...

**Comment by nikit19** [comment]
The code that you wrote in this pull request was supposed to be in the blogs.yml file in the _data folder

**Comment by kaushikichhabra** [comment]
There is no option for me to commit these changes

**Review by realslimshanky — CHANGES_REQUESTED** [review]
The code needs to be added to the correct file. Please share the steps you followed to make this PR so that we can help you better.

**Review by 0x48piraj — COMMENTED** [review]
Status ?

**Comment by kaushikichhabra** [comment]
1. open https://github.com/fossasia/gci17.fossasia.org/
blob/gh-pages/installation/installation_windows.md
2. click find file
3. Open data folder
4. open blogs.yml
5. there is no option for me to compose a code/ pull request.

**Comment by kaushikichhabra** [comment]
1. open the gci website
2. go to pull requests
3. compare "gh pages" to "revert 534"
4. create pull request with the required format

**Comment by kaushikichhabra** [comment]
my task is due by 1:27
please someone help

**Comment by kaushikichhabra** [comment]
can you give me few extra hours to finish this task..if I am not able to do
this by 12.
link to my task: https://codein.withgoogle.com/dashboard/task-
instances/6017835425857536/
thanks

**Comment by kaushikichhabra** [comment]
File 567.jpg

i had uploaded picture..but now i am not able to find it

**Comment by kaushikichhabra** [comment]
my image is no longer there..and  uploads are disabled

**Comment by kaushikichhabra** [comment]
my task is due at 1;27 and less than an hour is left
please help🙏🙏🙏🙏🙏🙏🙏🙏
give me few extra hours

**Comment by kaushikichhabra** [comment]
earlier i sent my image through via upload
but now it is blocked

**Comment by kaushikichhabra** [comment]
please help and give some extra time(few hours)
 🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by kaushikichhabra** [comment]
I have made another pull request..check it

**Review by ParthS007 — COMMENTED** [review]
closing as a duplicate of #884

**Pull request closed without merging**
