### PR TITLE
Add img blog

### PR DESCRIPTION
**Pull request by amryarios**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please provide a preview link .

**Comment by anshumanv** [comment]
It would be better if you can give a preview link.

**Review by anshumanv — APPROVED** [review]
LGTM!

**Review by the-codingninja — APPROVED** [review]

**Review by akshatnitd — APPROVED** [review]
LGTM :rocket:

**Comment by the-codingninja** [comment]
https://amryarios.github.io/gci17.fossasia.org/
@ParthS007 this is the link I checked it here to approve the task

**Comment by anshumanv** [comment]
Thanks @ms10398 :+1: 
@amryarios try to provide a test link in PR description from next time.

**Pull request merged**
