### PR TITLE
added photo of yashkumarverma

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Hello there,

I've added my own photo and changed index.html to show up the image.

### CODE REVIEW

**Review by abishekvashok — APPROVED** [review]
LGTM

**Review by abhinavk96 — APPROVED** [review]

**Review by daminisatya — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]
LGTM!

**Review by rishiraj824 — APPROVED** [review]

**Comment by abishekvashok** [comment]
Can someone merge this, everyone has been approving :)

**Comment by YashKumarVerma** [comment]
actually ! :P

**Pull request merged**
