### PR TITLE
Create mentor's (Piyush Agrawal) profile

### PR DESCRIPTION
**Pull request by NishSatish**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please squash all your commits in one.

**Review by anshumanv — DISMISSED** [review]
LGTM, squash commits.

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please ensure that the dimensions of the image is 240 x 240 pixels

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash your commits

**Review by dilpreetsio — COMMENTED** [review]
@NishSatish All images must 240 x 240. Please update the images.

**Comment by NishSatish** [comment]
I squashed the

**Pull request closed without merging**
