### PR TITLE
Added the link of my blog

### PR DESCRIPTION
**Pull request by AmanSingh200**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by supunTE** [comment]
Add a preview link. It's must be there.

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please upload the image that you have specified in the img/blogs folder

**Review by harshit98 — CHANGES_REQUESTED** [review]
Kindly upload your image which you have specified.

**Comment by AmanSingh200** [comment]
img_20171201_200847095

**Comment by AmanSingh200** [comment]
dsc_3288

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash the commits :+1:

**Review by harshit98 — APPROVED** [review]

**Comment by harshit98** [comment]
Kindly squash your commits from next time!

**Comment by harshit98** [comment]
Reverting it back, since it is failing Travis CI.

**Comment by AmanSingh200** [comment]
size of the image isnt specified properly 
whether its is 200 * 200 pixels or what

**Pull request merged**
