### PR TITLE
Added Transalations

### PR DESCRIPTION
**Pull request by samyakbvs**
Irish, Danish, Italian

### CODE REVIEW

**Review by niranjannitesh — APPROVED** [review]

**Review by gabru-md — APPROVED** [review]
:+1:

**Review by vaibhavsingh97 — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Comment by vaibhavsingh97** [comment]
@anshumanv Please check translation before merging

**Comment by gabru-md** [comment]
@vaibhavsingh97 I've checked the translations and then reviewed.
It matches with Google Translate.

**Comment by samyakbvs** [comment]
Is it ready to merge?

**Comment by anshumanv** [comment]
Thanks @gabru-md for verification, merging.

**Comment by gabru-md** [comment]
sure

**Comment by anshumanv** [comment]
Is there an issue for this @samyakbvs?
If not, please make sure you create an issue for any change you're proposing and reference the issue in the PR you make.

**Pull request merged**
