### PR TITLE
Added mentor

### PR DESCRIPTION
**Pull request by saarthakchats**

### CODE REVIEW

**Review by nzec — APPROVED** [review]
Learn to squash commits. Other than that, it is all good!

**Comment by saarthakchats** [comment]
You have added some commits after me #390. And I have worked on the online editor. So I might not be able to squash. Can we do that from the next PR

**Comment by nzec** [comment]
@saarthakchats Okay! Fine!

**Review by nikit19 — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]
LGTM but would be better if u could squash commits

**Review by dilpreetsio — APPROVED** [review]

**Pull request merged**
