### PR TITLE
Added links to Project's corresponding websites :D and Thank you for Contributing !!

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes issue: #939

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/graniteknughtgci17.fossasia.org/#fossasia-projects --> preview link :D

**Comment by Beta-King** [comment]
please review and merge :D

**Review by realslimshanky — APPROVED** [review]
Nice work :+1:

**Comment by yashk0thari** [comment]
Thanks @realslimshanky :D

**Comment by yashk0thari** [comment]
@harshit98 @nikit19 @rupav please review and merge it guys :D

**Review by anshumanv — COMMENTED** [review]
Which issue are you solving?

**Comment by yashk0thari** [comment]
@anshumanv , given the issue number :D could you approve and merge it ??

**Comment by anshumanv** [comment]
Translation is in which language?

**Comment by yashk0thari** [comment]
@anshumanv its in Ukrainian :D can we please merge now ??

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
