### PR TITLE
Refactored Files

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request
- Refactored files and formatted

### CODE REVIEW

**Comment by poush** [comment]
@vaibhavsingh97, some conflicts here.

**Comment by vaibhavsingh97** [comment]
Will fix 😄

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by abishekvashok** [comment]
It's big change, pls resolve the conflicts, if we merge this now, we might make conflicts for all PRs currently there.

**Review by 0x48piraj — COMMENTED** [review]
Conflicting, as codebase evolved. :worried:

**Comment by harshit98** [comment]
@vaibhavsingh97 It is unclear what you're trying to do here. Kindly mention the issue and description of what has been done in this pull request.

**Comment by vaibhavsingh97** [comment]
Oops!! sorry, missed that. Will update

**Pull request closed without merging**
