### PR TITLE
Added pic correctly...

### PR DESCRIPTION
**Pull request by yashk0thari**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by yashLadha** [comment]
You have marked that you are including a live link or a demo link. But you
haven't please only mark those things that you have completed don't
unnecessary mark them.

**Comment by yashk0thari** [comment]
Where have i done this ??

**Comment by yashk0thari** [comment]
ohk, so how do i change it ??

**Comment by yashk0thari** [comment]
Ohk reverted it back, no check on that one

**Comment by yashk0thari** [comment]
Is it mergeable now ??

**Review by nikit19 — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]
LGTM, but would be better if u could squash commits.

**Review by akshatnitd — COMMENTED** [review]
@Beta-King Can you please squash the commits ?

**Comment by yashk0thari** [comment]
How to squash commits ??

**Comment by abishekvashok** [comment]
run inside your fork:
`git rebase -i HEAD~noofcommitstosquash`
Then change pick from the second line to the last line to squash. Save and exit. Then in the editor that pops up enter commit message and description. Save and exit. The force push:
`git push -f`

**Comment by yashk0thari** [comment]
done that

**Comment by yashk0thari** [comment]
now can you merge ??

**Comment by yashk0thari** [comment]
FYI, i think you gave me the commands for cmd in windows but i i have a mac so those commands did not work, but i googled and stuff and finally hopefully got it done anyways :D, but thanks for the help anyways :)

**Review by akshatnitd — APPROVED** [review]
Super work! Nice to see, that you googled up and did it yourself 🙂

**Comment by yashk0thari** [comment]
thanks

**Pull request merged**
