### PR TITLE
Fixed #455: Added the names

### LINKED ISSUE #455: Projects
### Expected results
The name of the students should be mentioned
### Actual results
The name of the students aren't be mentioned
### Steps to reproduce the issue
Add there names 
## Would you like to work on this
Yes!

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/kay-gci17.fossasia.org/

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@samyakbvs  Can you please give a valid description and follow the PR template and add a scrrenshot of the changes done by you, It will help in review . I hope you understand 👍

**Review by harshit98 — APPROVED** [review]
Excellent work! @samyakbvs. I was expecting something like this. 💯

**Comment by samyakbvs** [comment]
Thanks @harshit98

**Pull request merged**
