### PR TITLE
Fixed #932: Added all internal links under one umbrella

### LINKED ISSUE #932: Combining all internal links into one dropdown
I guess the title is self explanatory

Pls don't take up this issue I am working on it

### PR DESCRIPTION
**Pull request by samyakbvs**
The navbar was flooding that is the reason for this PR

https://samyakbvs.github.io/internal-links-gci17.fossasia.org/

### CODE REVIEW

**Review by harshit98 — APPROVED** [review]
Good job! 💯 
I will merge this PR once Travis passes.

**Comment by nzec** [comment]
Nice work!

**Comment by samyakbvs** [comment]
Thanks @duttaditya18

**Review by akshatnitd — APPROVED** [review]
Good work :)

**Review by anshumanv — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]

**Review by rupav — APPROVED** [review]

**Pull request merged**
