### PR TITLE
Fixed #665: Deleted lokinder singh

### LINKED ISSUE #665: Lokhinder singh
The image has to be deleted as it was added by mistake

### PR DESCRIPTION
**Pull request by samyakbvs**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
screen shot 2017-12-31 at 11 56 11 am
This is the PR which initially deleted the image but someone thought it was an issue as only the image was deleted and restored the image
Now the whole block for Lokhinder Singh has been deleted

- Fixes #<Issue no.>665

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
@samyakbvs this bug has already been fixed by @saarthakchats he has added a new image
Check this out: https://github.com/fossasia/gci17.fossasia.org/pull/656

**Comment by samyakbvs** [comment]
Before:
screen shot 2017-12-31 at 12 06 32 pm
After:
screen shot 2017-12-31 at 12 05 43 pm
(The AFTER screenshot is taken by locally deploying the site)

**Comment by samyakbvs** [comment]
@arjunpandey2003 That PR is the reason of the issue he added it back instead it is supposed to be delted

**Comment by arjunpandey2003** [comment]
@samyakbvs why should it be deleted, lokhinder singh is a particpant i think and wants his image

**Comment by harshit98** [comment]
Lokinder Singh is a participant. I have merged his PR. He has added his image on the website. I'm closing this PR @samyakbvs.

**Pull request closed without merging**
