### PR TITLE
Added Social media Section

### PR DESCRIPTION
**Pull request by ghost**
Added Social media Section.

### CODE REVIEW

**Comment by the-codingninja** [comment]
Your PR has merge conflicts please try to solve them

**Comment by the-codingninja** [comment]
Can you provide a deployment link to review it easily

**Comment by ghost** [comment]
https://sabakhukhunashvili.github.io/gci-foosasia/
Social Media is under "LIGHTBOX GRID GALLERY" 
Thank you <3

**Review by the-codingninja — APPROVED** [review]
LGTM!!

**Comment by ba11b0y** [comment]
@SabaKhukhunashvili I think a section for social media is unnecessary, as link in Navbar already points to that.

**Review by anshumanv — APPROVED** [review]

**Comment by ba11b0y** [comment]
Also please first open an issue and then make a PR for the corresponding issue 😄

**Comment by ba11b0y** [comment]
@SabaKhukhunashvili @SaptakS @poush Closing this as not needed.
Try working on some existing issues or first open an issue and then open a PR.
Thanks for contributing anyways.

**Pull request closed without merging**
