### PR TITLE
UPDATE MENTORS.YML

### PR DESCRIPTION
**Pull request by ShivamRai2003**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by ParthS007 — COMMENTED** [review]
@ShivamRai2003 Please provide a preview link 👍

**Comment by ShivamRai2003** [comment]
how should i know about my preview link plzz help

**Comment by ShivamRai2003** [comment]
(shivamrai2003.github.io) preview link

**Comment by harshit98** [comment]
Provide your own photo instead of others.

**Comment by ShivamRai2003** [comment]
As you can see we have to add mentors photo not ours

**Review by nikit19 — APPROVED** [review]

**Comment by nikit19** [comment]
@ShivamRai2003  `your-username.github.io/name-of-repository` is your preview link

**Comment by ShivamRai2003** [comment]
please merge it.

**Review by dilpreetsio — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Comment by ShivamRai2003** [comment]
now plzz merge it

**Pull request merged**
