### PR TITLE
Add Dangerfile

### PR DESCRIPTION
**Pull request by m1guelpf**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot: https://m1guelpf-forks.github.io/gci17.fossasia.org
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Add a Dangerfile as part of #221. Please see the issue for details. This can be merged without waiting for part 2.

### Related issue:

#221

### CODE REVIEW

**Review by isuruAb — CHANGES_REQUESTED** [review]
@m1guelpf  please mention the issue number in pull request body that you are going to solve from this pull request
cheers

**Comment by m1guelpf** [comment]
@isuruAb It's already there, I'm solving #221

**Comment by akshatnitd** [comment]
@mariobehling This PR needs Danger app added to this repository. Here is the link, https://github.com/apps/danger/installations/new

**Comment by abishekvashok** [comment]
@m1guelpf status pls

**Comment by m1guelpf** [comment]
@abishekvashok I'm waiting for revision and merge.

**Pull request merged**
