### PR TITLE
Fixes #672 : Changed @demonsingh336's image in Students section

### LINKED ISSUE #672: Want To Change My Photo In Fossasia Website Of Google Code In 2017-2018
I want my current profile picture to be uploaded instead of my previous photo please help me someone

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

* Changes @demonsingh336's image in student section as per his request (#672)
* Fixes #672

***Preview Link : https://duttaditya18.github.io/gci17.fossasia.org/students***

### CODE REVIEW

**Comment by ghost** [comment]
Thnk you so much... @duttaditya18 Happy New Year

**Comment by nzec** [comment]
@demonsingh336 You're welcome! Please review the changes.

**Comment by ghost** [comment]
had it got merged

**Comment by nzec** [comment]
@demonsingh336 This hasn't been merged yet. Please review this.

**Comment by ghost** [comment]
how to review

**Comment by nzec** [comment]
@demonsingh336 Go to the "Files Changed" tab and click on review changes and click on approve,

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
done

**Comment by ghost** [comment]
now

**Review by Ploypiti — APPROVED** [review]
LGTM 🐍

**Review by anshumanv — APPROVED** [review]

**Comment by ghost** [comment]
when will it change on original site @duttaditya18

**Pull request merged**
