### PR TITLE
Fixes #755 : Minified/Compressed css libraries

### LINKED ISSUE #755: Website: Improve Loading Times and Code Quality of FOSSASIA Google Code-In website
### Expected results
Make our website fast! (if not blazing fast!)

### Actual results
Our website lags now, and it's loading time is greater than other websites.

### Steps to reproduce the issue
**_Visit : https://gci17.fossasia.org/_**

## Would you like to work on this

**GCI Students!**

### PR DESCRIPTION
**Pull request by 0x48piraj**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Compressed some css libraries (as they are not manipulated :wink: )
- _**Preview - https://0x48piraj.github.io/gci17.fossasia.org/**_
- Fixes #755 

Ping @harshit98 @ParthS007 @vaibhavsingh97 :+1: 

> **_For ref : Used https://github.com/ben-eb/cssnano_**

### CODE REVIEW

**Comment by harshit98** [comment]
Add extra space at EOF. This applies to all the three files.

**Comment by 0x48piraj** [comment]
I used an automated css compressor named **_[cssnano](https://github.com/ben-eb/cssnano)_**
In the documentation, I read somewhere that don't manually try to change the files when using the `default` configuration. :blush:

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
`css/bootstrap.min.css` is already minified and you can use instead of `css/bootstrap.css`.

**Comment by vaibhavsingh97** [comment]
@0x48piraj Please do what @harshit98 had asked

**Comment by 0x48piraj** [comment]
It's not recommended in the docs @vaibhavsingh97

**Review by harshit98 — APPROVED** [review]
> I used an automated css compressor named cssnano
In the documentation, I read somewhere that don't manually try to change the files when using the default configuration.

Okay @0x48piraj 

LGTM! 💯

**Comment by 0x48piraj** [comment]
Thanks @harshit98 !

**Pull request merged**
