### PR TITLE
Add "Thank you for contributing" in Indonesian

### PR DESCRIPTION
**Pull request by amryarios**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please resolve conflicts and it would be better if you could squash your commits

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@amryarios  closing this PR , first update your local and fork repo and then make a PR, I hope you understand. Thanks 👍

**Comment by amryarios** [comment]
sorry i just reply now? @ParthS007 can you explain in more detail, because I still do not understand what you mean? hope you want to explain it :+1:  :)

**Comment by amryarios** [comment]
@ParthS007

**Comment by ParthS007** [comment]
@amryarios Your PR contains lots of old commits so I want to say please update your fork and local repo and then make a PR by going through `README.md` first.I hope you got it now 👍

**Pull request closed without merging**
