### PR TITLE
Fixed #527: Improvised names

### LINKED ISSUE #527: Student project
The names look very disorganised and their display is not up to Fossasia standards

## Would you like to work on this
Yes! pls don't work on it

### PR DESCRIPTION
**Pull request by samyakbvs**
Before:
screen shot 2017-12-26 at 10 01 51 pm
After:
screen shot 2017-12-26 at 10 16 49 pm

https://samyakbvs.github.io/namessamyak-gci17.fossasia.org/
Closes #527

### CODE REVIEW

**Comment by anshumanv** [comment]
The current site looks alright to me.

**Comment by NaviRocker** [comment]
@samyakbvs I don't think that this is a valid change

**Comment by samyakbvs** [comment]
Actually the image in AFTER that's how the site looked before somebody changed and made it like the Before image. From my perspective the way the names are written in the BEFORE image is not good at all, rest I leave it for you all to decide

**Comment by anshumanv** [comment]
We're seeing images in the AFTER section in the website presently.

**Review by 0x48piraj — APPROVED** [review]
LGTM! :tada:

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@samyakbvs  Please close this PR as transition is applied by other student and there is no need to remove it and Please update your forked repository 👍

**Comment by vaibhavsingh97** [comment]
Closing both issue and PR as this is not an issue. Please update your fork repository. Thanks

**Pull request closed without merging**
