### PR TITLE
Added fossasia's Pinterest link in missing places :D

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/harenhall.gci17.fossasia.org/ --> Preview Link :D

**Comment by anshumanv** [comment]
How do you know that's the official fossasia pintrest page?

**Comment by yashk0thari** [comment]
thats the only account in pinterest that has the name 'fossasia' and it is written that if a social media platform doesnt have a fossasia's page we can create one :D

**Comment by yashk0thari** [comment]
Besides i used the same link for another PR and the mentors approved it :D

**Comment by yashk0thari** [comment]
However if this is not usable, i'll change the link to a relevant one; no worries :D

**Comment by yashk0thari** [comment]
screen shot 2018-01-04 at 11 10 44 pm

**Review by ParthS007 — COMMENTED** [review]
closing this PR as the added link is not the official account of `FOSSASIA`. thanks

**Comment by yashk0thari** [comment]
Ohk

**Pull request closed without merging**
