### PR TITLE
Student Data

### PR DESCRIPTION
**Pull request by HasaluSL**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Review by the-codingninja — CHANGES_REQUESTED** [review]
You have removed lots of data which was not required to be deleted.
Please correct it.

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
a lot of data removed.
please restore.

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please restore the deleted data and add students details and image in appropriate directories.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Conflicts, resolve them.
Squash the commits as well. :+1:

**Comment by ParthS007** [comment]
@HasaluSL closing this PR, Please create an issue of the bug/feature and then create a PR referencing it and provide a proper PR message 👍

**Pull request closed without merging**
