### PR TITLE
Update blogs.yml

### PR DESCRIPTION
**Pull request by abhinavraj0123456789**
Added my blog details

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by harshit98** [comment]
Your demo link: https://abhinavraj0123456789.github.io/gci17.fossasia.org/ is showing me old website. Have you updated changes in your working branch?

**Comment by harshit98** [comment]
The blog by Saarthak Chaturvedi is coming two times. Please resolve the issue. Thanks!

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Many Blogs are showing two times. Fix that!

**Review by anshumanv — CHANGES_REQUESTED** [review]
The above changes plus you need to upload an image for your blog post.

**Review by NaviRocker — CHANGES_REQUESTED** [review]
Please Update your Repo

**Comment by ParthS007** [comment]
closing this as a duplicate of #453

**Pull request closed without merging**
