### PR TITLE
Added Links in Nav

### PR DESCRIPTION
**Pull request by nzec**
* Added links in Nav
* Added smooth scroll to all internal links (i.e. the ones with an href that starts with "#")
* Aims to fix the half of the issue #86

Link to my task: https://codein.withgoogle.com/dashboard/task-instances/5173243537260544/

### CODE REVIEW

**Comment by lazyprop** [comment]
@duttaditya18 bhai kal exam hai

**Comment by nzec** [comment]
@fossasia/fossasia-gci Please take a look.

**Comment by codethejason** [comment]
@duttaditya18 Please resolve merge conflicts.

**Comment by nzec** [comment]
Can the person merging this please squash the commits as well? Because if I do squash the commits, new conflicts will arise.

**Comment by akarshan96** [comment]
@duttaditya18 can you provide the site link too.

**Comment by codethejason** [comment]
You can resolve merge conflicts when you solve merge conflicts - it's good practice.

**Comment by nzec** [comment]
@codethejason I will do that from now on. Thank you so much for the suggestion.

**Pull request merged**
