### PR TITLE
Added Repositories for Contributors to work on with

### LINKED ISSUE #365: Github Repos in Website
It would be great if Fossasia's Repositories are on the Website. So that If a Visitor likes it, He/She can start from there itself

### PR DESCRIPTION
**Pull request by NaviRocker**
Fixes #365 
Added Repositories for Contributors to work on with
Preview Link - https://naveentherocker.github.io/gci17.fossasia.org/repos.html

Linked the Explore the Site Button to repos.html So it would be perfect as earlier it was linked to Mentors

### CODE REVIEW

**Comment by akshatnitd** [comment]
@naveentherocker Which issue does it address? 
Also, it is really needed ?

**Comment by NaviRocker** [comment]
Well, the Task regarding using Contribution API is still active. So I did this PR @akshatnitd.
It's better to remove that task then. 
Task Link - https://codein.withgoogle.com/tasks/5093390565769216/

**Comment by akshatnitd** [comment]
@naveentherocker It is better to think of a better use case of the Github Contributors API.

**Comment by NaviRocker** [comment]
Ok sure. I'll work on a new execution

**Comment by NaviRocker** [comment]
@akshatnitd How is it now?

**Comment by abishekvashok** [comment]
I don't know whether we really need this. But however since you have worked. It looks fine.

**Comment by nzec** [comment]
This is indeed very unnecessary.

**Comment by NaviRocker** [comment]
@abishekvashok @duttaditya18 Well this is just a small commit and I think something like this will be useful for the new visitors to engage in Contributing.

**Comment by 0x48piraj** [comment]
Yep. It's unnecessary. Not such a good use case.
But being optimistic, the **Explore the site** button was sending to Mentors Page, It's better than that though :smile:

**Review by 0x48piraj — COMMENTED** [review]
Why you reordered `image` in `mentors.yml` ?

**Comment by NaviRocker** [comment]
It was my last PR. It got merged @0x48piraj .

**Comment by m1guelpf** [comment]
Isn't it there a better way to fix repositories with Jekyll instead of JQuery?

**Review by akshatnitd — APPROVED** [review]

**Review by nzec — APPROVED** [review]
The images look bad as they repeat but other than that, it looks cool!

**Review by isuruAb — APPROVED** [review]

**Comment by isuruAb** [comment]
@duttaditya18  yes we can improve the UI step by step. 👍

**Pull request merged**
