### PR TITLE
GCI Fossasia task

### PR DESCRIPTION
**Pull request by NishithP2004**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by NishithP2004** [comment]
6d0a836e-3182-43cd-83cb-ad2b1699aca3

**Comment by NishithP2004** [comment]
For GCI task Website: Add Your Photo to the GCI FOSSASIA Site Student Section and Connect with Projects on GitHub ( FOSSASIA )

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please send a clean pr to gh-pages branch with only a single commit.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Resolve Commit errors, else close and open a new PR

**Comment by harshit98** [comment]
I have closed this PR due to many conflicts. Please open a fresh PR for it. Thanks!

**Pull request closed without merging**
