### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by RedeemCode67**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please provide a link to test the changes and resolve conflicts.

**Review by isuruAb — COMMENTED** [review]
Please provide a preview link and resolve conflicts

**Comment by abishekvashok** [comment]
Please provide a relevant description.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved.

**Comment by ParthS007** [comment]
@RedeemCode67  closing this PR, Please create an issue of the bug/feature and then create a PR referencing it.

**Pull request closed without merging**
