### PR TITLE
Added blog

### PR DESCRIPTION
**Pull request by saarthakchats**

### CODE REVIEW

**Comment by saarthakchats** [comment]
@ParthS007 
This is it

**Comment by ParthS007** [comment]
Please provide a preview link?

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/satsuupsgci17.fossasia.org/

**Comment by saarthakchats** [comment]
@ParthS007

**Review by ParthS007 — APPROVED** [review]

**Comment by saarthakchats** [comment]
@ParthS007 
Can you approve this task

**Comment by saarthakchats** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5185608102182912/

**Comment by saarthakchats** [comment]
I have two merged PRs  @ParthS007

**Pull request merged**
