### PR TITLE
Added Feature to Student Project Section :D

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`
#846 - I've contributed to this issue :D

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/minipeggci17.fossasia.org/ --> Preview Link :D

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@Beta-King Please give space between the button and above content just like other buttons present on site.
image
**expected space**
image
do proper alignment also 👍

**Comment by yashk0thari** [comment]
ohk; will work on them :D

**Comment by yashk0thari** [comment]
Made changes :D

**Comment by yashk0thari** [comment]
https://beta-king.github.io/boralegci17.fossasia.org/#projects ---> Preview link :D

**Comment by yashk0thari** [comment]
please review again :D

**Review by 0x48piraj — APPROVED** [review]

**Comment by yashk0thari** [comment]
Please review :>

**Comment by yashk0thari** [comment]
guys can we merge ?? :D

**Review by sayak119 — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Comment by yashk0thari** [comment]
Can we merge ?? :D

**Pull request merged**
