### PR TITLE
FOSSASIA BLOG (GOOGLE CODE.IN)

### PR DESCRIPTION
**Pull request by kaushikichhabra**
This is the link to my blog-
https://fossasiasblog.wordpress.com/blog/
Please tell if any changes are to be done...
Thanks 
Your Sincerely 
Kaushiki

### CODE REVIEW

**Review by nikit19 — COMMENTED** [review]
You have to fork the repository and then send a pull request from your forked repository. Steps for doing it are given in the READ.md

**Review by gabru-md — CHANGES_REQUESTED** [review]
There are conflicts with your PR.

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@kaushikichhabra  Please first update your local and forked repo and then go through `README.md` on how to add a blog. Closing this PR as it contains a lot of previous commits. Please ask if you face any problem in gitter channel 👍

**Comment by kaushikichhabra** [comment]
Please grant permission  to My blog...

**Pull request closed without merging**
