### PR TITLE
Fixed 391, 362 and 3rd point of 269

### LINKED ISSUE #362: One of students projects' link is broken!
### Expected results
Make it correct.

### Actual results
One of student projects' link is broken in Students Projects Section.
st
Doon International School project by @YashKumarVerma is not working.
See below picture that came after I clicked that project.
st2

### Steps to reproduce the issue
Add correct link to that project or, remove that project.

## Would you like to work on this
@YashKumarVerma Please add correct link.

### LINKED ISSUE #391: The github icon is unaligned
### Expected results
Github icon should be in line
### Actual results
Github icon is unaligned
## Would you like to work on this
Yes, working on it!

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

* Aligned Blog, videos, Projects to center.
* Fixed YashKumarVerma's broken project link.
* Fixed the Github logo which was not aligned (too big)
* Fixes #362 and 3rd point of #269 
* Fixes #391 

**Here is the preview link :** https://duttaditya18.github.io/gci17.fossasia.org/

---

### CODE REVIEW

**Comment by abishekvashok** [comment]
Pls solve only 1 issue per pr.

**Review by abishekvashok — APPROVED** [review]
Ack

**Comment by duttaditya18** [comment]
@abishekvashok 
>Pls solve only 1 issue per pr.
Doesn't that allow people to just get more contributions for less work?

**Review by sansyrox — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
@duttaditya18 Please check the checkboxes of the issues solved in #269

**Comment by 0x48piraj** [comment]
@ParthS007 Please close this issue.
Also, one issue was incorrectly done.
I made a new PR for that. :+1:

**Pull request merged**
