### PR TITLE
Added Interview Blog

### PR DESCRIPTION
**Pull request by saarthakchats**

### CODE REVIEW

**Comment by saarthakchats** [comment]
I did it on the online editor

**Comment by nikit19** [comment]
Please provide a preview link

**Comment by saarthakchats** [comment]
I'll make sure to merge from the next time

**Comment by duttaditya18** [comment]
Cool!

**Comment by nzec** [comment]
Learn to commit. It would come in handy!

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/c-u-shotm-g-c-i-1-7.fossasia.org/

**Comment by saarthakchats** [comment]
I know how to but I am having trouble doing it right now. I will make sure to do it from the next time :)

**Comment by supunTE** [comment]
merge this with upstream

**Review by akshatnitd — COMMENTED** [review]
Please squash the commits and you are done :)

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
