### PR TITLE
Demonsingh336 patch 1

### PR DESCRIPTION
**Pull request by ghost**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by ghost** [comment]
PLease someone change my photo from current photo on fossasia code in website

**Comment by harshit98** [comment]
@demonsingh336 Delete your old photo and add a new one (replace). You haven't deleted your old image.

Once you're done with the changes, push them. Mentors will review your PR.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
No need of two same photos, delete one of them.
Squash the commits too !

**Comment by ghost** [comment]
photos are not same one has the wrong dimensions 240*160 and one is of
240*240

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@demonsingh336  You have to delete your present image and add the new one in place of it 👍

**Comment by ghost** [comment]
yes i have but there is no change on tge website please someone on my
behalf change my photo from website

**Comment by harshit98** [comment]
I'm closing this pull request @demonsingh336. Kindly create a fresh PR with the suggested changes done. You can find a lot of resources on Google for such basic things.

- Make sure you clone the forked repo to avoid "uploads disabled" error.
- Drag your image in the working project directory and push the changes. Make sure the image name is same so that it is replaced. When you will check changes using `git status`, it will be reflected there.
- Make sure the image is in correct folder 'img'.

**Pull request closed without merging**
