### PR TITLE
index.html: Enhances contributors section

### PR DESCRIPTION
**Pull request by abishekvashok**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

Makes contributor's section match the site's design and make it in
comfort with other sections. Also made the images to be in standard
240x240px dimensions.

# Link to test:
https://abishekvashok.github.io/gci17.fossasia.org

# Screenshots of the change
screenshot from 2017-12-08 18-30-12
screenshot from 2017-12-08 18-30-17

### CODE REVIEW

**Comment by anshumanv** [comment]
Nice, just make a little change near the contributors section heading, it says `students who have contributed`, and since not only students contributed, it's better to have `people who have contributed..`

**Comment by abishekvashok** [comment]
@anshumanv sure. Would do that.

**Comment by abishekvashok** [comment]
@anshumanv done, pls review;

**Comment by anshumanv** [comment]
Awesome! Thanks for squashing the commits. :smile:

**Review by anshumanv — APPROVED** [review]

**Comment by abishekvashok** [comment]
@anshumanv yours welcome, pls merge as there are chance for conflicts :)

**Comment by abishekvashok** [comment]
Link to my task: https://codein.withgoogle.com/dashboard/task-instances/4701744267264000/

**Pull request merged**
