### PR TITLE
My opinion about gsc

### PR DESCRIPTION
**Pull request by arunkn271778640**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please read the README.MD to see how to add your blog. Please make your blog on WordPress

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Please fix this, otherwise close this PR :+1:

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please read `README.MD` on how to add a blog and update your PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

**Review by isuruAb — COMMENTED** [review]
please post this on your own blog and share it here. read README.MD on how to add a blog and update your PR.

**Review by ParthS007 — COMMENTED** [review]
@arunkn271778640 Closing this PR due to inactivity.

**Pull request closed without merging**
