### PR TITLE
Add a new blog post

### PR DESCRIPTION
**Pull request by Ploypiti**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added new blog & image
- [Live preview here](https://ploypiti.github.io/gci.fossasia.org/)

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]

**Comment by ParthS007** [comment]
@Ploypiti Well Done! Please Squash your commits.
image

@Ploypiti If you remove these spaces, it will be a plus. 👍

**Comment by anshumanv** [comment]
Agree with @ParthS007, this PR can close #243 too then.

**Comment by Ploypiti** [comment]
I worked fine in Dev tool but **didn't work in actual code**, furthermore this is case-by-case, if the title is really long (5+ lines) I'll need to cut it short eg. Michalski's post, if not, just removing the margin works.

image

I'll try adding the CSS directly to index.html or you'll need to edit the margin everytime someone added a long title, just a suggestion but you should limit the title length to avoid this issue or replace long title with '...' instead.

**Comment by anshumanv** [comment]
GFI and try if it solves the issue. :smile:

**Comment by Ploypiti** [comment]
Wait a min I'm squashing commits 😊

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
@Ploypiti Solve #243 in a new PR.Merging this 👍

**Comment by anshumanv** [comment]
Merge this @ParthS007 since the task has already been approved.

**Pull request merged**
