### PR TITLE
Make Danger work with Travis

### PR DESCRIPTION
**Pull request by m1guelpf**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot **(not applicable as not altering site)**
- [x] Images are `240 x 240` [w x h] **(not applicable as not adding images)**
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Make Danger work with Travis CI as part of issue #221 ([why?](https://github.com/fossasia/gci17.fossasia.org/issues/221#issuecomment-352851302))

### Related issue

#221

### Note to mantainers

[See below ⬇️ ](https://github.com/fossasia/gci17.fossasia.org/pull/371#issuecomment-352855684)

### CODE REVIEW

**Comment by m1guelpf** [comment]
Note to mantainer with access to Travis configuration: To make this work, a new **not private/hidden** variable should be added to the config named `DANGER_GITHUB_API_TOKEN` with a value of `3eae1dbf9d23bbddcf35bdba5e748ff89644292e`.

#### This is very important, and should be done ASAP to fix the Travis build.

**Comment by abishekvashok** [comment]
@m1guelpf the access token would get reverted if post it publicly.

**Comment by m1guelpf** [comment]
@abishekvashok Only if pushed to a repo. The token is "disabled" and shouldn't work until it's enabled (meaning that we're secure atm 😄 )

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Travis is failing! :worried:

**Comment by m1guelpf** [comment]
@abishekvashok That's because the token hasn't been added yet

**Comment by akshatnitd** [comment]
@mariobehling Needs your attention. Token needs to added to the Travis config.

**Comment by harshit98** [comment]
@akshatnitd:- @mariobehling is busy at some conference. Kindly convey him this message at mentor's chat channel.

**Comment by nzec** [comment]
GCI 17 has already ended. Don't see a point of this now.

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
