### PR TITLE
Update custom.css

### PR DESCRIPTION
**Pull request by a-v-lymarenko**
Add some animations for images(photos)

### CODE REVIEW

**Comment by abishekvashok** [comment]
Let's get professional @a-v-lymarenko, can you provide a description? :)

Best practises for fossasia: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Review by abhinavk96 — COMMENTED** [review]
@a-v-lymarenko Which issue does this pertain to? Please open a relavant issue with info on what you hope to accomplish  and link it to this PR . Also add in the description of the PR,  what changes will this PR bring  :)

**Comment by a-v-lymarenko** [comment]
Add some animations for images(photos)

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
Live link please for a quicker review ?

**Comment by abishekvashok** [comment]
Live link is: username.github.io/reponame
so for this PR it should be: https://a-v-lymarenko.github.io/gci17.fossasia.org

**Review by 0x48piraj — COMMENTED** [review]
Checked out your preview site. Implemented animation works.

**Comment by abishekvashok** [comment]
Can we get a status on this @jigyasa-grover

**Comment by nzec** [comment]
Can we get a status on this?

**Review by ParthS007 — APPROVED** [review]

**Review by vaibhavsingh97 — APPROVED** [review]

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
Please update your PR

**Review by nzec — CHANGES_REQUESTED** [review]
Looks really unrefined. In my opinion, it would have been better if the change was more subtle (like `border-radius` or something.)

**Review by supunTE — CHANGES_REQUESTED** [review]
Update your repo!

**Comment by harshit98** [comment]
Due to no activity, I'm closing this pull request @a-v-lymarenko.

Feel free to open the PR when you've done changes and updated your branch.

**Pull request closed without merging**
