### PR TITLE
Added Mentor Rahul Tiwari and Student Prasenjit Gautam

### PR DESCRIPTION
**Pull request by DotSlashTX**
Added Mentor Rahul Tiwari with image named : Rahul_Tiw.jpg and Student Prasenjit Gautam with image named : B477L3.jpg

### CODE REVIEW

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please fix all conflicts

**Comment by DotSlashTX** [comment]
Thanks for your help mentors but I can't get where the conflict is . I have updated all the information both for mentor and student , I have double checked it , the information I provided is 100% matching with the photos I added in img/mentors and img/students . My merged repository has no issues . Please help me out to get where the conflict is . I am struggling with this one .

**Review by ParthS007 — APPROVED** [review]
LGTM !

**Comment by ParthS007** [comment]
@ms10398 There is no Image of Rahul

**Comment by the-codingninja** [comment]
Wait @ParthS007

**Comment by the-codingninja** [comment]
His image name is changed in students.yml he is changing it back

**Comment by the-codingninja** [comment]
Great now its okay i think

**Review by the-codingninja — APPROVED** [review]

**Pull request merged**
