### PR TITLE
Please update 

### PR DESCRIPTION
**Pull request by Mridulbirla13**
A task of Google Code In - 2017.
Task was appointed to update the contribution section.

### CODE REVIEW

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash your commits!

**Comment by rishiraj824** [comment]
@Mridulbirla13 Please keep the description to only about the task. Also please fix the conflicts so that we can merge this. Thanks.

**Comment by NaviRocker** [comment]
Please Add a Proper Title for your Pull Request and don't forget to add a Preview Link

**Review by isuruAb — COMMENTED** [review]
@Mridulbirla13  please resolve conflicts and squash changes.don't forget to provide preview link with your PRs , then reviewers can review your PR easily and merge. cheers 👍

**Review by dilpreetsio — COMMENTED** [review]
@Mridulbirla13 Please use the following naming convention for the images `NameLastname` instead of `Name Lastname`. Lets not use a space in the image file name for consistency.

**Comment by ParthS007** [comment]
@Mridulbirla13  please  resolve conflicts and do the suggested changes .

**Comment by ParthS007** [comment]
@Mridulbirla13 please resolve conflicts and do the suggested changes .

**Review by ParthS007 — COMMENTED** [review]
closing due to inactivity and contributors section is fine, If you find any bug open a new PR 👍

**Pull request closed without merging**
