### PR TITLE
Many developments

### PR DESCRIPTION
**Pull request by saarthakchats**
Added a blog. Also fixed bug with dead-end links. Added relevant content to a template section.

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
Can you please share deployment link

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/bring-i-t-gci17.fossasia.org/

**Review by akshatnitd — COMMENTED** [review]
Please make only relevant changes in the PR, instead of making all sorts of changes in in a single PR. If you wish to make more changes, open an issue corresponding to it and open a separate PR for it.

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Please remove all other changes from this PR and open a new PR for it.

**Comment by saarthakchats** [comment]
Made a new one #440

**Pull request closed without merging**
