### PR TITLE
Removed unwanted space on blog section.

### LINKED ISSUE #311: Delete unwanted spaces on blog section
### Expected results
Remove spaces between images
### Actual results
No spaces
screenshot from 2017-12-15 12-00-20

## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

* Removed unwanted space on blog section. (by adding a `div.row` after every 4 blocks).
* Fixes #311

**Here is the live link :** https://duttaditya18.github.io/gci17.fossasia.org/

---

*I spent hours working this one out!* 😃

### CODE REVIEW

**Comment by nzec** [comment]
@fosssasia/fossasia-gci

**Review by anshumanv — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
Good Work @duttaditya18 . Have a look at #306 , you can do that 👍

**Comment by nzec** [comment]
Thanks @ParthS007! I'll check it out!

**Comment by shikhar-scs** [comment]
Is anyone working on #306 ? Or may I do it ? @ParthS007

**Comment by anshumanv** [comment]
Any of you can do it @shikhar-scs

**Pull request merged**
