### PR TITLE
Added Shreya Sandurkar's blog

### PR DESCRIPTION
**Pull request by shreyasandurkar**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request
Committing yml file with link to my blog

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Pls add image and data in a single pr

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please add your image and details in a single PR.
You can update your PR by adding commits in the same branch

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please close this PR as you have already made the required changes in #838 
ps: from now on, try to fix the existing PR using `git amend` instead of creating a new one. You welcome to ask for help if needed :)

**Review by 0x48piraj — COMMENTED** [review]
I think you should close this as you opened a new one

**Comment by nikit19** [comment]
Closing this PR as your other PR has been merged.

**Pull request closed without merging**
