### PR TITLE
Added a link (button) for student projects 2016

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can we have a squash?

**Comment by yashk0thari** [comment]
Yeah thats what i am doing rn :D

**Comment by yashk0thari** [comment]
Squashed !!

**Comment by yashk0thari** [comment]
please review and merge :D

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Hodorgci17.fossasia.org/ --> Preview Link

**Review by abishekvashok — APPROVED** [review]
Minor change, looks ready to be shipped.

**Comment by yashk0thari** [comment]
Minor change ?? is there something wrong with the changes ??

**Comment by abishekvashok** [comment]
Minor change means a small change

**Comment by yashk0thari** [comment]
ik ;D - idk how you are referencing it naa; minor change required or minor change done - cause ik i've made a minor change :D

**Comment by abishekvashok** [comment]
I was just referencing it is a small change and it is ready to go. Sorry if that did'nt make up.

**Comment by yashk0thari** [comment]
Lols kk :D

**Comment by yashk0thari** [comment]
My comprehending skills are not at par :>

**Pull request merged**
