### PR TITLE
Fix#255 Favicon Added

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- added favicon

### CODE REVIEW

**Comment by anshumanv** [comment]
Please use a descreptive PR title.

**Comment by codedsun** [comment]
@YashKumarVerma Nice to see your PR, make sure you should use proper PR Title. 
Like Fix#255 : Favicon Added 

Changing title !

**Comment by codedsun** [comment]
Fix #255 :Added Favicon

**Comment by YashKumarVerma** [comment]
thank you @codedsun @anshumanv

**Comment by anshumanv** [comment]
This favicon doesn't look appropriate, please use the original fossasia favicon used on - https://fossasia.org/

**Comment by YashKumarVerma** [comment]
Sure

**Comment by ParthS007** [comment]
@codedsun please wait for atleast 2 approval before merging . Thanks

**Pull request merged**
