### PR TITLE
added a blog

### PR DESCRIPTION
**Pull request by supunTE**
added a blog - interview a student

### CODE REVIEW

**Comment by supunTE** [comment]
https://stedirisuriya.github.io/gci17.fossasia.org/

**Comment by NaviRocker** [comment]
Don't Use the same Picture for Every Blog Image in the GCI Website

**Comment by supunTE** [comment]
next time i'll change

**Comment by anshumanv** [comment]
Please change it now.

**Comment by supunTE** [comment]
OK

**Comment by supunTE** [comment]
ok

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
