### PR TITLE
added pic to student section

### PR DESCRIPTION
**Pull request by Sudhanshuedoc**
here is my pic added to student section for the task Add Your Photo to the GCI FOSSASIA Site Student Section and Connect with Projects on GitHub

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Conflicts, please only add relevant commits

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts, remove unwanted commits and squash your commits

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
2 instances of images. Remove one.

**Review by nikit19 — COMMENTED** [review]
Try pulling the latest changes and please resolve conflicts

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@Sudhanshuedoc You have lot of previous commits, Please update your PR and do the changes 👍

**Pull request closed without merging**
