### PR TITLE
Added my blog

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Updated img file and blog.yml

### CODE REVIEW

**Review by NaviRocker — CHANGES_REQUESTED** [review]
Reduce the Size of the Image

**Review by NaviRocker — APPROVED** [review]
Now Fine. Try to Squash your Commits if possible.

**Review by nikit19 — APPROVED** [review]
LGTM but it would be better if you could squash your commits :+1:

**Comment by arjunpandey2003** [comment]
sure wait

**Comment by arjunpandey2003** [comment]
@nikit19 done

**Comment by arjunpandey2003** [comment]
pls merge and accept my task thanks!

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
