### PR TITLE
Fixes #923: Added a Blog

### LINKED ISSUE #923: Add a Blog
Add a New Blog to the Blog Section

### PR DESCRIPTION
**Pull request by NaviRocker**
Fixes #923
Added a New Blog to Blog Section

### CODE REVIEW

**Review by nikit19 — APPROVED** [review]

**Review by rupav — APPROVED** [review]
Good interview✨.

**Review by isuruAb — APPROVED** [review]

**Comment by rupav** [comment]
Resolve conflicts to get it merged.

**Comment by NaviRocker** [comment]
Done @rupav

**Comment by rupav** [comment]
Please squash it too.

**Comment by NaviRocker** [comment]
@rupav I committed the changes in Github Web. Please Squash and Merge it. Sorry!

**Comment by rupav** [comment]
You can still squash using git. 
`git pull origin`
And then squash using git.

**Comment by NaviRocker** [comment]
@rupav It shows that it is Up to Date when i do it.

**Review by anshumanv — APPROVED** [review]

**Comment by rupav** [comment]
Is there any branch patch-1 locally ??
Check using `git branch` .
If not add patch-1 as a branch.
Then pull again, `git pull origin patch-1 patch-1 `. Then squash.

**Comment by NaviRocker** [comment]
@rupav Still I get Others Files

**Comment by rupav** [comment]
`git log --graph` to see what commits need to be squashed. Then use squash commands to squash with your PR.  Post a screenshot wherever you face difficulty.

**Pull request merged**
