### PR TITLE
Fixes #543: Remove themify icons and move to font-awesome

### LINKED ISSUE #543: themify icons blocks page rendering
### Expected results

No script should block rendering

### Actual results

themify icons are blocking the rendering of the script above the fold

### Steps to reproduce the issue

See the page insights.
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgci17.fossasia.org%2F&tab=desktop

## Would you like to work on this

yes why not?

### PR DESCRIPTION
**Pull request by abishekvashok**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the white space as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

Removes themify ico0ns on the wake of the report by Google Pageinsights
that it blocks rendering of above the fold content resulting in slower
page load speed and lower page ranks (Google).

Both Font Awesome and themify icons were present and used, moves all
current icons to use Font Awesome icons and removes the css file of
themify icons.

Fixes #543

Live link to Preview: https://abishekvashok.github.io/gci17.fossasia.org/

### CODE REVIEW

**Comment by abishekvashok** [comment]
Ping @fossasia/website-admins

**Review by ParthS007 — APPROVED** [review]
LGTM ! Well done 👍

**Comment by abishekvashok** [comment]
Tq @ParthS007

**Review by saurabhjn76 — APPROVED** [review]
LGTM  👍

**Review by isuruAb — APPROVED** [review]

**Comment by abishekvashok** [comment]
@nikit19 ok, why was this reverted?

**Comment by nikit19** [comment]
@abishekvashok it wasn't. It was referenced while reverting some other commit but was not reverted.

**Pull request merged**
