### PR TITLE
Adding Anshuman

### PR DESCRIPTION
**Pull request by kartikeya23**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]
Thanks!

**Comment by kartikeya23** [comment]
#36 
Done as part of the issue

**Comment by anshumanv** [comment]
Is the task approved @kartikeya23 ?

**Comment by kartikeya23** [comment]
Yes but for another task I need PR to be addressing the issue #36
I'm creating a new PR though...

**Comment by anshumanv** [comment]
What are you creating a PR for?

**Comment by kartikeya23** [comment]
Adding another mentor

**Comment by kartikeya23** [comment]
Any other way I can get this PR under that issue? @anshumanv

**Comment by anshumanv** [comment]
Are you adding mentor as a part of the task?
I don't get what you mean by getting PR under that issue, please clarify.

**Comment by kartikeya23** [comment]
@anshuman73 
https://codein.withgoogle.com/tasks/5639979915018240/?sp-organization=6237166344601600&sp-is_beginner=False
This task says that I must take an issue and work on it. Issue #36 is to add a mentor so I want to show this PR

**Comment by anshumanv** [comment]
One PR can't suffice for 2 tasks, please pick existing issues from https://github.com/fossasia/gci17.fossasia.org/issues and solve any one of them and send a PR.

**Comment by anshuman73** [comment]
@kartikeya23 you seemed to have tagged the wrong Anshuman here :/
> @anshuman73

**Pull request merged**
