### PR TITLE
favicon improved, 2 blogs added

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- changed the favicon.ico image to preserve ratio of fossasia logo as said in #261 by @anshumanv 
- 2 blog entries added.

Preview at https://yashkumarverma.github.io/gci17.fossasia.org/

### CODE REVIEW

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Please upload diff. img for blogs.

**Comment by YashKumarVerma** [comment]
@abishekvashok

**Comment by YashKumarVerma** [comment]
Mind the favicon 😉 
screenshot 156

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
The favicon looks good but this is not used on the https://fossasia.org/.
I'd suggest to change it, but please wait and see what other think about this one.

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@YashKumarVerma Please use this https://github.com/fossasia/fossasia.org/blob/gh-pages/fossasia.ico

**Comment by YashKumarVerma** [comment]
@anshumanv @ParthS007

**Review by abishekvashok — APPROVED** [review]
LGTM

**Review by kubami9 — APPROVED** [review]
Nice work!

**Pull request merged**
