### PR TITLE
Blog about your participation in GCI and introduction of yourself!

### PR DESCRIPTION
**Pull request by STARGAZER173**
[] https://catechnical406767641.wordpress.com/2017/12/28/fossasia-blog-gci-2017/ (url)

### CODE REVIEW

**Comment by harshit98** [comment]
What's the purpose of opening this PR @Chirag1234567890 ? Why you're reverting back the changes?

**Review by nikit19 — COMMENTED** [review]
Please go through the readme.md to see how to add your blog.

**Comment by STARGAZER173** [comment]
Nikit19 please help me I don't know what to do

**Comment by STARGAZER173** [comment]
@harshit98 please help me what to do

**Comment by harshit98** [comment]
> What's the purpose of opening this PR @Chirag1234567890 ? Why you're reverting back the changes?

@Chirag1234567890 I don't know what you're trying to do here. How can I help you then?

**Comment by STARGAZER173** [comment]
@harshit98  I just want to link my blog to this website as given in the task

**Comment by nzec** [comment]
@Chirag1234567890 To do that, you need to add your image in 240x240 size in `img/blogs` and add a block in `_data/blogs.yml` in this format : 
```yaml
- url: URL to the blog
  title: Title of the blog
  img: Image of the blog
  author_name: Name of the author of the blog (most likely you)
```

Good luck!

**Comment by nikit19** [comment]
Fork this repository. Make the necessary changes and then send a pull request.
These links might help
https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/README.md
https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/installation/installation_windows.md

**Comment by STARGAZER173** [comment]
Thanks

**Comment by harshit98** [comment]
@Chirag1234567890 I'm closing this PR. Kindly create a fresh one. Make sure your branch is updated to avoid conflicts. 👍

**Pull request closed without merging**
