### PR TITLE
Add my blog post and Polish "Thank you for contributing"

### PR DESCRIPTION
**Pull request by kubami9**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

This PR also applies to #445

Add my blog post and Polish "Thank you for contributing"

Preview link: https://kubami9.github.io/gci17.fossasia.org-kubamichalski-contribute/

### CODE REVIEW

**Review by nzec — APPROVED** [review]
Cool!

**Review by nikit19 — APPROVED** [review]
LGTM !

**Comment by supunTE** [comment]
@kubami9 please tag this issue here https://github.com/fossasia/gci17.fossasia.org/issues/445

**Comment by kubami9** [comment]
@STEdirisuriya but this PR doesn't include any translation, it just adds "Thank you for contributing!" line in Polish since it has been deleted in some other PR

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
