### PR TITLE
animation added

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added hang animation to contributors heading
- removed the contributer.css file and added code to style.css

demo at [https://yashkumarverma.github.io/gci17.fossasia.org/](https://yashkumarverma.github.io/gci17.fossasia.org/)

### CODE REVIEW

**Comment by anshumanv** [comment]
I don't get why is this needed, the heading should be static ideally.
Anyways thanks for your effort, please wait for others to review.

**Comment by YashKumarVerma** [comment]
Anyone there?

**Review by isuruAb — COMMENTED** [review]
@YashKumarVerma  please resolve conflicts.

**Comment by YashKumarVerma** [comment]
@anshumanv  @isuruAb 

I have my preboards these days  (tomorrow of maths 😉  )
so i'll be doing the same tomorrow 😄

**Comment by ParthS007** [comment]
Please update this PR. @YashKumarVerma

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@YashKumarVerma Please Resolve Conflicts

**Review by ParthS007 — COMMENTED** [review]
@YashKumarVerma  Please update your PR or close this PR if it's not needed 👍

**Comment by ParthS007** [comment]
closing this PR due to inactivity 👍

**Comment by YashKumarVerma** [comment]
@ParthS007 
sorry for not closing it by myself. 
the required mojo was done in https://github.com/fossasia/gci17.fossasia.org/pull/126

**Pull request closed without merging**
