### PR TITLE
Added my blog

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please squash your commits.
Otherwise LGTM!

**Comment by samyakbvs** [comment]
I am not able to do it IDK why my terminal is not recognising the repo

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
squash commits please

**Comment by samyakbvs** [comment]
Done

**Review by nikit19 — APPROVED** [review]

**Comment by nikit19** [comment]
@samyakbvs well done :+1:

**Comment by samyakbvs** [comment]
Can you merge @nikit19

**Comment by samyakbvs** [comment]
Thanks btw

**Review by akshatnitd — COMMENTED** [review]
@samyakbvs Please provide the deployment link,so that I can merge it

**Comment by samyakbvs** [comment]
Sure

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/blog-gci17.fossasia.org/

**Comment by samyakbvs** [comment]
@akshatnitd

**Review by akshatnitd — APPROVED** [review]
Great ! Merging :rocket:

**Comment by samyakbvs** [comment]
Thanks

**Comment by samyakbvs** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5594412685983744/ pls approve this @akshatnitd

**Pull request merged**
