### PR TITLE
Grouped social media icons

### LINKED ISSUE #976: Group Social Media Icons
The social media icons on the top menu take up more space than they should take.

Please group the social media icons and reduce the space between them.

screenshot from 2018-02-09 12-55-31

### PR DESCRIPTION
**Pull request by ankurg22**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showing after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
- Previously Social media in header were taking lots of space, so made a dedicated drop-down for them named as `Connect`
- https://ankurg22.github.io/gci17.fossasia.org/
- Fixes #976

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@ankurg22  You have to only reduce space between the icons.

**Comment by ankurg22** [comment]
@ParthS007 Made the changes please review.

**Review by rupav — APPROVED** [review]
LGTM

**Comment by rupav** [comment]
@ParthS007 its good now, squash and merge this.

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
