### PR TITLE
Fixed #255: Added names && Blog

### LINKED ISSUE #255: Add Favicon
### Expected results
We should have a favicon

### Actual results
No favicon on Chrome 62.0.3202.94, Windows 10

image

## Would you like to work on this
No

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/kaymas-gci17.fossasia.org/

**Comment by harshit98** [comment]
@samyakbvs I'm not able to understand the PR. Where are the names you've added?

**Comment by samyakbvs** [comment]
screen shot 2017-12-24 at 6 52 22 pm

**Comment by samyakbvs** [comment]
screen shot 2017-12-24 at 6 52 16 pm

**Comment by abishekvashok** [comment]
Please add it to the bottom. Provide a nice description as well.

**Comment by samyakbvs** [comment]
I don't know why I am not able to do that

**Comment by samyakbvs** [comment]
Can you just how to do that

**Comment by samyakbvs** [comment]
Or is it good  like this? @harshit98

**Comment by abishekvashok** [comment]
See the student section as an example.

**Comment by samyakbvs** [comment]
I won't be able to squash the commits for blog as they aren't showing up in terminal

**Comment by samyakbvs** [comment]
closing this PR making a new one

**Pull request closed without merging**
