### PR TITLE
Scale top left logo and add my blog article Solves #218

### PR DESCRIPTION
**Pull request by kubami9**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

Scale top left FOSSASIA logo to the size from fossasia.org and add my blog article
This solves issue #218 

Preview link: https://kubami9.github.io/GCI17-kubamichalski/

### CODE REVIEW

**Comment by anshumanv** [comment]
What changes have been made to `img/blog/IMG_0020.JPG` since it's appearing in files changed.

**Comment by kubami9** [comment]
Yeah, that's my problem for few days. Whenever I fork FOSSASIA GCI 2017 repo this change automatically shows event though I do not touch this file. I forked this repo more than 5 times and every time this change appears :( I promise no changes were made to this file. It also appeared in my last PR but it had no impact on the website .

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by kubami9** [comment]
Thank you! :)

**Comment by anshumanv** [comment]
Nice work @kubami9  :smile:

**Pull request merged**
