### PR TITLE
Removed Google +

### PR DESCRIPTION
**Pull request by NishithP2004**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Removed Google + which is extinct now.
- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by abishekvashok — APPROVED** [review]
Ready to go

**Comment by NishithP2004** [comment]
@abishekvashok Could you please merge

**Comment by NishithP2004** [comment]
@prateekj117 Please review

**Comment by NishithP2004** [comment]
Please also review my PRs on gci18,16,15 &14 sites

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
