### PR TITLE
Made changes and developed website

### PR DESCRIPTION
**Pull request by saarthakchats**
Changed two buttons, added a new button feature in the blog section. Added social links to a few missing places.

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please don't change the image, changes should only be in index.html

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Update your fork so that the image change should not be there

**Comment by saarthakchats** [comment]
The image is not actually changed. It's the same. I had opened the image to check its dimensions and when I hit close it saved it without any changes. That is why it is in the changed files but it is unchanged.

**Comment by saarthakchats** [comment]
Fine, I made a new PR.
fossasia/gci17.fossasia.org#195
I have only changed the picture in that. Please merge that.

**Pull request closed without merging**
