### PR TITLE
Add mentor

### PR DESCRIPTION
**Pull request by kubami9**
Add mentor Mohit Sharma

### CODE REVIEW

**Comment by ParthS007** [comment]
Good work @kubami9 . Can you please provide the preview link just like you have done in the previous PR.

**Review by ParthS007 — APPROVED** [review]
LGTM !

**Comment by kubami9** [comment]
Here it is:
https://kubami9.github.io/kubamichalski-gci-changes/

**Comment by ParthS007** [comment]
@kubami9 Can you please align the last row as there are more mentors to be added so please shift the last row of mentors to left to make it just like above rows and If you increase the size of Mario's picture it will be a plus :grinning:

**Comment by kubami9** [comment]
Sure 😃

**Comment by kubami9** [comment]
I checked and the row automatically aligns as the previous rows when you add more mentors. I also replaced Mario image with 240x240px version. Create next pull request?

**Comment by ParthS007** [comment]
Good Work ! @kubami9  Keep it up

**Review by abishekvashok — APPROVED** [review]

**Comment by kubami9** [comment]
Thank you! 😆

**Comment by ParthS007** [comment]
@kubami9 Please submit your task

**Pull request merged**
