### PR TITLE
Fixes #655 :Added Lokinder Singh's image

### LINKED ISSUE #655: Lokinder Singh's image not available/not showing
### Expected results
All images showing
### Actual results
Lokinder Singh's image not showing
### Steps to reproduce the issue
Fix the problem
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Have added Lokinder Singh's image and linked it.
[Deploy Link](https://saarthakchats.github.io/LetsGoToTheMall/)
- Fixes #655 

# What it looked like
screenshot 12

# What it looks like now
screenshot 13

### CODE REVIEW

**Comment by codedsun** [comment]
@saarthakchats Image size 240*240

**Comment by saarthakchats** [comment]
@codesun Done! See now

**Comment by saarthakchats** [comment]
@codedsun Can you please approve.

**Comment by codedsun** [comment]
@saarthakchats Let the travis pass complete and I am ready to approve and merge. 👍

**Comment by saarthakchats** [comment]
Ok sure. Thanks

**Comment by saarthakchats** [comment]
@codedsun 
It passed

**Review by codedsun — APPROVED** [review]

**Comment by saarthakchats** [comment]
Thanks Suneet

**Comment by ghost** [comment]
hye i want to change my photo to my current profile photo
can i do so please

**Pull request merged**
