### PR TITLE
Akshat Garg mentor profile

### PR DESCRIPTION
**Pull request by AkshatJain1**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- added akshat garg information in mentor section(github, blog, twitter, linkedin, latitude+longitude)
- put 240x240 image "agarg.jpg" in img/mentor
- screenshot: 
agargmentorprofile

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Please complete only one task in one PR, provide a deployment link as well.

**Review by dilpreetsio — APPROVED** [review]

**Review by nikit19 — APPROVED** [review]

**Review by vaibhavsingh97 — APPROVED** [review]

**Comment by vaibhavsingh97** [comment]
please provide deployment link before final merge

**Comment by AkshatJain1** [comment]
Deployment Link: https://akshatjain1.github.io/fossasiafork/mentors

I will keep in mind to complete one task in each PR in the future!

**Review by akshatnitd — APPROVED** [review]
Great work ! Please make sure to make separate PRs for different tasks/issues from next time. Cheers :1st_place_medal:

**Pull request merged**
