### PR TITLE
Image for my blog..

### PR DESCRIPTION
**Pull request by pmsbir**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Looks good just delete the other image that you have uploaded. You should upload just one image. And it should be in the img/blog folder. Please remove conflicts as well

**Review by isuruAb — CHANGES_REQUESTED** [review]
Please squash your commits and resolve conflicts and upload a 240x240 sized image

**Comment by harshit98** [comment]
- Remove this image: `share686533663.jpg`
- Image size should be 240 x 240.
- Resolve conflicts.

**Comment by pmsbir** [comment]
Which commits are to be squashed....

**Comment by pmsbir** [comment]
What exactly should I do...
I have already uploaded an image of 240×240

**Comment by pmsbir** [comment]
I have already added an image of 240×240

**Comment by pmsbir** [comment]
Please merge my pull request quickly so that I can submit my Google Code-in task for review.

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please remove the second image it is causing the travis fail

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Let's keep a single image.

**Comment by pmsbir** [comment]
Sir, when I went to delete the other image in commit- Added an image of author on my blog, they show this message..
You must be on branch to make proposed changes on file.
How should I delete it??

**Comment by pmsbir** [comment]
Please reply..

**Comment by harshit98** [comment]
@pmsbir I would suggest you these steps:
- Create a new branch.
- Make sure it's updated. You can find useful resources on Google related to it: "How to update a branch using git"
- Do the changes. Make sure this time, you upload only 1 image. That 1 image should not be landscape or scenery. It should be of student itself who has written the blog.
- Create a fresh PR.

I'm closing this PR. Good luck! Let me know if you've less time left to complete the task. Share your task link here or any channel of FOSSASIA on gitter and you can request mentors to extend the deadline.

**Pull request closed without merging**
