### PR TITLE
Added my information

### PR DESCRIPTION
**Pull request by divitsolanki**
Added my information and image in section - **Students just like you**.

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please add this image divit.jpeg in the img/students folder and you are done :+1:

**Comment by divitsolanki** [comment]
Showing Error
File uploads require **push access** to this repository.

**Comment by nikit19** [comment]
@divitsolanki upload the file in your own forked repository

**Comment by divitsolanki** [comment]
image uploaded in my forked repository

**Comment by nikit19** [comment]
You must have uploaded it in a different branch. That is why those changes aren't reflected here.
Make sure you upload it in the same branch from which you made this pull request.

**Comment by divitsolanki** [comment]
created new request

**Pull request closed without merging**
