### PR TITLE
Learn Tab

### PR DESCRIPTION
**Pull request by ghost**
People can learn more about coding in varios laguages with very good resources and links and info on fossasia - by Arjun Bhorkar

### CODE REVIEW

**Comment by mariobehling** [comment]
Hi @BOKOBOT9 It looks like you added another file index1.html. Please add your changes to the index.html file and avoid adding more html files. This will make it easier to review. Thank you!

**Comment by ghost** [comment]
hey edited my pull request merged it all in one page check it out

**Comment by SaptakS** [comment]
Please stash all the commits as most of them represent same work... Try to make all the commits into one.. try this https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by ghost** [comment]
Wait i will make a new pull request

**Comment by SaptakS** [comment]
What I meant was squash just to make myself clear.. Sorry for the mistake..

**Pull request closed without merging**
