### PR TITLE
Fixed #518 : Restored the contributors section

### LINKED ISSUE #518: Restore the contributors section
The contributor's section has been damaged it has to be restored the way it was
I am working on it, please don't take up this without my consent

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/restoration-gci17.fossasia.org/

**Comment by anshumanv** [comment]
preview link doesn't work.

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/git-gci17.fossasia.org/
@anshumanv

**Review by ParthS007 — APPROVED** [review]
LGTM !

**Comment by anshumanv** [comment]
Not working for me still.

**Comment by samyakbvs** [comment]
closing this one and opening a new one

**Pull request closed without merging**
