### PR TITLE
Update footer.html (Added a text to notify users about the Social Link section)

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Queen.gci17.fossasia.org/ --> preview link !!

**Comment by abishekvashok** [comment]
Is this needed. If yes then it looks good :)

**Comment by yashk0thari** [comment]
it wont hurt to add it; navigation galore :D

**Comment by abishekvashok** [comment]
Sure :D

**Comment by yashk0thari** [comment]
kk; so can we merge ??

**Comment by abishekvashok** [comment]
@Beta-King let's wait for reviews.

**Comment by yashk0thari** [comment]
ohkk 👍

**Review by nzec — CHANGES_REQUESTED** [review]
Not needed.

**Comment by yashk0thari** [comment]
Ohk; was a longshot anyways :D lols

**Pull request closed without merging**
