### PR TITLE
Fixed Issue#741

### LINKED ISSUE #741: `Thanks for contributing` section not working
There's a blank black-coloured section on the homepage. I did an inspect element and found that it had an 
`<h2> element` with some strings entered in the `data-rotate attribute`. It seems there's some Javascript/JQuery plugin which is either not included or not working.

### Steps to reproduce the issue
Open the site and scroll down until you see a black section with no content.
## I would love to work on this if I'm provided with either the plugin's name, or if I'm allowed to use a different plugin to get the same effect of typing and deletion.

### PR DESCRIPTION
**Pull request by aryan-02**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Preview link: https://aryan-02.github.io/fossasiagci/
- Fixes #741

Earlier, there was a black section in the site, without any content. I noticed that it was an incomplete text-typing effect. I fixed it by linking the JavaScript correctly using a plugin called "Typed.js"

### CODE REVIEW

**Comment by aryan-02** [comment]
@0x48piraj Finally I learnt how to squash commits properly :)

**Comment by aryan-02** [comment]
Okay, now this is safe to merge.

**Comment by vaibhavsingh97** [comment]
@aryan-02 Your PR has conflicts. PLease fix it and update your PR

**Comment by aryan-02** [comment]
Okay, how do I fix conflicts?

**Comment by aryan-02** [comment]
I mean, they weren't there when I made the PR

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Resolve conflicts and get your PR merged :tada:

**Comment by aryan-02** [comment]
Resolved the conflict

**Comment by aryan-02** [comment]
Let me squash the commits again

**Comment by aryan-02** [comment]
I'm not sure why, I can't squash these commits, however three commits shouldn't be bad, right?

**Comment by realslimshanky** [comment]
@aryan-02 you can squash all 4 into 1. Just do a soft reset to `HEAD~3` and create a new commit.

**Comment by nzec** [comment]
@aryan-02 I would recommend a  little bit less speed. Otherwise, it looks awesome! 👍

**Review by akshatnitd — CHANGES_REQUESTED** [review]
I can see many unwanted changes have also come in this PR. Please rebase properly :)

**Comment by aryan-02** [comment]
Done

**Comment by aryan-02** [comment]
Squashed the commits

**Comment by aryan-02** [comment]
Please review and merge :)

**Review by akshatnitd — CHANGES_REQUESTED** [review]
The PR is not rebased properly and I can still see changes from other PRs.

**Comment by realslimshanky** [comment]
@aryan-02 this issue will be fixed by #725 and will work properly. Check out the result here https://realslimshanky.github.io/gci17fossasia

**Review by ParthS007 — COMMENTED** [review]
Good work @aryan-02  but as your PR has some previous commits also so I would suggest to close this PR and update your clone and local repo and then make a fresh PR.I hope you understand. 👍

**Comment by aryan-02** [comment]
Okay, let's do it once again

**Pull request closed without merging**
