### PR TITLE
Make the drop down menu red on scroll over same as fossasia.org

### LINKED ISSUE #213: Make the drop down menu red on scroll over same as fossasia.org
The scroll down item that is on "scroll over" should be red same as on http://fossasia.org

screenshot from 2017-12-09 18-37-43

### PR DESCRIPTION
**Pull request by ryushar**
**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Make the drop down menu red on scroll over same as fossasia.org (#Fixes #213 )
-Made the design of the top menu bar similar to the one at fossasia.org
screenshot from 2017-12-12 13-54-44
screenshot from 2017-12-12 13-55-22
-Live Demo : http://2coolife.github.io/gci17.fossasia.org

### CODE REVIEW

**Comment by anshumanv** [comment]
The red highlighting works but the position of the FOSSASIA logo in the left of nav is not correct please see. Thanks!

**Review by anshumanv — CHANGES_REQUESTED** [review]
Fix logo positioning.

**Comment by ryushar** [comment]
@anshumanv i made some changes, please have a look :smile:

**Comment by anshumanv** [comment]
Thanks @2coolife :smile:

**Review by anshumanv — APPROVED** [review]

**Comment by ParthS007** [comment]
@anshumanv  red on scroll over is added already in #229  and its working fine so why It is added here again . Please let me know if I am missing something .

**Comment by ryushar** [comment]
@ParthS007 The issue(#213 ) said it should be similar to the one at [fossasia.org](https://fossasia.org/) :sweat_smile:

**Comment by abishekvashok** [comment]
I think it was solved.

**Comment by anshumanv** [comment]
Yes, @ParthS007 it is solved partially, and it's working in firefox for me and not in Chrome(Version 62.0.3202.94 (Official Build) (64-bit).
This was raised by @ms10398 too I think.
Can you please confirm @ms10398 ?

**Comment by the-codingninja** [comment]
Yes its working now

**Comment by anshumanv** [comment]
Thanks for confirming, no issues then if its working for you all. :smile:

**Comment by the-codingninja** [comment]
Sorry but as the work was finished in some other PR
Then you but have to close it

**Pull request closed without merging**
