### PR TITLE
Added my blog

### PR DESCRIPTION
**Pull request by Devansh1234**
Updated necessary files
<a href="https://devansh1234.github.io/gci17.fossasia16098.org/">Deploy</a>

### CODE REVIEW

**Review by rupav — COMMENTED** [review]
Good job. Did you use git to send the PR? Can you squash your commits from 2 to 1?

**Review by anshumanv — COMMENTED** [review]
LGTM, please try squashing.

**Review by nikit19 — APPROVED** [review]
Since it is your first PR it is okay if the commits are not squashed but make sure you do it from next time :+1:

**Review by rupav — APPROVED** [review]
Agreed with @nikit19 . Wait for travis check to merge.

**Comment by anshumanv** [comment]
@rupav @nikit19 I think there's some problem with travis, it hasn't completed the build since quite long, any ideas?

**Comment by rupav** [comment]
@anshumanv true, this too https://github.com/fossasia/gci17.fossasia.org/pull/924.

**Comment by Devansh1234** [comment]
It says Travis CI build is in progress, what do I do?

**Pull request merged**
