### PR TITLE
Please update the following

### PR DESCRIPTION
**Pull request by Mridulbirla13**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- A task of GCI-17.
- Added the profile information of mentor (Pratyush Singh) in mentor.yml section.
- Added the image of mentor (Pratyush Singh) in img/mentor section.
- Here is my live link :  https://codein.withgoogle.com/dashboard/task-instances/4669383198638080/

### CODE REVIEW

**Comment by Mridulbirla13** [comment]
Please help me in squashing the commits.

**Comment by nzec** [comment]
@Mridulbirla13 I followed this to squash the commits : http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Review by nikit19 — COMMENTED** [review]
Your preview link is `your-username.github.io/name-of-repo`
and this might help you to squash your commits
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Review by nzec — COMMENTED** [review]
Don't write names of images with spaces between them. Have something like : `pratyush.jpg`

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@Mridulbirla13 Please do the suggested changes and update your PR 👍

**Comment by Mridulbirla13** [comment]
I am having this error. Please help! 
rebase error

**Comment by harshit98** [comment]
I'm closing this PR @Mridulbirla13. Please create a fresh PR with the changes done. Also, change the image name to `pratyush.jpg`.

**Comment by harshit98** [comment]
Basically, you're getting this error because no default text editor has been defined. Once you define a default text-editor, no such errors will occur. 

But I would suggest creating a fresh PR with the changes. Good luck!

**Pull request closed without merging**
