### PR TITLE
Added mentor, made necessary code changes....

### PR DESCRIPTION
**Pull request by yashk0thari**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added mentor pic
- Made necessary code changes

### CODE REVIEW

**Comment by yashk0thari** [comment]
if there are no conflicts, then plz merge !! or tell me what needs to be done ??

**Comment by yashk0thari** [comment]
What live link do i need to provide ?? if any...

**Review by ParthS007 — COMMENTED** [review]
@Beta-King  You have to provide a preview link and else looks good to me 👍

**Comment by yashk0thari** [comment]
Here, https://beta-king.github.io/Beta-King.fossasia.org/

**Comment by yashk0thari** [comment]
Done !!

**Comment by ParthS007** [comment]
@Beta-King  Page gives `404` error , please resolve it

**Comment by supunTE** [comment]
please add a description about PR

**Comment by yashk0thari** [comment]
ohk wait...

**Comment by supunTE** [comment]
And give a correct preview link. Please search it on Google, If you're don't know that thing.

**Comment by yashk0thari** [comment]
Resolved it, plz check the link again, it is accessable now...

**Review by ParthS007 — APPROVED** [review]

**Comment by ParthS007** [comment]
@Beta-King  Please squash commits from next time 👍

**Comment by yashk0thari** [comment]
ohk, will do :D

**Comment by yashk0thari** [comment]
Thx

**Pull request merged**
