### PR TITLE
Added my info and resolved issue #568 

### PR DESCRIPTION
**Pull request by divitsolanki**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

- Fixes`#568`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
LGTM but somebody is already working on issue #568 so remove that part and rest looks good :+1:

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@divitsolanki  Please resolve Travis error

**Review by isuruAb — COMMENTED** [review]
please resolve travis failure.  and resolve conflicts

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash your commits.

**Comment by harshit98** [comment]
I'm closing this PR @divitsolanki due to no activity. 

You can still do the changes. Once the changes are pushed in the branch, feel free to reopen the pull request. Mentors will review it.

**Pull request closed without merging**
