### PR TITLE
Update blogs.html

### PR DESCRIPTION
**Pull request by arjunloomba1311**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- added adequate image and all details required

### CODE REVIEW

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please fix travis and add a image for the blog

**Comment by supunTE** [comment]
**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!

You may check them after opening your pull request.**
If you're finish a point please check it.

ex:-
- [ ] Included a description of my change below
_like this_
- [x]  Included a description of my change below

**Comment by supunTE** [comment]
And type your change description there,

# Things done in this Pull Request
  -  Replace this with your change description

**Comment by the-codingninja** [comment]
Please fix travis

**Review by akshatnitd — CHANGES_REQUESTED** [review]
The image size should be 240*240px. Please make the change. Also, squash the commits.

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please resolve conflicts and image is still not 240*240

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please remove the extra image

**Comment by harshit98** [comment]
Hi @arjunloomba1311. If you check, you're removing someone else blog as well. May I know why?

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
