### PR TITLE
@0x48piraj: Added another blog

### PR DESCRIPTION
**Pull request by 0x48piraj**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Added Blog

### CODE REVIEW

**Review by the-codingninja — APPROVED** [review]

**Review by rupav — COMMENTED** [review]
You brought your data to the top in _data/students.yml . Please see to it, you dont need to modify this file, since you are already added in this section.

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Please revert the changes @rupav pointed.

**Comment by 0x48piraj** [comment]
I just updated my GPS co-ords. :+1:

**Comment by mariobehling** [comment]
0x48piraj_susi.jpg is scaled wrongly and distorting the SUSI.AI logo.

**Pull request merged**
