### PR TITLE
added a blog 

### PR DESCRIPTION
**Pull request by supunTE**
I added a blog to the site that shows my experiences on GCI-FOSSASIA and open source.
https://morethanworld64569539.wordpress.com/2017/12/06/google-code-in-and-open-source/

### CODE REVIEW

**Review by scandindian — CHANGES_REQUESTED** [review]
Your blog looks very nice but it seems like you have modified some other parts too. There are many lines deleted and added to your pull request however it should only reflect the changes that you made. 

- Avoid auto indentation
- Only modify your part in the file

**Comment by supunTE** [comment]
How am I change now?

**Comment by supunTE** [comment]
OK?

**Comment by scandindian** [comment]
@STEdirisuriya You can see your files changed here https://github.com/fossasia/gci17.fossasia.org/pull/167/files . 

Did you intentionally modify all the text marked in red and green?

See other student's pull request https://github.com/fossasia/gci17.fossasia.org/pull/144 for help where only a few lines are added.

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@STEdirisuriya  Please see previous PRs where contributors have added the blog. You have to update only your blog links in index.html.Please ask if you have any doubt.

**Comment by supunTE** [comment]
I'll resolve all conflicts soon

**Pull request closed without merging**
