### PR TITLE
Please update the following 

### PR DESCRIPTION
**Pull request by Mridulbirla13**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- A GCI-2017 task
- Added my profile information in Students.yml
- Added my image in the img/students section
- My live link is https://codein.withgoogle.com/dashboard/task-instances/5813642547167232/

### CODE REVIEW

**Comment by Mridulbirla13** [comment]
Sir, but the image is 240*240.
file
If any other error, then please guide me.

**Review by anshumanv — CHANGES_REQUESTED** [review]
Fix travis by resizing the image.

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Resize image to fix travis

**Comment by anshumanv** [comment]
@abishekvashok can you see what's wrong with his image?

**Comment by nzec** [comment]
@anshumanv @ms10398  The image indeed is 240x240px. The real problem is that he has written the Twitter address with an `@` symbol.

The Travis Log says this clearly : 
```
jekyll 3.6.2 | Error:  (/home/travis/build/fossasia/gci17.fossasia.org/_data/students.yml): found character that cannot start any token while scanning for the next token at line 177 column 12
````

Please remove the `@` symbol @Mridulbirla13 !

**Comment by abishekvashok** [comment]
@anshumanv sorry for the late response.
The problems is the same as @duttaditya18 reported. Really sorry for being late.

**Comment by abishekvashok** [comment]
#326 or this one?

**Comment by anshumanv** [comment]
Thanks @duttaditya18 @abishekvashok :+1:

**Comment by ParthS007** [comment]
closing it duplicate of #326

**Pull request closed without merging**
