### PR TITLE
Add my avatar to the website

### PR DESCRIPTION
**Pull request by m1guelpf**
Hi everyone!
This PR will add my avatar to the website.

Preview link: https://m1guelpf-forks.github.io/gci17.fossasia.org

Note:
- We should probably use something like jekyll like last year, we don't want everyone editing index.html, causing conflicts, etc. (Opened issue #38).

:octocat:

### CODE REVIEW

**Review by jigyasa-grover — APPROVED** [review]
You know the drill:
- Squash the commits
- Rename it, a meaningful message "Adding <yourname> avatar"

**Comment by m1guelpf** [comment]
@jigyasa-grover Done!

**Review by jigyasa-grover — APPROVED** [review]

**Comment by jigyasa-grover** [comment]
@m1guelpf  Thanks !

> We should probably use something like jekyll like last year, we don't want everyone editing index.html, causing conflicts, etc. (Opened issue #38).

@mariobehling Reviews pls ?

**Review by daminisatya — APPROVED** [review]

**Review by abhinavk96 — APPROVED** [review]

**Comment by abhinavk96** [comment]
@mariobehling Please merge this

**Comment by rishiraj824** [comment]
@m1guelpf Please resolve conflicts. Thanks!

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Merge Conflicts

**Comment by m1guelpf** [comment]
Done!

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
