### PR TITLE
Added a Promotional Video !! 

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/rashtrapatqgci17.fossasia.org/ --> Preview Link :D

**Comment by yashk0thari** [comment]
@harshit98 made new PR -- is there a problem with the Travis -- this PR shouldnt fail but idk -- the travis is failing in many areas, Labyrinth being one of them...

**Comment by yashk0thari** [comment]
please review and merge :D

**Comment by samyakbvs** [comment]
Are you allowed to use a song without license

**Comment by samyakbvs** [comment]
@Beta-King

**Comment by yashk0thari** [comment]
ohk removing that then :D

**Comment by yashk0thari** [comment]
Work in progress...

**Comment by yashk0thari** [comment]
Can we approve and merge now ??

**Comment by yashk0thari** [comment]
@samyakbvs made changes :D

**Comment by yashk0thari** [comment]
The Travis has passed -- can we merge now ??

**Review by vaibhavsingh97 — APPROVED** [review]

**Review by nikit19 — APPROVED** [review]

**Comment by yashk0thari** [comment]
Can we merge ?? :D

**Comment by rupav** [comment]
Good Work !!

**Comment by yashk0thari** [comment]
Thank you :D

**Pull request merged**
