### PR TITLE
Fixes js console error

### LINKED ISSUE #678: Resolve all the console errors.
### Expected results

No console errors should be present when gci17.fossasia.org is visited.

### Actual results

A lot of console errors are coming up when gci17.fossasia.org is visited.

Here are some screenshots:

screen shot 2017-12-31 at 5 08 16 pm
screen shot 2017-12-31 at 5 08 40 pm

### PR DESCRIPTION
**Pull request by realslimshanky**
Most of the js console error and warnings which
were shown earlier has been fixed by this commit.

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- Please checkout this link to test the changes. https://realslimshanky.github.io/gci17fossasia/
- Fixes #678 

# Changes which cannot be fixed

- OpenLayers/OpenStreetMap API is sending images for the map using HTTP which is needed to be dealt with in a different issue altogether.

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
still there are lot of errors on the console. please check again

**Comment by realslimshanky** [comment]
@isuruAb most of them are warnings due to either browser's tracking protection or from an open street maps api which needs a separate issue for discussion.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Why left the unused local file named `jquery.min.js`

Also, using external domains, slows down the website :smile:

**Comment by realslimshanky** [comment]
@0x48piraj good point. Let me check for dead files and remove it.

**Comment by harshit98** [comment]
@realslimshanky The open street API errors can also be improved. I mean, try to find the link related to it. Check what can be done. See if it can be served in HTTPS.

**Comment by realslimshanky** [comment]
@harshit98 I tried reading through OpenLayers and OpenStreetsAPI. I'll be needing help with the person who initially put that code, I tried git blame but it seems messed up. Any change on the maps would bring about a change in entire API.

**Review by sansyrox — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Comment by realslimshanky** [comment]
@stealthanthrax, the conflict has been resolved.
cc: @0x48piraj

**Review by ParthS007 — APPROVED** [review]
LGTM ! Thanks for the PR

**Review by isuruAb — COMMENTED** [review]
please squash your commits.

**Comment by realslimshanky** [comment]
@isuruAb I cannot squash these commits since they are not continuous in history.

**Pull request merged**
