### PR TITLE
Students photo

### PR DESCRIPTION
**Pull request by AKostiv8**
I have changed the way of adding students photo, also I have made the student's image size as required,  but unfortunately didn't find students links in social networks

### CODE REVIEW

**Comment by NaviRocker** [comment]
Solve the Conflicts and Preview link Please.

**Review by isuruAb — CHANGES_REQUESTED** [review]
please resolve conflicts and squash your 5 commits.
follow this tutorial to squash your commits.
https://www.youtube.com/watch?v=vp7-NeURmFg&t=35s

**Comment by AKostiv8** [comment]
@isuruAb I have resolved conflicts)))

**Comment by isuruAb** [comment]
@AKostiv8  nice. did you try to squash these 9 commits  ?

**Comment by ParthS007** [comment]
@AKostiv8 Can you please provide a preview link ?

**Pull request closed without merging**
