### PR TITLE
Add Student profile

### PR DESCRIPTION
**Pull request by Ploypiti**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Add my photo to the GCI FOSSASIA Site Student Section
- Fill in the details including Github, Twitter, country, etc.
- Connect with Projects on GitHub

### CODE REVIEW

**Comment by abishekvashok** [comment]
@Ploypiti please change the img dimensions to 240x240px

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Make image dimensions correct

**Review by abishekvashok — APPROVED** [review]
LGTM

**Comment by abishekvashok** [comment]
Would be better if you could squash the commits though @Ploypiti

**Comment by Ploypiti** [comment]
Sorry, but how do I do that? (I'm pretty new to this)

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Please squash the commits :) Refer https://gist.github.com/patik/b8a9dc5cd356f9f6f980 for help

**Comment by abishekvashok** [comment]
@Ploypiti learn it here: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by Ploypiti** [comment]
@akshatnitd 

I entered git checkout master && git pull
**fatal: Not a git repository (or any of the parent directories): .git**, is there any way to do this without cmd? or how do I solve this?

**Comment by Ploypiti** [comment]
Hmm Do I need to clone the repo

**Comment by Ploypiti** [comment]
C:\Users\P10YP1T1\gci17.fossasia.org>git merge feature_branch
merge: feature_branch - not something we can merge

C:\Users\P10YP1T1\gci17.fossasia.org>git reset origin/gh-pages
Unstaged changes after reset:
M       img/blog/IMG_0020.JPG

C:\Users\P10YP1T1\gci17.fossasia.org>git add . --all

C:\Users\P10YP1T1\gci17.fossasia.org>git commit
On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.

Changes not staged for commit:
        modified:   img/blog/IMG_0020.JPG

no changes added to commit

**Comment by akshatnitd** [comment]
@Ploypiti Yes, you need to do it inside a git repo. First change the directory to the repo directory from terminal and then follow the steps in the link. If you have not cloned the repo, go ahead and clone it.

**Comment by Ploypiti** [comment]
What does it mean by _not something we can merge_ and _changes not staged for commit?_

**Comment by akshatnitd** [comment]
The error log ```not something we can merge``` is being shown because branch named ```feature_branch``` doesn't exist

**Comment by Ploypiti** [comment]
what branch name should I use, gh-pages?

**Comment by akshatnitd** [comment]
@Ploypiti Yes
The link I shared was a generic guideline. You need to change names where required.

**Comment by Ploypiti** [comment]
Ok, thanks. Is this what should happen
```
C:\Users\P10YP1T1\gci17.fossasia.org>git commit
On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.

Changes not staged for commit:
        modified:   img/blog/IMG_0020.JPG

no changes added to commit
```

**Comment by akshatnitd** [comment]
@Ploypiti Can you send the output of ```git log --oneline``` ?

**Comment by Ploypiti** [comment]
Basically a bunch of issue or PR list (I'm not sure)

**Comment by akshatnitd** [comment]
Send 10 lines from the top of the output

**Comment by Ploypiti** [comment]
I can't mark & copy the result...I'll try to type or send a screenshot instead?

**Comment by akshatnitd** [comment]
Yes, screenshot would be fine

**Comment by Ploypiti** [comment]
https://ibb.co/kbMS2w

**Comment by akshatnitd** [comment]
@Ploypiti You have cloned the FOSSASIA's ```gci.fossasia.org``` repo. You need to clone the fork of the repo, i.e, ```git clone https://github.com/Ploypiti/gci.fossasia.ploypiti.git```

I would suggest you to move to gitter, as more devs would be there to help :)

**Comment by harshit98** [comment]
Hi. @Ploypiti 
The pull request looks good to me. No need to squash commits if you're facing difficulties at present. Can you provide me the working demo link of it, so that I can preview the changes? : )

**Comment by Ploypiti** [comment]
@harshit98 Thanks, https://ploypiti.github.io/gci.fossasia.ploypiti/students 
@akshatnitd However I did it anyway, here's the screenshot https://ibb.co/eyXT9b

**Review by harshit98 — APPROVED** [review]

**Comment by akshatnitd** [comment]
@Ploypiti Great! You can try squashing the commits from next task.

**Pull request merged**
