### PR TITLE
Fixes #582 : Small Fix: 2018 Summit link was added twice

### LINKED ISSUE #582: 2018 summit link added twice
### Expected results
All links added once
### Actual results
2018 summit link added twice
### Steps to reproduce the issue
Remove one
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #582

### CODE REVIEW

**Review by gabru-md — APPROVED** [review]

**Review by nikit19 — APPROVED** [review]

**Comment by saarthakchats** [comment]
Can we merge?

**Comment by saarthakchats** [comment]
@nikit19 @gabru-md

**Review by vaibhavsingh97 — APPROVED** [review]

**Comment by vaibhavsingh97** [comment]
@saarthakchats Please fix TravisCI too

**Comment by saarthakchats** [comment]
Its not because of my changes

**Comment by saarthakchats** [comment]
Manish said it was because of some blog addition by some other guy and will be fixed by a few other PRs

**Comment by saarthakchats** [comment]
@vaibhavsingh97 @gabru-md

**Comment by vaibhavsingh97** [comment]
@saarthakchats I know, but in a team one should take a responsibilty so can you try to fix travis ci

**Comment by vaibhavsingh97** [comment]
Error `jekyll 3.6.2 | Error:  (/home/travis/build/fossasia/gci17.fossasia.org/_data/blogs.yml): did not find expected '-' indicator while parsing a block collection at line 1 column 1`

**Comment by saarthakchats** [comment]
I tried @vaibhavsingh97. I am having trouble doing it.

**Comment by saarthakchats** [comment]
I dont really know how

**Review by akshatnitd — COMMENTED** [review]
your travis log shows this error
```
jekyll 3.6.2 | Error:  (/home/travis/build/fossasia/gci17.fossasia.org/_data/blogs.yml): did not find expected '-' indicator while parsing a block collection at line 1 column 1
```

**Comment by saarthakchats** [comment]
Can you aid in fixing travis @vaibhavsingh97

**Comment by vaibhavsingh97** [comment]
@saarthakchats This line causing error https://github.com/fossasia/gci17.fossasia.org/blob/7157f2f0485e2b313a202c9f5da15bcd74b9c46f/_data/blogs.yml#L202

**Comment by saarthakchats** [comment]
@akshatnitd I dont know how to fix it

**Comment by saarthakchats** [comment]
@vaibhavsingh97 Ok I will fix

**Comment by saarthakchats** [comment]
@vaibhavsingh97 I think I have fixed it

**Comment by saarthakchats** [comment]
@vaibhavsingh97 Can we merge now?

**Comment by nikit19** [comment]
@saarthakchats instead of deleting that code you could add a space after `-`  so that his blog will also be there and travis will also pass.

**Comment by saarthakchats** [comment]
Ok ill do it

**Comment by saarthakchats** [comment]
Did the changes

**Comment by vaibhavsingh97** [comment]
@saarthakchats Remove `:` from https://github.com/saarthakchats/gci17.fossasia.org/blob/c57015c71766baf97360cb559ed3794e1538fb96/_data/blogs.yml#L202 and add something relevant

**Pull request merged**
