### PR TITLE
Added documentation and updated FOSSASIA BG

### LINKED ISSUE #273: Add documentation for running the website locally
### Expected results
A documentation for installation and running the website locally
- [x] For installation in Windows
- [x] For installation in Linux
- [x] For installation in MacOS

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

* Added documentation for running website locally on MacOS
* Changed Fossasia is based in Asia Backgground
* Fixes #273 
* #269 11 point

**Here is the Live Link :** 
https://duttaditya18.github.io/gci17.fossasia.org/
https://github.com/duttaditya18/gci17.fossasia.org/blob/gh-pages/installation_macos.md
https://github.com/duttaditya18/gci17.fossasia.org/blob/gh-pages/README.md

---

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
Add a link for readme.md

**Review by supunTE — CHANGES_REQUESTED** [review]
Add a link of installation_macos.md for readme.md

**Comment by nzec** [comment]
@STEdirisuriya Okay done. Can you review this please?

**Review by supunTE — APPROVED** [review]
Looks fine

**Review by 0x48piraj — APPROVED** [review]
LGTM!

**Review by anshumanv — APPROVED** [review]
LGTM!

**Review by ParthS007 — APPROVED** [review]

**Comment by nzec** [comment]
@ParthS007 Thanks!

**Pull request merged**
