### PR TITLE
Fixes #972

### LINKED ISSUE #972: URGENT: Top slideshow not loading properly
The top slideshow is not loading properly. It often only loads on reload. Probable reason: The responsible JS is in the footer instead of the header. Also take out the arrows on right and left.

screenshot from 2018-02-09 11-50-01

### PR DESCRIPTION
**Pull request by yashLadha**
Signed-off-by: Yash Ladha <yashladhapankajladha123@gmail.com>

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Made the slider correct and removed arrow buttons.
- Fixes #972

### CODE REVIEW

**Comment by yashLadha** [comment]
http://yashladha.tech/gci17.fossasia.org/

**Comment by yashLadha** [comment]
Ping @mariobehling

**Review by rupav — COMMENTED** [review]
Removal of side arrows looks good to me, but it was claimed by someone else too in another issue #963. Ping @ankurg22 . #972 also mentions the problem.

**Comment by yashLadha** [comment]
It was one of the tasks in the issue, so I had done accordingly. @rupav. Is
the other guy has already sent a pr for the same.

**Comment by rupav** [comment]
Not yet @yashLadha . Yes I agreed, its written on #972 too. 👍

**Comment by ankurg22** [comment]
@yashLadha @rupav No problem. You can merge this PR. Just close the two duplicate issue along with this :+1:

**Comment by mariobehling** [comment]
Good job. Please don't make the issue into a coding format in future to enable linking and making it easier. Cheers.

**Comment by yashLadha** [comment]
Sure @mariobehling  :+1:

**Pull request merged**
