### PR TITLE
Added mentors photo and bio

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by anshumanv** [comment]
Hey, thanks for contributing. Please see - https://github.com/fossasia/gci17.fossasia.org/pull/143/files
There are 4 files changed with changes to students file(your addition) and your image which are not an intention of this pull request, there should be only 2 changed files (one with mentor image, one with mentor details).

Please explore and find a workaround, if unable, ask for help. :smile:

**Comment by samyakbvs** [comment]
can you this PR i will send anoher one

**Comment by anshumanv** [comment]
In short, there are commits of your old pull request which shouldn't be here.

**Comment by samyakbvs** [comment]
can you close this PR i will send another one

**Comment by anshumanv** [comment]
Okay, keep trying, you will get it!

**Pull request closed without merging**
