### PR TITLE
Added Google Code In logo in the Navbar

### LINKED ISSUE #490: Add the Google Code In logo in header
### Expected results
A GCI logo in the header along with the link.

### Actual results
No such thing is there.

### Steps to reproduce the issue
Add it.

### Would you like to work on this
Yes.

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

* Added Google Code In logo in the Navbar.
* Fixes #490 and the last point of #363 

***Deploy Link : https://duttaditya18.github.io/gci17.fossasia.org/***

---

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
Deploy Link?

**Comment by saarthakchats** [comment]
Please provide a preview link

**Comment by nzec** [comment]
@arjunpandey2003 @saarthakchats  Added. Oops I forgot! 😛

**Comment by arjunpandey2003** [comment]
@duttaditya18 LGTM

**Review by arjunpandey2003 — APPROVED** [review]

**Review by saarthakchats — APPROVED** [review]
LGTM

**Review by gabru-md — APPROVED** [review]

**Comment by nzec** [comment]
@gabru-md Thanks!

**Review by ParthS007 — APPROVED** [review]
LGTM !

**Pull request merged**
