### PR TITLE
Aligned the column below Pitch us

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/gci17.fossasia.org/

**Review by anshumanv — CHANGES_REQUESTED** [review]
Don't left center the whole block, image sizing is still uneven.

**Comment by samyakbvs** [comment]
Two images are not getting resized I cant understand why, even though they have the same class

**Comment by anshumanv** [comment]
You can manually set the image height and width in the img tag.

**Comment by samyakbvs** [comment]
I know that But the image tag isn't in the index, where is it

**Comment by samyakbvs** [comment]
screen shot 2017-12-12 at 8 23 03 pm
Can you pls tell me with what to replace Origin, master and feature_branch

**Comment by samyakbvs** [comment]
@anshumanv

**Comment by samyakbvs** [comment]
actually just tell me what to write instead of master

**Comment by samyakbvs** [comment]
Now i have already commited is it strill possible to squash commits

**Comment by abishekvashok** [comment]
@samyakbvs yes,
Run
`git rebase -i HEAD~3` since there are 3 commits
change the second and third pick to `squash` in the text editor that opens, save and exit the editor;
then it will come up again, clear everything and give the commit title in the first line then leave a line blank and give the commit description then save and exit.
then, `git push -f` do a force push.

**Comment by samyakbvs** [comment]
okay pls tell me whats my feature branch

**Comment by samyakbvs** [comment]
@abishekvashok

**Comment by abishekvashok** [comment]
@samyakbvs see my updated comment

**Comment by samyakbvs** [comment]
There is no updated comment @abishekvashok

**Comment by samyakbvs** [comment]
okay thanks @abishekvashok btw I did it with a different method

**Comment by samyakbvs** [comment]
some problem closing this one

**Pull request closed without merging**
