### PR TITLE
Added student name and image 

### PR DESCRIPTION
**Pull request by DotSlashTX**
Prasenjit Gautam 
image: HyperionGrey.jpg

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@FreakinBabaJi Please be specific about your PR name and If you are also adding mentor then also mention it in PR name and @invinciblycool  name is `RAHUL TIWARI`

**Comment by DotSlashTX** [comment]
Actually First I added myself , then I added Rahul Tiwari but at that time
I was working on Add Mentor task . I made the PR at that time for that task
but now I am on Add student task . I asked a mentor that if I submit the
link of that same old PR , will it be accepted? And his answer was that yes
it will be .

**Comment by dilpreetsio** [comment]
@FreakinBabaJi Please remove the conflicts in mentors.yml file

**Comment by ParthS007** [comment]
@FreakinBabaJi  Please resolve conflict and change name of mentor to `RAHUL TYAGI` from   `RAHUL TIWARI`

**Comment by akshatnitd** [comment]
@FreakinBabaJi There still are conflicts. Please resolve them :)

**Pull request closed without merging**
