### PR TITLE
Fixed #709: Added vatsal's image

### LINKED ISSUE #709: Vatsal Jain
He is a GCI participant but his image isn't added
Working on it

### PR DESCRIPTION
**Pull request by samyakbvs**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Added Vatsal's image
- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**) https://samyakbvs.github.io/double-gci17.fossasia.org/students
- Fixes #<Issue no.>709

### CODE REVIEW

**Review by nikit19 — COMMENTED** [review]
Is he a GCI participant? 
If yes don't you think he should add his details himself ?

**Comment by samyakbvs** [comment]
He was active earlier but now he isn't

**Comment by samyakbvs** [comment]
@nikit19

**Comment by nikit19** [comment]
Github link ? And that twitter id doesn't exist

**Comment by harshit98** [comment]
@nikit19 Yes. He is a GCI participant and he was active earlier.

@samyakbvs I think it's better he should add his image himself.

**Comment by samyakbvs** [comment]
Okay no problem

**Pull request closed without merging**
