### PR TITLE
Change Facebook link

### PR DESCRIPTION
**Pull request by Ploypiti**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Replace `student.github` with `student.facebook`
- Issue #288

### CODE REVIEW

**Comment by anshumanv** [comment]
I think I changed those in this commit https://github.com/fossasia/gci17.fossasia.org/commit/7171d8e5c43403bfe156525425b9a8fc2f23f9fd :disappointed: 
Don't know how it got changed back.

**Review by anshumanv — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]
@Ploypiti Good work ! Keep it up.

**Comment by Ploypiti** [comment]
@anshumanv I think it's because you changed it in index.html not the student page ☺️

**Comment by anshumanv** [comment]
Ah, my bad, thanks for the fix @Ploypiti :smile:

**Pull request merged**
