### PR TITLE
Adding blog and image for Shreya Sandurkar

### PR DESCRIPTION
**Pull request by shreyasandurkar**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request
Added my image

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Pls change _data/blogs.yml file as well

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please add your blog in the blogs.yml file in the _data folder

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Close this as well, I guess :+1:

**Comment by nikit19** [comment]
Closing this PR as your other PR has been merged.

**Pull request closed without merging**
