### PR TITLE
update on fossasia 

### PR DESCRIPTION
**Pull request by ShivamRai2003**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by ParthS007** [comment]
@ShivamRai2003  Your PR is correct. Please reopen it

**Comment by ParthS007** [comment]
I am checking the Travis logs. Please wait

**Comment by ShivamRai2003** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/844
please see this one

**Comment by ShivamRai2003** [comment]
i have deleted it

**Comment by ShivamRai2003** [comment]
created new one

**Pull request closed without merging**
