### PR TITLE
Adding more to the code section

### PR DESCRIPTION
**Pull request by Raheel102**

### CODE REVIEW

**Comment by mananwason** [comment]
@Raheel102 Not working on my end. Please check once. Thanks!
screen shot 2016-01-24 at 1 07 40 pm

**Comment by Raheel102** [comment]
I think that'll do it :+1:

**Comment by jigyasa-grover** [comment]
@Raheel102 Unable to see the changes..

**Comment by Raheel102** [comment]
it should be good now

**Comment by jigyasa-grover** [comment]
Nope :/

**Comment by Raheel102** [comment]
I couldn't see past the DESIGN AND USABILITY page because i couldn't figure out how to get past it. Do you know how i could access it?

**Comment by Raheel102** [comment]
for some reason it wont work from just the index file but when i ran it on my local server it works! So i edited it a bit so i will squash those files together in a few minutes and you can check out the pics from here.
fashion1
fossasia1
loklak1

**Comment by Raheel102** [comment]
There we go i believe i am done :D

**Comment by sudheesh001** [comment]
@Raheel102 There's a small problem, clicking "Yes" on "Code" does take it into the required questions of Fashion (Make this `Fashion Tec`), loklak etc.., but this should be the same questions which should keep spinning in the tree, If i keep clicking No in these questions I get back to writing.

Have a look at mozilla's What can i do for mozilla website and just play with it to figure out the problem. http://whatcanidoformozilla.org/#!/progornoprog/softtest

**Comment by Raheel102** [comment]
I think i have fixed the issue

**Pull request merged**
