### PR TITLE
Update students.yml

### PR DESCRIPTION
**Pull request by ghost**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by codedsun** [comment]
@demonsingh336 Do we have a imagefile named that as mentioned?

**Comment by ghost** [comment]
no i am unable to upload the correct one(photo)

**Comment by codedsun** [comment]
@demonsingh336 Kindly update the PR with the same image file name to be added to the site.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Remove the merge conflicts !

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by ParthS007** [comment]
closing this PR as the student is already added 👍

**Pull request closed without merging**
