### PR TITLE
Intro to FOSSASIA

### PR DESCRIPTION
**Pull request by mohdtauseef**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by mohdtauseef** [comment]
Intro to FOSSASIA

**Review by mohdtauseef — COMMENTED** [review]
Intro to FOSSASIA

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please don't delete those lines of code. Right yours after that without the #

**Review by anshumanv — COMMENTED** [review]
Please go through the project's README to see how changes are to be made.

**Review by akshatnitd — COMMENTED** [review]
Add a new entry for your video, instead of replacing the sample format. Also, you need to upload an image for the video. Check README.md file for help.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Image is not there!

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please read `README.MD` on how to add a video.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

**Comment by mohdtauseef** [comment]
How to add image to my video project

**Review by rupav — COMMENTED** [review]
You need to add image in img/video section. Refer
https://github.com/fossasia/gci17.fossasia.org/pull/898/files .
Also please place your code to the last of the page not on the top.

**Review by isuruAb — COMMENTED** [review]
please place your code to the last of the page, not on the top.

**Review by realslimshanky — COMMENTED** [review]
Please follow others reviews and fix accordingly. Rest looks good. Nice job, keep it up :)

**Review by ParthS007 — COMMENTED** [review]
@mohdtauseef Closing this PR due to inactivity.Please read README.MD on how to add a video and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

**Pull request closed without merging**
