### PR TITLE
index.html: Adds map to support community bindings

### LINKED ISSUE #110: Add a map with co-ordiantes students and mentors
Just like the previous years website can we have a map with geo-cordinates of mentors and students.
I think it will be nice and foster community bondings.
We can use the geo locator used for that purpose: https://fossasia.github.io/geolocation/
(we can also use other geo locators available on thew web)
What do you think?

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds google map which will display blips according to mentor's and
students locations to improve community bindings.

Fixes #110 

Screenshots:
screenshot from 2017-12-04 18-52-46
screenshot from 2017-12-04 18-52-51

Live link to test: http://abishekvashok.github.io/gci17.fossasia.org/

### CODE REVIEW

**Review by NaviRocker — APPROVED** [review]

**Comment by abishekvashok** [comment]
Link to my task: https://codein.withgoogle.com/dashboard/task-instances/5402067608797184/

**Comment by anshumanv** [comment]
Looks good, can you provide a deployment link and please resolve conflicts? @abishekvashok

**Comment by abishekvashok** [comment]
@anshumanv link  was given in description,  http://abishekvashok.github.io/gci17.fossasia.org/

**Comment by akshatnitd** [comment]
@abishekvashok Please resolve the conflicts by updating the branch

**Comment by abishekvashok** [comment]
@anshumanv @akshatnitd done, please squash and merge.

**Comment by anshumanv** [comment]
Ah thanks for the link @abishekvashok, I think is missed to see in the PR comment.

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
