### PR TITLE
Added my Promotional Video :D

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/alezubangci17.fossasia.org/ --> Preview Link :D

**Comment by yashk0thari** [comment]
Please review and merge :D

**Review by abishekvashok — APPROVED** [review]

**Comment by yashk0thari** [comment]
Thanks for the review :D @abishekvashok

**Review by harshit98 — APPROVED** [review]
LGTM 💯 

I will merge this PR once Travis CI passes. 🎉

**Comment by yashk0thari** [comment]
Ohk, Thank you @harshit98 :D

**Review by nikit19 — APPROVED** [review]

**Comment by harshit98** [comment]
Resolve conflicts @Beta-King. Looks like Travis has been suspended.

**Comment by yashk0thari** [comment]
What are the conflicts ?? @harshit98

**Comment by harshit98** [comment]
@Beta-King `_data/video.yml` are having some conflicts. Resolve them.

**Comment by yashk0thari** [comment]
In the Preview Link; everything seems to work just fine @harshit98 can you please help me resolve these conflicts

**Review by harshit98 — CHANGES_REQUESTED** [review]
Why I'm not able to see any changes? I would suggest you create a fresh PR.

**Comment by yashk0thari** [comment]
Hmm, ohk :D

**Pull request closed without merging**
