### PR TITLE
Fixes #766 : Fixed Twitter logo in Footer.

### LINKED ISSUE #766: Twitter icon in footer not working.
### Expected results
The Twitter icons must be showing up.

### Actual results
They are not showing up.

### Would you like to work on this
**Yes.**

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

* Fixed arrows in Image Slider.
* Fixes #766

***Preview Link : https://duttaditya18.github.io/gci17.fossasia.org/***

### CODE REVIEW

**Comment by saarthakchats** [comment]
Can you provide screenshots?

**Comment by nzec** [comment]
@saarthakchats All right, here you go : 

Screenshot

**Review by saarthakchats — APPROVED** [review]
Looks good

**Review by arjunpandey2003 — APPROVED** [review]
LGTM!

**Review by codedsun — APPROVED** [review]

**Pull request merged**
