### PR TITLE
Fixed #645: Czech translation

### LINKED ISSUE #645: Thank you for contributing
The section has disappeared

### PR DESCRIPTION
**Pull request by samyakbvs**
Added Thai translation to the Thanks for contributing JS effect

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/translation-gci17.fossasia.org/

**Comment by arjunpandey2003** [comment]
LGTM!

**Review by arjunpandey2003 — APPROVED** [review]

**Comment by 0x48piraj** [comment]
I think, Thai was already present !

**Comment by samyakbvs** [comment]
Nope it wasn't

**Comment by Ploypiti** [comment]
@samyakbvs Well it already does, I added it myself.

**Comment by samyakbvs** [comment]
Changes made now is it fine?

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@samyakbvs  I am not able to see the addition as translation are not appearing, Please check this and update your PR 👍

**Comment by samyakbvs** [comment]
Okay

**Comment by samyakbvs** [comment]
Making another one

**Pull request closed without merging**
