### PR TITLE
Update custom.css. Added tada effect

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes issue #477 
Added Tada effect to projects in the student project section
Things done:

- Added Tada effect to student projects

- Updated custom.css

- Deploy link provided below

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
https://arjunpandey2003.github.io/gci17.fossasiapc.org/.

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please change the PR name as per best practices and you should keep the Pull Request template as it is and make the changes where its shown

**Comment by arjunpandey2003** [comment]
@ms10398 what do you mean i should keep the template same but make the changes where it is shown

**Comment by the-codingninja** [comment]
You should change the pull request template where it is required to tell the changes you have done

**Comment by arjunpandey2003** [comment]
Ok sure

**Comment by arjunpandey2003** [comment]
@ms10398 please see the updates. Thanks!

**Review by anshumanv — APPROVED** [review]
LGTM

**Review by saarthakchats — APPROVED** [review]
LGTM

**Review by ParthS007 — APPROVED** [review]

**Comment by arjunpandey2003** [comment]
@ParthS007 Thanks

**Pull request merged**
