### PR TITLE
Added Video --> Labyrinth (Promotional) :D

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/rollielogangci17.fossasia.org/ --> Preview Link :D

**Review by codedsun — APPROVED** [review]

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please provide an image which has the dimensions of 240 x 240 pixels

**Comment by yashk0thari** [comment]
Sorry for that; changing dimensions right now :D

**Comment by yashk0thari** [comment]
@nikit19 --> made changes :D

**Comment by yashk0thari** [comment]
please review and merge @nikit19

**Review by nzec — APPROVED** [review]
Looks good. But please fix the aspect ratio of the image.

**Comment by yashk0thari** [comment]
if i fix that, then the the image wont be 240x240 so i have to leave it this way :D

**Comment by yashk0thari** [comment]
can we merge now ?? :D

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Please look into some alternatives

**Comment by yashk0thari** [comment]
Hmm ohk :D

**Comment by yashk0thari** [comment]
Added a different image @0x48piraj

**Review by ShivamRai2003 — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
