### PR TITLE
Enhance student section and added my photo

### PR DESCRIPTION
**Pull request by AKostiv8**

### CODE REVIEW

**Comment by AKostiv8** [comment]
Preview link: https://akostiv8.github.io/gci17.fossasia.org/

**Review by anshumanv — APPROVED** [review]
Looks good!

**Review by yashLadha — APPROVED** [review]
LGTM

**Comment by anshumanv** [comment]
Please resolve conflicts and incorporate one missing mentor and student, this is good to go then! :smile:

**Comment by AKostiv8** [comment]
Resolved

**Comment by AKostiv8** [comment]
@anshumanv

**Comment by anshumanv** [comment]
Thanks for the quick fix @AKostiv8, however one student is still missing I think, can you please confirm? :smile:

**Comment by anshumanv** [comment]
There should be a total of 14 students with you added.

**Comment by AKostiv8** [comment]
Ok, I will fix it now)))

**Comment by AKostiv8** [comment]
@anshumanv

**Comment by anshumanv** [comment]
Thanks so much for your hard work and patience, merging.

**Comment by AKostiv8** [comment]
Thank you too :)

**Pull request merged**
