### PR TITLE
Image resized to 240X240

### LINKED ISSUE #179: Travis: Change the size of the images to 240 x 240
Change the size of the images listed in the image to 240 x 240

### PR DESCRIPTION
**Pull request by awesometushar000**
Fixes #179 
As a [GCI task](https://codein.withgoogle.com/dashboard/task-instances/6412267404918784/)
Error found [here](https://travis-ci.org/fossasia/gci17.fossasia.org/jobs/313342013#L686)

### CODE REVIEW

**Comment by awesometushar000** [comment]
https://awesometushar000.github.io/gci17.fossasia.org/

**Comment by awesometushar000** [comment]
Travis Error solved

**Comment by anshumanv** [comment]
Hey @awesometushar000 thanks, can you please resolve merge conflicts so this can be merged?

**Comment by awesometushar000** [comment]
@anshumanv Please see

**Comment by akshatnitd** [comment]
@awesometushar000 Great! Merging :)

**Comment by awesometushar000** [comment]
Thank You

**Pull request merged**
