### PR TITLE
Added installation files in Polish language #445

### PR DESCRIPTION
**Pull request by kubami9**
This PR refers to #445 

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

Added installation files in Polish language

### CODE REVIEW

**Review by NaviRocker — CHANGES_REQUESTED** [review]
It would be great If you could link these pages to the README.md

**Review by anshumanv — COMMENTED** [review]
Please link them here - https://github.com/fossasia/gci17.fossasia.org#installation-steps

**Review by ParthS007 — COMMENTED** [review]
@kubami9 Please link them to README.md and update your PR

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by kubami9** [comment]
@naveentherocker @anshumanv @ParthS007 done 😃

**Review by kavithaenair — APPROVED** [review]
LGTM :)

**Review by saurabhjn76 — APPROVED** [review]

**Comment by kavithaenair** [comment]
@kubami9 Please squash your commits so that it can be merged. Good job. 👍

**Comment by kubami9** [comment]
@kavithaenair squashed 😄

**Comment by supunTE** [comment]
@kubami9 Thanks for help in https://github.com/fossasia/gci17.fossasia.org/issues/445

**Pull request merged**
