### PR TITLE
Add border to Mentors, Contributors, and Students section.

### PR DESCRIPTION
**Pull request by Ploypiti**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Issue #269 point 5
- Add borders to mentors, contributors, students section to prevent confusion

### CODE REVIEW

**Comment by anshumanv** [comment]
Looks neat, please provide a test link to test your changes.

**Comment by Ploypiti** [comment]
Here's the screenshot https://ibb.co/dOoh4b

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by anshumanv** [comment]
Please try to give a test link, where we can see the changes live from next time, thanks! :smile: 
You can follow - https://pages.github.com/

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please provide a test Link @Ploypiti

**Comment by Ploypiti** [comment]
https://ploypiti.github.io/gci17.fossasia.org/ there you go :)

**Comment by ParthS007** [comment]
Good work @Ploypiti  ! Keep it up 👍

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
