### PR TITLE
Added blog info

### PR DESCRIPTION
**Pull request by awesometushar000**
As a [GCI task](https://codein.withgoogle.com/dashboard/task-instances/6175821603536896/)
https://meets2tushar.wordpress.com/2017/12/11/my-interaction-with-fossasia/
https://awesometushar000.github.io/gci17.fossasia.org/

### CODE REVIEW

**Comment by anshumanv** [comment]
Please give a test link.

**Comment by ParthS007** [comment]
@anshumanv It is provided already :smiley:

**Review by ParthS007 — APPROVED** [review]
LGTM ! Good work !

**Review by the-codingninja — APPROVED** [review]

**Comment by ParthS007** [comment]
@anshumanv Why there is 3 blog with same pic

**Pull request merged**
