### PR TITLE
Fixed Issue #741

### PR DESCRIPTION
**Pull request by aryan-02**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Preview link: https://aryan-02.github.io/fossasiagci/
- Fixes`#741`

Earlier, there was a black section in the site, without any content. I noticed that it was an incomplete text-typing effect. I fixed it by linking the JavaScript correctly using a plugin called "Typed.js"

### CODE REVIEW

**Comment by aryan-02** [comment]
Before: gci17.fossasia.org
After: https://aryan-02.github.io/fossasiagci/

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash the commits :+1:

**Comment by aryan-02** [comment]
@0x48piraj I'm sorry I'm new to GitHub. Could you please help me with how to squash commits?

**Comment by aryan-02** [comment]
Oh, I'm sorry, I guess I just did something disastrous while trying to squash my commits :(

**Comment by aryan-02** [comment]
Let me just create a new pull request...

**Comment by aryan-02** [comment]
I'm extremely sorry about the inconvenience. I'm closing this pull request and creating a new one with commits organised correctly...

**Comment by 0x48piraj** [comment]
No problem mate. :+1:

**Comment by aryan-02** [comment]
Okay, it seems creating a new pull request won't do the work...

**Comment by aryan-02** [comment]
The only problem is that it's showing some previous commits in my pull request, so it won't change the content...

**Comment by aryan-02** [comment]
If you directly merge the way you normally would, it won't affect any data, except that it'll show that 2 people made the previous few commits. So, I'll recommend selectively merging. The steps are mentioned in the answers to this question on StackOverflow: https://stackoverflow.com/questions/7217031/github-accept-pull-request-but-only-some-commits

**Comment by aryan-02** [comment]
If you just merge the commits ea0dbc0 and 7dd09f2, it'll do everything correctly.

**Comment by aryan-02** [comment]
So basically, 
```
git cherry-pick ea0dbc0
git cherry-pick 7dd09f2
```

**Comment by aryan-02** [comment]
Okay, let me try to fix it from my side

**Comment by aryan-02** [comment]
Okay, I don't find any way to fix that from my side, could you please selectively merge?

**Comment by aryan-02** [comment]
(Or if that small issue does not make a difference, a regular merge?)

**Comment by aryan-02** [comment]
Or rather, let me fork the repository again, upload the files and then make a new pull request

**Pull request closed without merging**
