### PR TITLE
Update header.html (Made necessary code changes to make the 'ENG' dropdown visible)

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`
#616; i've fixed this issue !!

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Louisgci17.fossasia.org/ --> preview link...

**Comment by yashk0thari** [comment]
screen shot 2017-12-29 at 11 37 17 pm

**Comment by yashk0thari** [comment]
Can we merge if there are no conflicts ??

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@Beta-King I am not able to reproduce the issue, can you just recheck again by pulling latest changes. Thanks 👍

**Comment by yashk0thari** [comment]
@ParthS007; im having this problem; checked in multiple browsers (Chrome and Safari) im still getting this ...
screen shot 2017-12-30 at 10 21 01 am

**Comment by yashk0thari** [comment]
But its working in another computer; maybe there is something wrong with mine, kk

**Pull request closed without merging**
