### PR TITLE
Fixed #505: Chinese translation (Simplified)

### LINKED ISSUE #505: Transalation
### Expected results
The website should be translated into at least 4 other languages
### Actual results
The website hasn't been translated even in one
## Would you like to work on this
Yes! Pls don't work on this issue without my consent

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Add related issue no. and also describe what the PR does. Add relevant screenshots and deployment link.

**Comment by samyakbvs** [comment]
I did add a related issue number and stated that it converts the site to chinese

**Comment by samyakbvs** [comment]
I am not able to provide a deployment link due to many branches some error is occurring but the purpose of the PR is that it takes the user to the Chinese translated site when he/she click on Chinese
site - https://translate.google.com/translate?hl=en&sl=en&tl=zh-CN&u=https%3A%2F%2Fgci17.fossasia.org%2F
@akshatnitd

**Comment by samyakbvs** [comment]
I have provided a test link link in every PR I hope you will understand why am I not able to do provide it this time and just not take it as an excuse, you can see the code there is nothing wrong

**Review by NaviRocker — APPROVED** [review]
Don't forget that there are 2 Chinese Languages: Simplified and Traditional. Try to mention that. Then it would be fine.

**Comment by samyakbvs** [comment]
Thanks for mentioning it @naveentherocker

**Comment by samyakbvs** [comment]
closes #505

**Comment by NaviRocker** [comment]
No Problem @samyakbvs

**Pull request closed without merging**
