### PR TITLE
#324 Added Video

### PR DESCRIPTION
**Pull request by arjunpandey2003**

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
please squash your 2 commits

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please provide a preview link

**Comment by arjunpandey2003** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/405

**Comment by arjunpandey2003** [comment]
https://arjunpandey2003.github.io/gci17.fossasiaarjun.org/.

**Comment by arjunpandey2003** [comment]
https://arjunpandey2003.github.io/gci17.fossasiaarjun.org/.

**Review by ParthS007 — COMMENTED** [review]
@arjunpandey2003  Please resolve conflicts, else look fine !

**Comment by arjunpandey2003** [comment]
Conflicts Resolved

**Comment by arjunpandey2003** [comment]
Could Please approve the request

**Review by akshatnitd — CHANGES_REQUESTED** [review]
@arjunpandey2003 You need to change the image also. It would be better to task a screenshot of the video at any instance :) Make sure that the image is 240x240 px in size.

**Review by akshatnitd — COMMENTED** [review]
@arjunpandey2003 Please resolve the conflicts!

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Resolve conflicts & squash commits! :sweat_drops:

**Pull request closed without merging**
