### PR TITLE
Added my blog

### PR DESCRIPTION
**Pull request by saarthakchats**

### CODE REVIEW

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/gci1tidstdgidfgsdesgredfsen7.fossasia.org/

**Comment by saarthakchats** [comment]
Og

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@saarthakchats  Please use image of dimension `240*240` only

**Comment by saarthakchats** [comment]
@ParthS007 
I'll make a new PR

**Pull request closed without merging**
