### PR TITLE
Fixed #518 && #505

### LINKED ISSUE #518: Restore the contributors section
The contributor's section has been damaged it has to be restored the way it was
I am working on it, please don't take up this without my consent

### PR DESCRIPTION
**Pull request by samyakbvs**
I restored the contributors' section which was haywire before and also added Chinese(simplified) translation to the site

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/demo-gci17.fossasia.org/ - test link

**Comment by samyakbvs** [comment]
Closes #518 
Closes #505

**Review by anshumanv — APPROVED** [review]
LGTM, squash commits.

**Comment by samyakbvs** [comment]
Done @anshumanv

**Review by NaviRocker — APPROVED** [review]

**Comment by vaibhavsingh97** [comment]
@samyakbvs Please use some human friendly commit message. As 2 months down the line no one remember the number 😅

**Pull request merged**
