### PR TITLE
Student Project : Blog Engine made on Flask (Beautiful Flask)

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

* Added Student Project : Blog Engine made on Flask (Beautiful Flask)

***Preview Link : https://duttaditya18.github.io/gci17.fossasia.org/#projects***

### CODE REVIEW

**Comment by anshumanv** [comment]
Improve the commit message, whose student project did you add? Reference the issue that you solved in this.

**Review by NaviRocker — APPROVED** [review]
LGTM

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@duttaditya18  Please do the suggested changes

**Comment by ParthS007** [comment]
@duttaditya18 Please add proper PR message and resolve conflicts 👍

**Comment by nzec** [comment]
@ParthS007 @naveentherocker @anshumanv Made a new PR here : #535

**Pull request closed without merging**
