### PR TITLE
for issue - #422 - Added a back to top button.  

### PR DESCRIPTION
**Pull request by supunTE**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- https://stedirisuriya.github.io/gci17.fossasia.org/
- Fixes https://github.com/fossasia/gci17.fossasia.org/issues/422
- Add a back to top button.

### CODE REVIEW

**Review by NaviRocker — APPROVED** [review]
Good Job. LGTM.

**Comment by gabru-md** [comment]
@STEdirisuriya the animation is mind blowing :+1:

**Review by gabru-md — APPROVED** [review]
Awesome

**Review by abishekvashok — APPROVED** [review]
LGTM

**Comment by supunTE** [comment]
https://github.com/fossasia/gci17.fossasia.org/issues/422

**Pull request merged**
