### PR TITLE
Updated my information

### PR DESCRIPTION
**Pull request by abhinavraj0123456789**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Review by akshatnitd — CHANGES_REQUESTED** [review]
The image is missing. Kindly add it to the PR.

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Pls add your image

**Comment by abhinavraj0123456789** [comment]
abhinav

**Comment by abishekvashok** [comment]
@abhinavraj0123456789 to the ./img/students folder please

**Comment by akshatnitd** [comment]
@abhinavraj0123456789 
Add the image to the PR, not in the comments.
`* First add this photo in the ```img/students/``` folder
* Then,
 ```
git add <image-path>
git commit --amend
git push origin <branch-name> -f
```

This would do !

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@abhinavraj0123456789 Please see the instructions in `README.md`

**Comment by the-codingninja** [comment]
All interactions will be followed up on https://github.com/fossasia/gci17.fossasia.org/pull/155

**Pull request closed without merging**
