### PR TITLE
Added a different link to the video :D Added Asciicast video and Made alignment :D

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`
#908 --> this is the issue i fixed, rest i have added :D

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/rainbowgodgci17.fossasia.org/ --> Preview Link :D

**Comment by yashk0thari** [comment]
I have made this PR to change the link to a video which was merged and was under-timed, so i have added more content to the video and so increased the time to make the video acceptable :D

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please squash all your commits into one. Rest looks good. Good work, keep it up :)

**Comment by yashk0thari** [comment]
Squashed all commits @realslimshanky, could you approve now ??

**Review by realslimshanky — APPROVED** [review]

**Review by sayak119 — CHANGES_REQUESTED** [review]
Please mention issue number that you have fixed

**Comment by yashk0thari** [comment]
#908 --> this is the issue i fixed, rest i have added :D

**Comment by yashk0thari** [comment]
@sayak119 could you approve now ??

**Comment by realslimshanky** [comment]
> #908 --> this is the issue i fixed, rest i have added :D

Please add this to the main PR description on the top.

**Review by rupav — APPROVED** [review]
LGTM

**Pull request merged**
