### PR TITLE
Added a video

### PR DESCRIPTION
**Pull request by samyakbvs**
I added a video for Fossasia Summit to the video section

### CODE REVIEW

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
Please share demo link

**Comment by samyakbvs** [comment]
I can't

**Comment by samyakbvs** [comment]
As one of my PR is already pending

**Comment by samyakbvs** [comment]
@vaibhavsingh97

**Review by nikit19 — APPROVED** [review]

**Review by nikit19 — CHANGES_REQUESTED** [review]
name of the image is FOSSASIA.jpeg please change it

**Comment by samyakbvs** [comment]
@nikit19 now can you merge?

**Review by codedsun — APPROVED** [review]

**Review by nikit19 — APPROVED** [review]

**Comment by samyakbvs** [comment]
Pls merge @nikit19

**Comment by samyakbvs** [comment]
Thanks @codedsun

**Pull request merged**
