### PR TITLE
Andre Christoga's Profile.

### PR DESCRIPTION
**Pull request by drepram**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- I've added my avatar and added my name and social links to the students YAML config.

### CODE REVIEW

**Comment by yashLadha** [comment]
Please provide a deployment link

**Comment by yashLadha** [comment]
Only tick fields that you have done. Do not unnecessarily mark all the fields.

**Review by yashLadha — CHANGES_REQUESTED** [review]
Request a demo link

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please upload your image in the img/students folder

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Pls add your image

**Comment by abishekvashok** [comment]
Deployment link: https://acga.github.io/gci17.fossasia.org

**Comment by drepram** [comment]
Here's the preview screenshot :

**Review by nikit19 — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]

**Review by akshatnitd — APPROVED** [review]
Great work :)

**Pull request merged**
