### PR TITLE
Added link and image of my blog

### PR DESCRIPTION
**Pull request by AmanSingh200**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Squashed the commits.
- [ ] Included a description of change below.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
Resolve conflicts, please.

**Review by nikit19 — COMMENTED** [review]
Please resolve conflicts. Rest looks good :+1:

**Review by isuruAb — COMMENTED** [review]
please squash commits and resolve conflicts

**Comment by AmanSingh200** [comment]
resolved the conflict

**Comment by AmanSingh200** [comment]
done

**Comment by harshit98** [comment]
@AmanSingh200 I have merged your pull request. Kindly next time squash your commits.

**Pull request merged**
