### PR TITLE
Added image and updated blog.yml 

### PR DESCRIPTION
**Pull request by TechnoAman**
added name,country,github id,image,twitter handle
deleted the old image and added new resized image. aman1.jpg
merged conflicts.

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — COMMENTED** [review]
Why are you submitting half the changes in one pull request and the other half in another one?
You are doing it correctly but all these changes should be in one pull request.

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@TechnoAman  Haven't you read `README.md` yet. Please read it and first please close all other PRs

**Comment by TechnoAman** [comment]
how to make all the changes inside the same pull request

**Comment by nikit19** [comment]
@TechnoAman make changes in your forked repository and they will reflected here automatically. Just make sure you are on the same branch from where you sent the pull request.

**Comment by TechnoAman** [comment]
Thanks I have made the changes and updated the pull request

**Comment by supunTE** [comment]
Resolve conflicts

**Review by TechnoAman — COMMENTED** [review]
do I have to remove these lines

**Comment by TechnoAman** [comment]
Do l have to remove students. Yml file from my pull request

**Comment by TechnoAman** [comment]
Do I have to remove the students. Yml file from my pull request. Please
reply as soon as possible.

**Review by harshit98 — APPROVED** [review]
LGTM. 💯

**Comment by TechnoAman** [comment]
ParthS007 requested some changes .I didnot undérstand what changes I have
to make

**Review by TechnoAman — COMMENTED** [review]
I have read the  readme file and make changes

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
