### PR TITLE
Mentor's bio and photo

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
@anshumanv 
I am not able to figure out that how would we exclude the older commits

**Comment by anshumanv** [comment]
You need to update your fork with the upstream repository.

**Comment by abishekvashok** [comment]
@samyakbvs  rebase your fork, you can also fetch from upstream in a new branch and apply the only required changes there.

**Comment by nzec** [comment]
@samyakbvs You need to force push.
https://stackoverflow.com/questions/43567577/what-is-the-different-between-force-push-and-normal-push-in-git

**Comment by agbilotia1998** [comment]
@samyakbvs please resolve conflicts in mentors.yml

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Kindly resolve the conflicts

**Comment by NaviRocker** [comment]
Please Squash your commits after resolving the Conflicts.

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by ParthS007** [comment]
@samyakbvs  If you are facing issue in resolving conflicts and excluding old commits, You can close this PR and open a fresh one but please pull the changes in your local repo and update your fork before making a new one .

**Comment by ParthS007** [comment]
@anshumanv  should we close this ?

**Comment by anshumanv** [comment]
Yes, no activity on this despite the user being active. Please go ahead @ParthS007 :+1:

**Pull request closed without merging**
