### PR TITLE
Added multiple new animations to repos.html

### LINKED ISSUE #397: Add multiple new animations to `repos.html`
### Expected results

**Multiple new animations to `repos.html`**
 
### Actual results

**No animations yet.**

## Would you like to work on this
Yes :fire:

### PR DESCRIPTION
**Pull request by 0x48piraj**
# Fixes #397

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Added multiple new animations to `repos.html`. :sparkles: 
- Added a rich library and a default `styles.css` to easily integrate/use/implement that library. **(Modular)** :sunglasses: 
- **_Preview - https://0x48piraj.github.io/gci17.fossasia.org/repos.html_**

### CODE REVIEW

**Review by the-codingninja — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]

**Comment by vaibhavsingh97** [comment]
@ms10398 Have you checked PR carefully? The alignment of Github-icon is not there

**Comment by the-codingninja** [comment]
Can you provide me a screenshot which github icon exactly

**Comment by 0x48piraj** [comment]
image

**It's in center.**

**Comment by vaibhavsingh97** [comment]
@ms10398 Oops!! Sorry It was my internet 😢 
Some CSS files not loaded and github icon is not centerd. but checked again and it's look fine. Sorry for the trouble

**Comment by the-codingninja** [comment]
No issues @vaibhavsingh97 :sweat_smile:

**Pull request merged**
