### PR TITLE
add my blog

### PR DESCRIPTION
**Pull request by ShubhamGhanmode2**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by rupav — CHANGES_REQUESTED** [review]
Provide  preview link. Also please change PR commit message. "Add my blog" will do.

**Comment by ShubhamGhanmode2** [comment]
Can you please tell me what do you mean by preview link

**Comment by rupav** [comment]
You can see in settings of your forked repo. Its https://shubhamghanmode2.github.io/gci17.fossasia.org/ . your changes are affected in this website.

**Review by rupav — APPROVED** [review]

**Comment by rupav** [comment]
Good work 👍 , you can now submit for review your code-in task. From next time you need to squash your commits to 1. (e.g. its 5 commits in this case, which you need to squash into 1)

**Comment by ShubhamGhanmode2** [comment]
Thanks a lot

**Pull request merged**
