### PR TITLE
 mhlee304's Blog

### PR DESCRIPTION
**Pull request by mhlee304**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [X ] Read and understood (see CONTRIBUTING.md)
- [X ] Included a Preview link and screenshot showning after and before the changes.
- [ X] Images are `240 x 240` [w x h].
- [X ] Included a description of change below.
- [ X] Squashed the commits.

# Changes done in this Pull Request
2
- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Looks good just make sure that the dimensions of the image is 240 x 240 pixels

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@mhlee304  Good work , only change you have to do is resize your blog's image to `240 * 240` dimension and your PR is ready  to merge

**Review by nikit19 — APPROVED** [review]

**Review by codedsun — APPROVED** [review]

**Review by isuruAb — COMMENTED** [review]
please squash your commits

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash commits.

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@mhlee304  why you are deleting someone else blog photo, please remove that commit.

**Comment by harshit98** [comment]
Resolve conflicts as well @mhlee304.

**Review by ParthS007 — COMMENTED** [review]
@mhlee304 closing this PR as there are some conflicts. Please read README.md on how to add a blog and ask on Gitter channel if you face any difficulties and create a new PR.

**Pull request closed without merging**
