### PR TITLE
Added image properly :D

### PR DESCRIPTION
**Pull request by yashk0thari**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`
#683 - I've solved this issue !!

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Allahgci17.fossasia.org/ --> Preview Link !!

**Comment by yashk0thari** [comment]
please review :>

**Review by abishekvashok — APPROVED** [review]

**Review by nikit19 — CHANGES_REQUESTED** [review]
Looks good just delete the unused image

**Comment by yashk0thari** [comment]
I deleted it; i just had to change the extension to make it work :D

**Comment by yashk0thari** [comment]
ohk i understood :D thanks

**Comment by yashk0thari** [comment]
squashed commits too; can we merge now ?? :D

**Comment by yashk0thari** [comment]
can we merge ??

**Review by nikit19 — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
