### PR TITLE
Add blog link and upload image

### PR DESCRIPTION
**Pull request by MomtahinaKarim**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

### CODE REVIEW

**Review by nikit19 — COMMENTED** [review]
You have already added your blog. Why are you doing the same thing again ?

**Review by abishekvashok — CHANGES_REQUESTED** [review]
I saw yours where commitee by @nikit19

**Comment by MomtahinaKarim** [comment]
I thought it was not right. Now what should I do?

**Comment by nikit19** [comment]
Just close this pull request

**Pull request closed without merging**
