### PR TITLE
Fixes #514 :Added contributors section on navbar

### LINKED ISSUE #514: Contributors Section not on the Navbar
### Expected results
All sections linked on the navbar
### Actual results
Contributors' section missing
### Steps to reproduce the issue
Add it
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #514 

# Things done in this Pull Request
Added contributors' section on navbar
[Deploy link](https://saarthakchats.github.io/supari/)

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by anshumanv** [comment]
@saarthakchats you need to update your fork btw, it's running a very old version.

**Review by saurabhjn76 — APPROVED** [review]

**Review by NaviRocker — APPROVED** [review]

**Comment by saarthakchats** [comment]
@saurabhjn76 @anshumanv 
Can we merge

**Comment by saarthakchats** [comment]
There are no conflicts

**Comment by vaibhavsingh97** [comment]
@saurabhjn76 @anshumanv Please review PR's correctly as due this `gci17.fossasia.org` is broken. And it's very clear as deployment link given by him is also broken. Do final review before merge

**Pull request merged**
