### PR TITLE
Fixes #742 : Made the video section responsive.

### LINKED ISSUE #742: Make the video section responsive
### Expected results
A responsive video section.

### Actual results
Not responsive.

The blog section was made responsive by #569 but the same styles were not applied on the Video Section.

## Would you like to work on this
**If anyone wants to work on this, go ahead!**

### PR DESCRIPTION
**Pull request by nzec**
- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

* Made the video section responsive.
* Fixes #742

***Preview Link : https://duttaditya18.github.io/gci17.fossasia.org/***

---

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
screen shot 2018-01-02 at 6 46 06 pm

It shows like this when screen width is 1383px. please check

**Comment by nzec** [comment]
@isuruAb Yes. What's the problem with that? You want them to be centrally aligned as well?

**Comment by harshit98** [comment]
@duttaditya18 Try to improve the responsiveness if you can. This is what @isuruAb meant.

**Comment by nzec** [comment]
@harshit98 What is the problem? Compare the previous one with what it is now. The image used to stretch, now it doesn't. I only made that change.

**Review by 0x48piraj — COMMENTED** [review]
Try manipulating the css class *(width)*

**Pull request closed without merging**
