### PR TITLE
GCI 2017 - New Data Entry Under _data/students.yml and img/students

### PR DESCRIPTION
**Pull request by ChenNuode**
I added my details and my image.
 ~ nuodebot

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please don't remove other images.

**Comment by anshumanv** [comment]
Can you improve the image by using your photo?

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please do the suggested changes & resolve conflicts.It will be better if you use your own photo. 👍

**Comment by ChenNuode** [comment]
I already submitted successfully on another pull request.

**Pull request closed without merging**
