### PR TITLE
MY BLOG (FOSSASIA AND ME)

### PR DESCRIPTION
**Pull request by kaushikichhabra**
This is the link to my blog...
fossasiasblog.wordpress.com
Please grant permission to my work...
Thanks
Your Sincerely 
Kaushiki

### CODE REVIEW

**Comment by harshit98** [comment]
@kaushikichhabra You have not updated your branch. Please check. The changes and blog of yours is not there.

**Comment by abishekvashok** [comment]
@kaushikichhabra pls resolve conflicts

**Comment by kaushikichhabra** [comment]
Sorry...
I don't what is my branch?

**Comment by kaushikichhabra** [comment]
Is there a need for any other changes to be done...and please review my work as well as grant permission...also please clear out what it means "i haven't updated my  branch"
Thankyou to all the members of FOSSASIA for co-operating with me and always helping me when I needed help!
Happy New Year!
Have a Great Year Ahead!!

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please fork this repository and then send a pull request.
These links might help you
https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/README.md
https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/installation/installation_windows.md

**Comment by kaushikichhabra** [comment]
Sure...I am working in it...

**Comment by kaushikichhabra** [comment]
There is no  option for me to create my pull request...
Now should I simply just create a pull request following the same format?
thanks for helping me with this!

**Comment by kaushikichhabra** [comment]
I have even forked the respository...

**Comment by nikit19** [comment]
Make the required changes in your fork.
Commit those changes and then send a pull request from your forked repository

**Comment by kaushikichhabra** [comment]
I have done that...please check and reply...
Thanks to all for your support and help...

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved :+1:

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by kaushikichhabra** [comment]
Hello everyone...
This is regarding time extension of this task( create a blog )
I am not at my place.. and I am still not able to create a pull request. I
have just sent a pull request. But I am not sure if it is right or not...
Thanks to all the mentors of FOSSASIA...for helping me so much...I really
appreciate your co-operation.
Thanks
Your Sincerely
Kaushiki Chhabra

**Comment by nikit19** [comment]
@kaushikichhabra can you post the link of your task ? I will increase the time

**Comment by kaushikichhabra** [comment]
https://codein.withgoogle.com/dashboard/task-instances/6017835425857536/
THANKYOU SO MUCH!

**Comment by codedsun** [comment]
@kaushikichhabra resolve conflicts

**Comment by kaushikichhabra** [comment]
Thank u @nikit bhandari
For extending my time...

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Closing this PR, please read `README.md` on how to add a blog and If you face any difficulty ask on FOSSASIA Gitter channel and make a PR.Thanks

**Pull request closed without merging**
