### PR TITLE
Add video

### PR DESCRIPTION
**Pull request by notsoocool**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

-  This is my live task link https://codein.withgoogle.com/dashboard/task-instances/4958290263932928/
-  Added image in img/video folder.
-  Updated information video.yml 
-  My preview link is https://yajushvyas.github.io/gci17.fossasia.org/

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please read the README.md on how to add your video.
Ensure that the dimensions of the image are 240 x 240 pixels

**Review by isuruAb — COMMENTED** [review]
please remove unwanted images

**Review by akshatnitd — APPROVED** [review]
Great work! Check I have updated the preview link in your comment.

Since, its your first time, please squash the commits from next time :)

**Comment by notsoocool** [comment]
Thank you @akshatnitd

**Pull request merged**
