### PR TITLE
blogs.ymll

### PR DESCRIPTION
**Pull request by kaushikichhabra**
url: https://fossasiasblog.wordpress.com/blog/
title: FOSSASIA AND ME
img: 567.jpg
author_name: Kaushiki_ Chhabra

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@kaushikichhabra Closing this PR as It have lots of previous commits.Please read `README.md` on how to add a blog or you may ask other GCI participants for help on FOSSASIA Gitter channel.

**Comment by kaushikichhabra** [comment]
My time has expired  for submission
I am trying  to reclaim it

**Comment by kaushikichhabra** [comment]
A request...please write the steps to create a pull request from the data
folder

**Comment by kaushikichhabra** [comment]
Please send the steps to create  a pull request from the data/blogs folder..

**Pull request closed without merging**
