### PR TITLE
 Adding right sized images

### PR DESCRIPTION
**Pull request by samyakbvs**
Added my blog and photo

### CODE REVIEW

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Can't see the image in the diff. Pls add it :) 
Also if you could squash the commits it would be awesome.

**Comment by samyakbvs** [comment]
@akshatnitd

**Comment by akshatnitd** [comment]
@samyakbvs I can see that the indentation is not correct. Kindly fix it, along with the indentation of the other 2 blogs.  

Also, squash the commits into 1, that would be great :)

**Comment by samyakbvs** [comment]
Can you pls guide me on how to squash the comits

**Comment by samyakbvs** [comment]
#166 fixed

**Comment by samyakbvs** [comment]
@akshatnitd  I have also made the changes to the image sizes to bring them in the correct so please approve them too :)

**Comment by akshatnitd** [comment]
@samyakbvs Great work :) Please squash the commits and remove the conflict. Then, it will be ready to merge :)

Also, thanks for resizing the images :100:

**Comment by samyakbvs** [comment]
Can you please explain to me that whats the conflict

**Comment by isuruAb** [comment]
@samyakbvs  you can check conflicts by clicking the "Resolve conflicts" button

**Comment by samyakbvs** [comment]
screen shot 2017-12-07 at 10 56 39 pm
screen shot 2017-12-07 at 10 56 22 pm
If i click on resolve conflicts it takes me to this but still this is not helping me in identifying the conflicts

**Comment by samyakbvs** [comment]
Actually I am new to command line so pls can you help me out here

**Comment by samyakbvs** [comment]
@akshatnitd @isuruAb

**Comment by isuruAb** [comment]
@samyakbvs did you try to solve conflicts ? what are the problems you have ?

**Comment by samyakbvs** [comment]
I can't see any problems in the code
@isuruAb

**Comment by isuruAb** [comment]
@samyakbvs yes there is no any problem in your code. please read this to resolve conflicts
https://help.github.com/articles/resolving-a-merge-conflict-on-github/

**Comment by samyakbvs** [comment]
Done?

**Comment by samyakbvs** [comment]
And pls can I be excused for not squashing the commits

**Comment by samyakbvs** [comment]
I mean can this be merged without me squashing the commits

**Comment by samyakbvs** [comment]
Thanks @isuruAb

**Comment by samyakbvs** [comment]
@akshatnitd

**Comment by akshatnitd** [comment]
@samyakbvs Merging :rocket: Make sure you learn how to squash and follow it in your next PRs.

**Comment by samyakbvs** [comment]
@anshumanv pls see my new task

**Comment by anshumanv** [comment]
@samyakbvs please communicate your queries on the gitter channel
, we all are available there to assist you. If reviewing your task is delayed then post on the community gitter channel please.

**Comment by samyakbvs** [comment]
okay i am sorry

**Comment by anshumanv** [comment]
No need to be sorry :smile: It's a general practice, and you didn't know it.
It's the sole motive of GCI to get accustomed with best practices of Open Source. :smile: 

Cheers!

**Pull request merged**
